import { SymbolLibraryItem } from '../../types';

export const ANIMAL_SYMBOLS: SymbolLibraryItem[] = [
  {
    id: 'sym-wolf',
    name: 'Kurt (Wolf)',
    category: 'Hayvan',
    subcategory: 'Sürü Sadakati & Vahşi Sezgi',
    meaning: 'Özgürlük, sezgisel rehberlik, sürü sadakati, vahşi içgüdü ve bağımsız liderlik.',
    archetypes: ['Lider', 'Rehber', 'Yol Gösterici'],
    positiveThemes: ['sezgisel pusula', 'bağımsızlık', 'sürü koruyuculuğu', 'cesur liderlik'],
    shadowThemes: ['yalnız kurt sendromu', 'yabancılaşma', 'saldırganlık'],
    relatedChakras: [3, 6],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [1, 7],
    relatedAstrology: ['Koç', 'Yay'],
    relatedEnneagram: [8, 6],
    relatedTotemThemes: ['gece uluması', 'alfa bakışı', 'keskin koku alma'],
    suitableFor: ['Kendi yolunu çizen, bağımsızlığına düşkün ama sevdiklerini canı pahasına koruyanlar'],
    avoidWhen: ['Yalnızca yumuşak, evcil ve tamamen teslimiyetçi arayışlar'],
    designCompatibility: {
      recommendedStyles: ['Geometric Linework', 'Micro Realism', 'Single Line Abstract', 'Dotwork'],
      bodyPlacements: ['Önkol Dış', 'Omuz / Pazu', 'Sırt Kürek Kemiği', 'Baldır'],
      compositionRole: 'Merkezi arketip odak veya dinamik yönlendirici hat',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dinamik 3 açılı kırık yön hatları, yukarı bakan sivri alfa açısı ve negatif alanda oluşturulan keskin göz boşluğu'
    },
    visualDescription: 'Vahşi asil kurt profili, arkasında ay halesi veya kırık geometrik 03RL yön çizgileri.',
    numerologyConnection: 'Yaşam Yolu 1 (Liderlik) ve 7 (İçsel İnziva/Sezgi)',
    astrologyConnection: 'Koç (Ares cesareti) ve Yay (Gezgin ruh)',
    enneagramConnection: 'Tip 8 (Meydan Okuyan) & Tip 6 (Sadık Muhafız)',
    visualKeywords: ['howling wolf silhouette', 'dire wolf portrait', 'mystic eyes', 'lunar background']
  },
  {
    id: 'sym-raven',
    name: 'Kuzgun (Raven)',
    category: 'Hayvan',
    subcategory: 'Simya & Boyutlar Arası Zeka',
    meaning: 'Boyutlar arası geçiş, simya, kadim sırlar, hafıza ve zihinsel uyanış.',
    archetypes: ['Simyacı', 'Büyücü', 'Gözlemci'],
    positiveThemes: ['yüksek zeka', 'gölge bilgeliği', 'boyutlar arası rehberlik', 'dönüşüm'],
    shadowThemes: ['kara haber takıntısı', 'aşırı kuşkuculuk'],
    relatedChakras: [6, 7],
    relatedElements: ['Hava', 'Eter'],
    relatedNumerology: [7, 11],
    relatedAstrology: ['Akrep', 'Kova'],
    relatedEnneagram: [5, 4],
    relatedTotemThemes: ['siyah tüyler', 'parlak zeki göz', 'alchemical kafatası'],
    suitableFor: ['Karanlığın içindeki bilgeliği gören, analitik ve mistik zekaya sahip arayışçılar'],
    avoidWhen: ['Yüzeysel renkli ve çocuksu masumiyet projeleri'],
    designCompatibility: {
      recommendedStyles: ['Etching / Gravür', 'Fine Line Feather', 'Blackwork Gothic'],
      bodyPlacements: ['Önkol', 'Omuz Başı', 'Sırt'],
      compositionRole: 'Merkezi mistik gözlemci veya tepe refakatçisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Açılı tüy siluetleri, alchemical hekzagon ve zikzak hava akış çizgileri'
    },
    visualDescription: 'Kömür siyahı tüyler, hafif açık gaga, gözlerinde zeka ışıltısı ve arkasında geometrik hekzagram.',
    numerologyConnection: 'Yaşam Yolu 7 (Mistik Derinlik) & Üstat 11',
    astrologyConnection: 'Akrep (Gölge derinliği) ve Kova (Yüksek zeka)',
    enneagramConnection: 'Tip 5 (Gözlemci) & Tip 4 (Mistik Bireyci)',
    visualKeywords: ['black raven feathers', 'alchemical raven', 'skull and raven', 'flying corvid']
  },
  {
    id: 'sym-serpent',
    name: 'Yılan / Ouroboros (Serpent / Kundalini)',
    category: 'Hayvan',
    subcategory: 'Kundalini & Deri Değiştirme',
    meaning: 'Deri değiştirme, ölüm ve yeniden doğuş, kundalini yaşam enerjisi ve şifa.',
    archetypes: ['Simyacı', 'Şifacı', 'Dönüştürücü'],
    positiveThemes: ['eskiyi geride bırakma', 'yaşam enerjisi (Kundalini)', 'şifa kudreti', 'yenilenme'],
    shadowThemes: ['zehir saçma', 'sinsilik korkusu'],
    relatedChakras: [1, 2, 7],
    relatedElements: ['Toprak', 'Ateş', 'Su'],
    relatedNumerology: [8, 9],
    relatedAstrology: ['Akrep', 'Balık'],
    relatedEnneagram: [8, 9],
    relatedTotemThemes: ['sarmal omurga', 'çatallı dil', 'parlak pullar'],
    suitableFor: ['Hayatında köklü bir deri değiştirme ve dönüşüm yaşayanlar'],
    avoidWhen: ['Yılan fobisi olan danışanlarda kesinlikle soyut geometrik çizgilere dönüştürülmelidir'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Scalework', 'Single-Line Spiral', 'Blackwork Coiled'],
      bodyPlacements: ['Kol Sarmalı', 'Önkol İç', 'Omurga', 'Bilek'],
      compositionRole: 'Tüm kompozisyonu birbirine bağlayan kıvrımlı sarıcı akış',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Çift kıvrımlı S-eğrisi, kundalini spirali ve eşmerkezli dalga hatları'
    },
    visualDescription: 'Bıçak veya aya sarılmış pul pul işlenmiş zarif yılan gövdesi, akışkan kıvrımlar.',
    numerologyConnection: 'Yaşam Yolu 8 (Dönüşüm) ve 9 (Bitiş ve Başlangıç)',
    astrologyConnection: 'Akrep (Plüton dönüşümü) ve Balık (Sonsuzluk)',
    enneagramConnection: 'Tip 8 (Simya) & Tip 9 (Bütünlük)',
    visualKeywords: ['coiled snake around dagger', 'ouroboros biting tail', 'sacred serpent scales', 'kundalini spiral']
  },
  {
    id: 'sym-owl',
    name: 'Baykuş (Owl)',
    category: 'Hayvan',
    subcategory: 'Karanlıkta Gören Göz & Bilgelik',
    meaning: 'Karanlıkta gören göz, Athena’nın bilgeliği, aldatmacaları aşan berraklık ve gece sezgisi.',
    archetypes: ['Bilge', 'Kâşif', 'Gözlemci'],
    positiveThemes: ['aldatmacaları delme', 'gece berraklığı', 'derin felsefi akıl', 'sessiz gözlem'],
    shadowThemes: ['aşırı kuşkuculuk', 'yalnızlaşma'],
    relatedChakras: [6, 7],
    relatedElements: ['Hava'],
    relatedNumerology: [7],
    relatedAstrology: ['Başak', 'Oğlak'],
    relatedEnneagram: [5],
    relatedTotemThemes: ['gece kanatları', 'keskin yuvarlak gözler', 'sessiz uçuş'],
    suitableFor: ['Yalanları ve illüzyonları anında fark eden, sessiz bilgelik arayanlar'],
    avoidWhen: ['Gürültülü, patlayıcı ve fevri eylem temaları'],
    designCompatibility: {
      recommendedStyles: ['Micro Realism Eyes', 'Fine Line Dotwork', 'Geometric Feather'],
      bodyPlacements: ['Önkol', 'Göğüs Kafesi', 'Sırt Kürek Kemiği'],
      compositionRole: 'Merkezi gözlemci bakış odağı veya tepe bilgelik motifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Eşmerkezli iki daire göz, V-formunda gaga ve radyal tüy çizgileri'
    },
    visualDescription: 'Öne bakan hipnotik gözler, tüylü kaşlar, hilal ay üzerinde tünemiş sessiz baykuş profili.',
    numerologyConnection: 'Yaşam Yolu 7 ve Çakra 7 (Taç/Üçüncü Göz)',
    astrologyConnection: 'Başak ve Oğlak (Analitik ustalık)',
    enneagramConnection: 'Tip 5 (Araştırmacı Bilge)',
    visualKeywords: ['horned owl gaze', 'barn owl wings', 'crescent moon and owl', 'stippled feathers']
  },
  {
    id: 'sym-phoenix',
    name: 'Anka Kuşu (Phoenix)',
    category: 'Hayvan',
    subcategory: 'Küllerinden Yeniden Doğuş',
    meaning: 'Küllerinden yeniden doğuş, ölümsüz ruh, yangınlardan güçlenerek çıkma ve ilahi dönüşüm.',
    archetypes: ['Kahraman', 'Simyacı', 'Yenilmez'],
    positiveThemes: ['asla pes etmeme', 'yangından güçlenme', 'yükseliş', 'ölümsüz ruh'],
    shadowThemes: ['sürekli kendini yakıp yeniden başlama kısırdöngüsü'],
    relatedChakras: [3, 7],
    relatedElements: ['Ateş', 'Güneş'],
    relatedNumerology: [8, 19],
    relatedAstrology: ['Akrep', 'Aslan'],
    relatedEnneagram: [8, 3],
    relatedTotemThemes: ['alev kanatlar', 'uzun kuyruk tüyleri', 'küllerden sıçrayan kıvılcım'],
    suitableFor: ['Büyük bir yıkımın ardından hayatını sıfırdan ve eskisinden çok daha güçlü kuranlar'],
    avoidWhen: ['Yalnızca serin, durgun ve sakinleştirici su temaları'],
    designCompatibility: {
      recommendedStyles: ['Dynamic Linework', 'Fine Line Flow', 'Single-Needle Feather'],
      bodyPlacements: ['Sırt Boydan Boya', 'Kaburga Yanı', 'Önkol', 'Uyluk'],
      compositionRole: 'Yukarı doğru yükselen ana odak veya dinamik dikey alev ekseni',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Yukarı kıvrılan alev spiralleri, V-kanat açısı ve dikey kuyruk çizgileri'
    },
    visualDescription: 'Göğe doğru kanat çırpan alevli kanatlar, uzun dalgalı kuyruk tüyleri ve merkezde solar parlama.',
    numerologyConnection: 'Yaşam Yolu 8 ve 19 İlahi Yardım',
    astrologyConnection: 'Akrep (Yüksek oktavı) ve Aslan (Güneş ateşi)',
    enneagramConnection: 'Tip 8w7 & Tip 3w4',
    visualKeywords: ['rising phoenix wings', 'flaming celestial bird', 'ashes to fire rebirth', 'solar plumage']
  },
  {
    id: 'sym-stag',
    name: 'Ak Geyik / Geyik (Stag / White Hart)',
    category: 'Hayvan',
    subcategory: 'Ormanın Muhafızı & Ruhsal Taç',
    meaning: 'Ormanın koruyucu kralı, zarafet, boynuzların yenilenmesiyle gelen ruhsal taç ve asalet.',
    archetypes: ['Hükümdar', 'Orman Koruyucusu', 'Masum'],
    positiveThemes: ['zarafet', 'doğal asalet', 'ruhsal taçlanma', 'koruyucu varlık'],
    shadowThemes: ['aşırı ürkeklik', 'kaçma dürtüsü'],
    relatedChakras: [4, 7],
    relatedElements: ['Toprak', 'Hava'],
    relatedNumerology: [4, 6],
    relatedAstrology: ['Boğa', 'Yay'],
    relatedEnneagram: [1, 9],
    relatedTotemThemes: ['çatallı boynuz tacı', 'asil duruş', 'orman derinliği'],
    suitableFor: ['Kendi asaletini koruyarak başkalarına liderlik eden zarif ve güçlü ruhlar'],
    avoidWhen: ['Kaba, agresif ve yırtıcı kan dökücü temalar'],
    designCompatibility: {
      recommendedStyles: ['Botanical Horns', 'Fine Line Elegance', 'Geometric Stag'],
      bodyPlacements: ['Göğüs Merkezi', 'Önkol Dış', 'Sırt Kürek Kemiği', 'Uyluk'],
      compositionRole: 'Merkezi taç figürü veya dallanan boynuz armatürü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dallanan fraktal boynuz çizgileri, merkez üçgen alın ve negatif alan gözleri'
    },
    visualDescription: 'Görkemli çatallı boynuzlarında çiçekler veya geometrik yıldızlar açan asil geyik başı.',
    numerologyConnection: 'Yaşam Yolu 4 (Köklenme) ve 6 (Koruyuculuk)',
    astrologyConnection: 'Boğa ve Yay',
    enneagramConnection: 'Tip 1 & Tip 9',
    visualKeywords: ['majestic stag antlers', 'forest guardian stag', 'antlers with flowers', 'ethereal deer']
  },
  {
    id: 'sym-lion',
    name: 'Güneş Aslanı (Solar Lion)',
    category: 'Hayvan',
    subcategory: 'Yürekli Cesaret & Krallık',
    meaning: 'Yürekli cesaret, ilahi kraliyet, merkezde durma, yaratıcı özgüven ve kalbin asaleti.',
    archetypes: ['Hükümdar', 'Kahraman'],
    positiveThemes: ['özgüven', 'korkusuz liderlik', 'cömertlik', 'yaratıcı ateş'],
    shadowThemes: ['kibir', 'merkezde olma takıntısı'],
    relatedChakras: [3, 4],
    relatedElements: ['Ateş', 'Güneş'],
    relatedNumerology: [1, 3],
    relatedAstrology: ['Aslan'],
    relatedEnneagram: [3, 8],
    relatedTotemThemes: ['güneş yelesi', 'kükreyen çene', 'altın taç'],
    suitableFor: ['Kendi hayatının sahnesinde özgüvenle parlamak ve liderlik etmek isteyenler'],
    avoidWhen: ['Aşırı mütevazı ve görünmez olmayı amaçlayan inziva süreçleri'],
    designCompatibility: {
      recommendedStyles: ['Single Line Lion', 'Fine Line Baroque', 'Geometric Solar Mane'],
      bodyPlacements: ['Pazu', 'Göğüs', 'Önkol Dış', 'Sırt'],
      compositionRole: 'Güçlü merkez odak veya solar taç rozeti',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Güneş ışını radyal hatları, yele formunda 12 kadranlı güneş çarkı ve altın üçgen'
    },
    visualDescription: 'Güneş ışınları gibi açılan ayrıntılı yele, asil sakin bakış ve altın taç/geometrik halo.',
    numerologyConnection: 'Yaşam Yolu 1 ve 3 (Görkemli İfade)',
    astrologyConnection: 'Aslan (Güneş Yöneticisi)',
    enneagramConnection: 'Tip 3 & Tip 8',
    visualKeywords: ['roaring lion head', 'crowned solar lion', 'baroque lion ornate', 'fine line lion mane']
  },
  {
    id: 'sym-moth',
    name: 'Ölüm Başı Güvesi & Ay Güvesi (Death Head / Lunar Moth)',
    category: 'Hayvan',
    subcategory: 'Metamorfoz & Işığa Çekilme',
    meaning: 'Işığa çekilme, metamorfoz, kırılganlık içinde güç, gölge dönüşümü ve gece güzelliği.',
    archetypes: ['Arayışçı', 'Simyacı'],
    positiveThemes: ['ışığa yönelme', 'tam başkalaşım', 'özgün güzellik', 'gece zarafeti'],
    shadowThemes: ['kendini ateşe atma dürtüsü', 'kırılganlık'],
    relatedChakras: [6, 4],
    relatedElements: ['Hava', 'Ay / Su'],
    relatedNumerology: [7, 8],
    relatedAstrology: ['Akrep', 'İkizler'],
    relatedEnneagram: [4, 5],
    relatedTotemThemes: ['kafatasılı gövde', 'gece kanatları', 'ay fazları'],
    suitableFor: ['Kendi metamorfozunu yaşayan ve karanlığın içindeki ışığı arayan özgün ruhlar'],
    avoidWhen: ['Yalnızca parlak neşeli çocuksu renk arayışları'],
    designCompatibility: {
      recommendedStyles: ['Dotwork Sacred Geometry', 'Fine Line Gothic', 'Micro Realism'],
      bodyPlacements: ['Göğüs Kafesi Ortası (Sternum)', 'Önkol İç', 'Ense', 'Köprücük Altı'],
      compositionRole: 'Merkezi simetrik kanat motifi veya ay fazı taşıyıcısı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İki yana simetrik açılan üçgen kanat geometrisi ve ortada dikey elips gövde'
    },
    visualDescription: 'Sırtında minik kafatası motifi olan güve, kanatlarında geometrik ay fazları ve mikro dotwork detaylar.',
    numerologyConnection: 'Yaşam Yolu 7 & 8',
    astrologyConnection: 'Akrep ve İkizler',
    enneagramConnection: 'Tip 4 (Özgünlük) & Tip 5',
    visualKeywords: ['death head hawk moth', 'skull on thorax', 'lunar moth wings', 'sacred geometry moth']
  },
  {
    id: 'sym-eagle',
    name: 'Kartal (Golden Eagle)',
    category: 'Hayvan',
    subcategory: 'Yüksek Vizyon & Göksel Egemenlik',
    meaning: 'Fırtınaların üstünde uçma, ufuk ötesini gören keskin göz, ruhsal egemenlik ve ilahi vizyon.',
    archetypes: ['Hükümdar', 'Kâşif', 'Savaşçı'],
    positiveThemes: ['geniş vizyon', 'özgürlük', 'yüksekten bakabilme', 'korkusuz odak'],
    shadowThemes: ['kibir', 'aşağıdakileri küçümseme'],
    relatedChakras: [3, 6, 7],
    relatedElements: ['Hava', 'Güneş'],
    relatedNumerology: [1, 8],
    relatedAstrology: ['Akrep (Yüksek Kartal Hali)', 'Koç', 'Aslan'],
    relatedEnneagram: [8, 3],
    relatedTotemThemes: ['açılmış kanat genişliği', 'keskin gaga ve pençe', 'güneş bakışı'],
    suitableFor: ['Olaylara yukarıdan bakıp fırtınaları aşmak ve büyük hedeflere kilitlenmek isteyenler'],
    avoidWhen: ['Yalnızca yerde kalma ve küçük detaylara odaklanma süreçleri'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Wings', 'Etching Style', 'Geometric Falconry'],
      bodyPlacements: ['Sırt Boydan Boya', 'Göğüs', 'Önkol Dış'],
      compositionRole: 'Tasarımın tepe kanat çatısı veya merkezi avcı odağı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'V-şeklinde geniş açılan tüy okları ve merkezde keskin açı gaga vektörü'
    },
    visualDescription: 'Kanatlarını iki yana açmış gökyüzünde süzülen kartal, keskin bakışlar ve güneş ışınları.',
    numerologyConnection: 'Yaşam Yolu 1 ve 8 (Egemenlik)',
    astrologyConnection: 'Akrep (Kartal Yükselişi) ve Koç',
    enneagramConnection: 'Tip 8 & Tip 3',
    visualKeywords: ['soaring golden eagle linework', 'eagle wings spread tattoo', 'sharp vision eagle eye']
  },
  {
    id: 'sym-falcon',
    name: 'Şahin & Doğan (Falcon / Horus)',
    category: 'Hayvan',
    subcategory: 'Hız & Lazer Odaklanması',
    meaning: 'Hedefe kitlenme, anı yakalama hızı, zihinsel konsantrasyon ve göksel avcı zarafeti.',
    archetypes: ['Savaşçı', 'Stratejist'],
    positiveThemes: ['keskin odak', 'hızlı manevra', 'hedefi şaşırmama', 'çeviklik'],
    shadowThemes: ['sabırsızlık', 'aşırı sert inişler'],
    relatedChakras: [3, 6],
    relatedElements: ['Hava', 'Ateş'],
    relatedNumerology: [1, 5],
    relatedAstrology: ['Koç', 'İkizler'],
    relatedEnneagram: [3, 7],
    relatedTotemThemes: ['dalışa geçen kanatlar', 'ok hızı', 'avcı gözü'],
    suitableFor: ['Hedeflerine kilitlenip oyalanmadan hızlı ve net sonuç almak isteyenler'],
    avoidWhen: ['Yavaş, ağır ve tamamen meditasyonel dinginlik süreçleri'],
    designCompatibility: {
      recommendedStyles: ['Aerodynamic Linework', 'Fine Line Egyptian', 'Minimalist Vector'],
      bodyPlacements: ['Önkol İç', 'Kürek Kemiği', 'Baldır'],
      compositionRole: 'Dinamik yön oku veya dalış ekseni',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Ok ucu formunda geriye kıvrılan kanat üçgenleri ve aerodinamik hız çizgileri'
    },
    visualDescription: 'Aerodinamik dalış formunda şahin silueti, geometrik rüzgar hatları ve odaklanmış göz.',
    numerologyConnection: 'Yaşam Yolu 1 ve 5 (Hız ve Aksiyon)',
    astrologyConnection: 'Koç ve İkizler',
    enneagramConnection: 'Tip 3 & Tip 7',
    visualKeywords: ['diving falcon tattoo linework', 'peregrine falcon fine line', 'horus falcon speed tattoo']
  },
  {
    id: 'sym-panther',
    name: 'Kara Panter & Pars (Black Panther / Leopard)',
    category: 'Hayvan',
    subcategory: 'Sessiz Güç & Gölge Zarafeti',
    meaning: 'Görünmez adımlarla ilerleme, gölge zarafeti, sessiz kudret, gece cesareti ve içsel otorite.',
    archetypes: ['Gölge Savaşçısı', 'Avcı'],
    positiveThemes: ['sessiz güç', 'görünmeden etki etme', 'zarafet', 'korkusuz gece yürüyüşü'],
    shadowThemes: ['aşırı gizlilik', 'pusuda bekleme öfkesi'],
    relatedChakras: [1, 3],
    relatedElements: ['Toprak', 'Su'],
    relatedNumerology: [8, 7],
    relatedAstrology: ['Akrep', 'Oğlak'],
    relatedEnneagram: [8, 5],
    relatedTotemThemes: ['kadife adımlar', 'gece kamuflajı', 'esnek kaslar'],
    suitableFor: ['Bağırmadan, sessizce ama mutlak bir güçle hayatını yöneten asil ruhlar'],
    avoidWhen: ['Şovmen, gösterişli ve gürültülü dışa dönük eğlenceler'],
    designCompatibility: {
      recommendedStyles: ['Blackwork Contrast', 'Fine Line Silhouette', 'Minimalist Stalking'],
      bodyPlacements: ['Önkol Dış', 'Pazu', 'Uyluk Yanı', 'Kürek Kemiği'],
      compositionRole: 'Sessiz taban gücü veya kıvrımlı gölge akışı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'S-kıvrımlı omurga hattı, pençe çentikleri ve negatif alanda parlak göz yarığı'
    },
    visualDescription: 'Ay ışığı altında parlayan siyah parlak kürk, esnek kas anatomisi ve hipnotik zümrüt bakışlar.',
    numerologyConnection: 'Yaşam Yolu 8 ve 7 (Sessiz Derinlik)',
    astrologyConnection: 'Akrep ve Oğlak',
    enneagramConnection: 'Tip 8 & Tip 5',
    visualKeywords: ['stalking black panther tattoo', 'panther silhouette linework', 'shadow panther predator']
  },
  {
    id: 'sym-bear',
    name: 'Bozayı & Kutup Ayısı (Bear / Ursa Major)',
    category: 'Hayvan',
    subcategory: 'İçsel İnziva & Sarsılmaz Kudret',
    meaning: 'Kış uykusuyla gelen derin içsel yenilenme, yavrusunu koruyan anaç kudret, sarsılmaz güç ve şifa.',
    archetypes: ['Koruyucu Ana', 'Şifacı', 'Savaşçı'],
    positiveThemes: ['kendi mağarasına çekilme bilgeliği', 'sarsılmaz koruma', 'ham güç', 'topraklanma'],
    shadowThemes: ['aşırı hantallık', 'öfkeyle uyanma'],
    relatedChakras: [1, 4],
    relatedElements: ['Toprak'],
    relatedNumerology: [4, 8],
    relatedAstrology: ['Boğa', 'Başak', 'Yengeç'],
    relatedEnneagram: [8, 9],
    relatedTotemThemes: ['kış mağarası', 'büyük ayı takımyıldızı', 'ağır pençe izi'],
    suitableFor: ['Zaman zaman kendi içine çekilip güç toplayan ve sevdiklerine kale olanlar'],
    avoidWhen: ['Hafif, uçucu ve rüzgarlı narin tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Etching / Gravür', 'Constellation Bear', 'Blackwork Strength'],
      bodyPlacements: ['Pazu', 'Önkol', 'Sırt Kürek Kemiği', 'Göğüs'],
      compositionRole: 'Sağlam koruyucu zemin veya Büyük Ayı takımyıldızı çatısı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Ursa Major (Büyük Ayı) 7 yıldız hattı ve sağlam kare taban geometrisi'
    },
    visualDescription: 'Dağ yamacında duran güçlü ayı silueti, içinde Büyük Ayı takımyıldızı noktalamaları.',
    numerologyConnection: 'Yaşam Yolu 4 (Sağlam Temel) ve 8 (Kudret)',
    astrologyConnection: 'Boğa ve Yengeç',
    enneagramConnection: 'Tip 8 & Tip 9',
    visualKeywords: ['ursa major constellation bear', 'grizzly bear linework tattoo', 'protective bear spirit animal']
  },
  {
    id: 'sym-bull',
    name: 'Boğa (Bull / Taurus)',
    category: 'Hayvan',
    subcategory: 'Sarsılmaz Dayanıklılık & Bereket',
    meaning: 'Toprağın bereketi, engelleri yerinden söken sabırlı kuvvet, yılmaz azim ve sarsılmaz direnç.',
    archetypes: ['İnşa Eden', 'Savaşçı'],
    positiveThemes: ['yıkılmaz azim', 'bereketli emek', 'sadakat', 'fiziksel dayanıklılık'],
    shadowThemes: ['kör inatçılık', 'değişime direnç'],
    relatedChakras: [1],
    relatedElements: ['Toprak'],
    relatedNumerology: [4, 6],
    relatedAstrology: ['Boğa'],
    relatedEnneagram: [8, 1],
    relatedTotemThemes: ['hilal boynuzlar', 'sağlam toynaklar', 'bereketli toprak'],
    suitableFor: ['Tuttuğunu koparan, başladığı işi sabırla bitiren ve sarsılmaz azmi olanlar'],
    avoidWhen: ['Uçucu, değişken ve sürekli yön değiştiren temalar'],
    designCompatibility: {
      recommendedStyles: ['Single Line Bull', 'Geometric Taurus', 'Engraving'],
      bodyPlacements: ['Pazu', 'Önkol Dış', 'Göğüs', 'Baldır'],
      compositionRole: 'Merkezi kudret figürü veya boynuz hilal armatürü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Daire üzerine oturan hilal boynuz geometrisi (Boğa burcu glifi) ve geniş üçgen alın'
    },
    visualDescription: 'Öne eğilmiş hilal boynuzlu boğa başı, güçlü kas hatları ve geometrik daire çerçevesi.',
    numerologyConnection: 'Yaşam Yolu 4 ve 6',
    astrologyConnection: 'Boğa (Venüs ve Toprak Gücü)',
    enneagramConnection: 'Tip 8 & Tip 1',
    visualKeywords: ['taurus bull sacred geometry', 'charging bull fine line', 'crescent horns bull tattoo']
  },
  {
    id: 'sym-fox',
    name: 'Tilki (Fox / Kitsune)',
    category: 'Hayvan',
    subcategory: 'Kıvrak Zeka & Adaptasyon',
    meaning: 'Her türlü krizden kıvrak zekayla sıyrılma, kılık değiştirme/uyum ustalığı ve sezgisel çeviklik.',
    archetypes: ['Düzenbaz / Trickster', 'Stratejist', 'Kâşif'],
    positiveThemes: ['kriz çözme ustalığı', 'yüksek adaptasyon', 'oyuncu zeka', 'çeviklik'],
    shadowThemes: ['güvensizlik yaratma', 'bağlanmaktan kaçma'],
    relatedChakras: [3, 6],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [5, 3],
    relatedAstrology: ['İkizler', 'Yay'],
    relatedEnneagram: [7, 6],
    relatedTotemThemes: ['kabarık kuyruk', 'sivri kulaklar', 'kızıl alev kıvraklığı'],
    suitableFor: ['Katı kurallarla değil, zekasıyla ve esnekliğiyle hayatta kazanan akıllı ruhlar'],
    avoidWhen: ['Ağır, hantal ve aşırı kuralcı yapılar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Origami / Geometric', 'Asian Kitsune', 'Micro Realism'],
      bodyPlacements: ['Önkol', 'Köprücük Altı', 'Bilek', 'Baldır'],
      compositionRole: 'Kıvrımlı kuyruk akışı veya zeki profil odağı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Sivri üçgen kulaklar, kavisli spiral kuyruk ve geometrik origami hatları'
    },
    visualDescription: 'Kıvrılmış kabarık kuyruğuyla dinlenen uyanık tilki, sivri kulaklar ve ince kılcal çizgiler.',
    numerologyConnection: 'Yaşam Yolu 5 (Özgürlük ve Uyum) ve 3',
    astrologyConnection: 'İkizler ve Yay',
    enneagramConnection: 'Tip 7 & Tip 6',
    visualKeywords: ['origami geometric fox', 'kitsune fox tail tattoo', 'clever fox linework fine line']
  },
  {
    id: 'sym-dragonfly',
    name: 'Yusufçuk (Dragonfly)',
    category: 'Hayvan',
    subcategory: 'İllüzyonların Aşılması & Işık Kırılması',
    meaning: 'Su yüzeyinde doğup havaya uçma; yanılsamaları aşma, duygusal derinlikten zihinsel hafifliğe geçiş ve ışık.',
    archetypes: ['Mistik', 'Haberci'],
    positiveThemes: ['illüzyonları delme', 'hafiflik', 'duygusal olgunluk', 'ışık kırılması'],
    shadowThemes: ['kırılganlık', 'kısa ömür kaygısı'],
    relatedChakras: [4, 6],
    relatedElements: ['Su', 'Hava'],
    relatedNumerology: [5, 7],
    relatedAstrology: ['Yengeç', 'Balık', 'Kova'],
    relatedEnneagram: [4, 7],
    relatedTotemThemes: ['şeffaf tül kanatlar', 'uzun ince gövde', 'su damlası'],
    suitableFor: ['Ağır duygusal yüklerini hafifliğe ve berrak bir kavrayışa dönüştürenler'],
    avoidWhen: ['Kaba, ağır ve karanlık savaşçı konseptler'],
    designCompatibility: {
      recommendedStyles: ['Micro Realism Wings', 'Fine Line Dotwork', 'Geometric Wings'],
      bodyPlacements: ['Ense', 'Bilek', 'Köprücük Kemiği', 'Önkol İç'],
      compositionRole: 'Hafif tepe vurgusu veya su damlası üstü motifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dikey ince doğru gövde ve iki yanda 4 adet ince elips kanat kafesi'
    },
    visualDescription: 'Tül gibi damarlı dört şeffaf kanat, mikro dotwork gövde ve kanatlarında prizmatik ışık hissi.',
    numerologyConnection: 'Yaşam Yolu 5 ve 7',
    astrologyConnection: 'Balık ve Kova',
    enneagramConnection: 'Tip 4 & Tip 7',
    visualKeywords: ['dragonfly fine line tattoo', 'transparent wings dragonfly', 'sacred geometry dragonfly linework']
  },
  {
    id: 'sym-whale',
    name: 'Balina (Whale / Leviathan)',
    category: 'Hayvan',
    subcategory: 'Bilinçaltı Okyanusu & Kozmik Şarkı',
    meaning: 'Okyanusun ve bilinçaltının derinlikleri, kadim dünya hafızası, yankısal iletişim ve derin şefkat.',
    archetypes: ['Kozmik Anne', 'Mistik Dev'],
    positiveThemes: ['derin bilinçaltı barışı', 'kadim hafıza', 'şefkat', 'engelsiz genişlik'],
    shadowThemes: ['derin sulara gömülme', 'hüzün'],
    relatedChakras: [4, 5],
    relatedElements: ['Su'],
    relatedNumerology: [9, 2],
    relatedAstrology: ['Balık', 'Yengeç'],
    relatedEnneagram: [9, 4],
    relatedTotemThemes: ['kuyruk yüzgeci', 'okyanus şarkısı', 'yıldızlı sırt'],
    suitableFor: ['Ruhunun derinliklerinde sonsuz bir okyanus taşıyan, şefkatli ve bilge insanlar'],
    avoidWhen: ['Ateşli, agresif ve aceleci kuru projeler'],
    designCompatibility: {
      recommendedStyles: ['Celestial Whale Fine Line', 'Dotwork Ocean', 'Minimalist Fin'],
      bodyPlacements: ['Kaburga', 'Önkol Boydan Boya', 'Sırt Kürek Kemiği'],
      compositionRole: 'Alt kaide okyanus derinliği veya göksel süzülüş ekseni',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Akışkan kambur eğrisi, çift çatallı kuyruk yüzgeci ve paralel karın çizgileri'
    },
    visualDescription: 'Yıldızlı gökyüzü gibi benekli gövdesiyle okyanusta süzülen kambur balina, kuyruk dalgası.',
    numerologyConnection: 'Yaşam Yolu 9 ve 2 (Okyanusal Birlik)',
    astrologyConnection: 'Balık ve Yengeç',
    enneagramConnection: 'Tip 9 & Tip 4',
    visualKeywords: ['celestial humpback whale tattoo', 'whale swimming in stars linework', 'ocean whale fine line']
  },
  {
    id: 'sym-swan',
    name: 'Kuğu (Swan)',
    category: 'Hayvan',
    subcategory: 'Zarafet & Saf Sadakat',
    meaning: 'Çirkin ördek yavrusunun kuğuya dönüşmesi; ruhsal zarafet, saf sadakat, su üstünde sükunet ve asalet.',
    archetypes: ['Aşık', 'Masum', 'Dönüşen'],
    positiveThemes: ['kusursuz zarafet', 'ömür boyu sadakat', 'içsel dönüşüm', 'su sükuneti'],
    shadowThemes: ['kırılgan kibir', 'dış görünüş kaygısı'],
    relatedChakras: [4, 7],
    relatedElements: ['Su', 'Hava'],
    relatedNumerology: [6, 2],
    relatedAstrology: ['Terazi', 'Balık'],
    relatedEnneagram: [4, 2],
    relatedTotemThemes: ['kavisli boyun', 'beyaz tüyler', 'su yansıması'],
    suitableFor: ['Zarafeti ve sadakati en yüksek yaşam standardı olarak benimseyenler'],
    avoidWhen: ['Kaba, saldırgan ve çamurlu endüstriyel temalar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Elegance', 'Single-Line Swan', 'Minimalist Curve'],
      bodyPlacements: ['Köprücük Kemiği', 'Bilek', 'Önkol İç', 'Ense'],
      compositionRole: 'Zarif S-eğrisi akışı veya iki kuğunun kalp oluşturduğu ikili simetri',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Pürüzsüz S-boyun kavis çizgisi ve su üzerindeki eliptik gövde yansıması'
    },
    visualDescription: 'Kavisli boynuyla su üzerinde süzülen kuğu, arkasında narin su halkaları ve tüy hatları.',
    numerologyConnection: 'Yaşam Yolu 6 ve 2',
    astrologyConnection: 'Terazi ve Balık (Venüs ve Neptün Zarafeti)',
    enneagramConnection: 'Tip 4 & Tip 2',
    visualKeywords: ['graceful swan linework tattoo', 'swan reflection water ripples', 'fine line swan elegance']
  },
  {
    id: 'sym-wild-horse',
    name: 'Yaban Atı & Pegasos (Wild Horse / Pegasus)',
    category: 'Hayvan',
    subcategory: 'Dizginsiz Özgürlük & Rüzgar Ruhu',
    meaning: 'Dizgin vurulamayan ruh, rüzgar hızı, yaşam coşkusu, yorulmaz adımlar ve kanatlı yükseliş.',
    archetypes: ['Özgür Ruh', 'Gezgin', 'Kahraman'],
    positiveThemes: ['dizginsiz özgürlük', 'yaşam coşkusu', 'hızlı atılım', 'asalet'],
    shadowThemes: ['bağlanma korkusu', 'aşırı sabırsızlık'],
    relatedChakras: [3, 4],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [5, 1],
    relatedAstrology: ['Yay', 'Koç'],
    relatedEnneagram: [7, 8],
    relatedTotemThemes: ['rüzgarda dalgalanan yele', 'dörtnala toynaklar', 'şahlanış'],
    suitableFor: ['Hiçbir kafese sığmayan, hayatını kendi rüzgarıyla dörtnala koşanlar'],
    avoidWhen: ['Durağan, kapalı ve sınırlandırılmış yapılar'],
    designCompatibility: {
      recommendedStyles: ['Dynamic Brush Linework', 'Fine Line Pegasus', 'Geometric Horse'],
      bodyPlacements: ['Uyluk', 'Kaburga Yanı', 'Önkol Dış', 'Sırt'],
      compositionRole: 'Dinamik hareket taşıyıcısı veya şahlanan merkez figürü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Şahlanan boyun S-eğrisi, yele dalgaları ve diyagonal hareket ekseni'
    },
    visualDescription: 'Şahlanan asil at başı, rüzgarda savrulan dalgalı yeleler ve açılmış kanat tüyleri.',
    numerologyConnection: 'Yaşam Yolu 5 (Özgürlük) ve 1',
    astrologyConnection: 'Yay (Sentor) ve Koç',
    enneagramConnection: 'Tip 7 & Tip 8',
    visualKeywords: ['wild horse galloping linework', 'pegasus winged horse tattoo', 'free spirit horse fine line']
  },
  {
    id: 'sym-scorpion',
    name: 'Akrep (Scorpion)',
    category: 'Hayvan',
    subcategory: 'Derin Dönüşüm & Zehri İlaca Çevirme',
    meaning: 'Zehri panzehire dönüştüren simyacı; ölüm ve yeniden doğum, yalanları anında sezen keskin radar ve sarsılmaz kişisel sınırlar.',
    archetypes: ['Simyacı', 'Gölge Muhafızı'],
    positiveThemes: ['derin dönüşüm', 'keskin sezgi', 'aşırı sadakat', 'dokunulmaz sınırlar'],
    shadowThemes: ['intikam takıntısı', 'aşırı şüphecilik'],
    relatedChakras: [1, 2],
    relatedElements: ['Su', 'Ateş'],
    relatedNumerology: [8, 9, 13],
    relatedAstrology: ['Akrep'],
    relatedEnneagram: [8, 4, 6],
    relatedTotemThemes: ['kavisli kuyruk iğnesi', 'sağlam zırh plakaları', 'kıskaç dengesi'],
    suitableFor: ['Kendi gölgesini dönüştürüp küllerinden doğan, yalanlara tahammülü olmayan derin karakterler'],
    avoidWhen: ['Hafif, neşeli ve tasasız eğlence temaları'],
    designCompatibility: {
      recommendedStyles: ['Geometric Blackwork', 'Fine Line Etching', 'Micro Realism'],
      bodyPlacements: ['Bilek', 'Köprücük Kemiği', 'Ayak Bileği / Baldır', 'Kaburga'],
      compositionRole: 'Merkezi simyasal dönüşüm figürü veya alt koruma mührü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Sarmal kavisli bir iğne yayı, iki simetrik kıskaç üçgeni ve 8 segmentli zırh çizgileri'
    },
    visualDescription: 'Kıvrık tehditkar kuyruğu ve geometrik zırhlı segmentleriyle asil duruşlu akrep silueti.',
    numerologyConnection: 'Yaşam Yolu 8 ve 9',
    astrologyConnection: 'Akrep (Plüton & Mars)',
    enneagramConnection: 'Tip 8 & Tip 4',
    visualKeywords: ['scorpion tattoo linework', 'geometric scorpion fine line', 'alchemical scorpion symbol']
  },
  {
    id: 'sym-chameleon',
    name: 'Bukalemun (Chameleon)',
    category: 'Hayvan',
    subcategory: 'Kusursuz Uyum & Görünmezlik Sanatı',
    meaning: 'Bulunduğu ortama kusursuz uyum sağlama, sabırlı gözlem, 360 derece bağımsız görüş ve kriz anında görünmez olma ustalığı.',
    archetypes: ['Bukalemun / Uyum Ustası', 'Gözcü'],
    positiveThemes: ['yüksek uyum yeteneği', 'sabırlı bekleme', 'esneklik', 'bağımsız vizyon'],
    shadowThemes: ['kendi kimliğini kaybetme'],
    relatedChakras: [5, 6],
    relatedElements: ['Toprak', 'Su'],
    relatedNumerology: [5, 2],
    relatedAstrology: ['İkizler', 'Balık'],
    relatedEnneagram: [9, 3],
    relatedTotemThemes: ['kıvrık spiral kuyruk', 'bağımsız dönen gözler', 'kamuflaj dokusu'],
    suitableFor: ['Her türlü sosyal ve iş ortamına hızla uyum sağlayan, çatışmasız zeka ustaları'],
    avoidWhen: ['Tavizsiz ve sert cepheleşme isteyen durumlar'],
    designCompatibility: {
      recommendedStyles: ['Geometric Linework', 'Fine Line Botanical', 'Micro Realism'],
      bodyPlacements: ['Önkol', 'Köprücük Kemiği', 'Ayak Bileği'],
      compositionRole: 'Dala tutunan kavisli tamamlayıcı figür',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Sarmal spiral kuyruk, kavisli sırt sırtı ve iki bağımsız göz dairesi'
    },
    visualDescription: 'Kıvrılmış spiral kuyruğuyla ince bir dala tutunmuş, gözleri bağımsız odaklanan zarif bukalemun.',
    numerologyConnection: 'Yaşam Yolu 5 ve 2',
    astrologyConnection: 'İkizler ve Balık',
    enneagramConnection: 'Tip 9 & Tip 3',
    visualKeywords: ['chameleon tattoo linework', 'geometric chameleon design', 'camouflage reptile fine line']
  },
  {
    id: 'sym-hawk',
    name: 'Şahin & Doğan (Hawk & Falcon)',
    category: 'Hayvan',
    subcategory: 'Yüksek Vizyon & Şaşmaz Odak',
    meaning: 'Bulutların üstünden yeryüzünü tarayan yüksek perspektif; aldatmacaları görmezden gelip hedefe dik açıyla kilitlenen keskin zihin.',
    archetypes: ['Avcı', 'Vizyoner Gözcü'],
    positiveThemes: ['kuşbakışı vizyon', 'şaşmaz odaklanma', 'zihinsel hız', 'illüzyondan arınma'],
    shadowThemes: ['aşırı sabırsız acımasızlık'],
    relatedChakras: [6, 3],
    relatedElements: ['Hava', 'Güneş'],
    relatedNumerology: [1, 7],
    relatedAstrology: ['Koç', 'Aslan', 'Kova'],
    relatedEnneagram: [3, 8],
    relatedTotemThemes: ['jilet gibi keskin gözler', 'aerodinamik dalış kanatları', 'kavisli gaga'],
    suitableFor: ['Büyük resmi gören, hedeflerine sapmadan ve oyalanmadan kilitlenen stratejistler'],
    avoidWhen: ['Durgun, melankolik ve kararsız duygusal süreçler'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Dotwork', 'Geometric Falcon', 'Single Needle'],
      bodyPlacements: ['Önkol', 'Kürek Kemiği', 'Kaburga'],
      compositionRole: 'Yukarıdan bakan gözetleme odağı veya dalış hareketi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Açılı V-kanat kanat formu ve merkez delici tek odak noktası'
    },
    visualDescription: 'Karakteristik kavisli sivri gagası, delici gözü ve aerodinamik tüyleriyle şahin profili.',
    numerologyConnection: 'Yaşam Yolu 1 ve 7',
    astrologyConnection: 'Koç ve Aslan',
    enneagramConnection: 'Tip 3 & Tip 8',
    visualKeywords: ['hawk profile tattoo linework', 'falcon eye vision tattoo', 'geometric hawk sharp needle']
  },
  {
    id: 'sym-jaguar',
    name: 'Şamanik Jaguar (Sacred Jaguar)',
    category: 'Hayvan',
    subcategory: 'Yeraltı Gücü & Güneş Avcısı',
    meaning: 'Mezoamerikan şamanizminin en güçlü ruh hayvanı; karanlık ormanları ve yeraltı dünyasını yöneten, korkusuz ruhsal koruyucu.',
    archetypes: ['Şaman Savaşçı', 'Orman Efendisi'],
    positiveThemes: ['korkusuzluk', 'ruhsal liderlik', 'derin koruma', 'karanlıkta hakimiyet'],
    shadowThemes: ['aşırı dominantlık'],
    relatedChakras: [1, 3],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [8, 1],
    relatedAstrology: ['Akrep', 'Aslan'],
    relatedEnneagram: [8],
    relatedTotemThemes: ['rozet benekli kürk', 'keskin çene yapısı', 'yeraltı güneşi'],
    suitableFor: ['Ruhsal sınırlarını aşılmaz kılmak ve karanlık korkularını güce çevirmek isteyenler'],
    avoidWhen: ['Zayıf, kararsız ve pasif teslimiyet süreçleri'],
    designCompatibility: {
      recommendedStyles: ['Maya / Aztek Dotwork', 'Etching Blackwork', 'Fine Line Shamanic'],
      bodyPlacements: ['Uyluk Yanı', 'Sırt / Omuz', 'Önkol'],
      compositionRole: 'Merkezi otorite figürü veya koruyucu totem',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Geometrik benek rozetleri ve keskin çene çizgisi konturu'
    },
    visualDescription: 'Gözlerinden zeka ve kadim güç fışkıran, karakteristik rozet desenleriyle süslü jaguar başı.',
    numerologyConnection: 'Yaşam Yolu 8 ve 1',
    astrologyConnection: 'Akrep ve Aslan',
    enneagramConnection: 'Tip 8 (Reis)',
    visualKeywords: ['shamanic jaguar tattoo', 'maya jaguar linework', 'sacred predator tattoo design']
  },
  {
    id: 'sym-lynx',
    name: 'Kuzey Vaşağı (Lynx / Keeper of Secrets)',
    category: 'Hayvan',
    subcategory: 'Sırların Bekçisi & Sessiz Gözlem',
    meaning: 'Kuzey ormanlarının gizli vaşağı; kimsenin görmediği detayları fark eden, sırları saklayan ve yalnızlığın kutsallığına inanan bilge gözcü.',
    archetypes: ['Sır Muhafızı', 'Münzevi Gözcü'],
    positiveThemes: ['görünmeyeni görme', 'ketum güvenilirlik', 'sessiz adımlar', 'derin içgörü'],
    shadowThemes: ['aşırı izolasyon'],
    relatedChakras: [6, 7],
    relatedElements: ['Toprak', 'Hava'],
    relatedNumerology: [7, 5],
    relatedAstrology: ['Yay', 'Kova', 'Başak'],
    relatedEnneagram: [5, 4],
    relatedTotemThemes: ['püsküllü kulak uçları', 'geniş kar patileri', 'kehribar bakış'],
    suitableFor: ['Sır saklayabilen, gürültüden uzak derin bir gözlem gücüne sahip kişiler'],
    avoidWhen: ['Gürültülü, şamatacı ve renkli kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Nordic Fine Line', 'Engraving / Etching', 'Geometric Dotwork'],
      bodyPlacements: ['Önkol', 'Kürek Kemiği', 'Baldır'],
      compositionRole: 'Merkezi gözlemci veya üst köşe bekçisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Püsküllü sivri üçgen kulaklar ve iki delici badem göz ekseni'
    },
    visualDescription: 'Karakteristik püsküllü dik kulakları, sakallı yanakları ve delici bakışlarıyla asil vaşak portresi.',
    numerologyConnection: 'Yaşam Yolu 7 ve 5',
    astrologyConnection: 'Yay ve Kova',
    enneagramConnection: 'Tip 5 & Tip 4',
    visualKeywords: ['lynx tattoo linework', 'keeper of secrets lynx design', 'nordic lynx fine line tattoo']
  },
  {
    id: 'sym-peacock',
    name: 'Tavus Kuşu & Bin Gözlü Tılsım (Sacred Peacock)',
    category: 'Hayvan',
    subcategory: 'Bütüncül Güzellik & Bin Gözlü Koruma',
    meaning: 'Zehirli yılanları yiyip zehri parlak tüylere dönüştüren kutsal kuş; kibirsiz asalet, üçüncü göz bolluğu ve ruhun dirilişi.',
    archetypes: ['Büyücü', 'Aşık', 'Şifacı'],
    positiveThemes: ['zehri güzelliğe dönüştürme', 'ruhsal göz açıklığı', 'hak edilmiş asalet', 'diriliş'],
    shadowThemes: ['kibir ve narsisizm tuzağı'],
    relatedChakras: [4, 6, 2],
    relatedElements: ['Hava', 'Su', 'Güneş'],
    relatedNumerology: [3, 6],
    relatedAstrology: ['Aslan', 'Terazi', 'Boğa'],
    relatedEnneagram: [4, 3],
    relatedTotemThemes: ['göz motifli yelpaze kuyruk', 'taç sorguç', 'zarif boyun kavisleri'],
    suitableFor: ['Kendi acılarını ve travmalarını sanat ve zarafete dönüştürerek ışıldayanlar'],
    avoidWhen: ['Aşırı sade, kaba veya endüstriyel soğuk kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Art Nouveau Fine Line', 'Single Needle Dotwork', 'Neo-Traditional'],
      bodyPlacements: ['Sırt Boyunca', 'Uyluk Yanı', 'Önkol İç'],
      compositionRole: 'Görkemli yelpaze arka plan veya akıcı boyun odak çizgisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Radyal yelpaze hatları ve her hattın ucundaki damla-göz halkaları'
    },
    visualDescription: 'Açılmış yelpaze kuyruğundaki her tüyü koruyucu bir göz motifiyle bezenmiş asil tavus kuşu.',
    numerologyConnection: 'Yaşam Yolu 3 ve 6',
    astrologyConnection: 'Terazi ve Aslan',
    enneagramConnection: 'Tip 4 & Tip 3',
    visualKeywords: ['peacock feather tattoo linework', 'art nouveau peacock design', 'sacred peacock thousand eyes']
  }
];
