import { SymbolLibraryItem } from '../../types';

export const COSMIC_SYMBOLS: SymbolLibraryItem[] = [
  {
    id: 'sym-lunar-phases',
    name: 'Ayın Evreleri (Lunar Phases / Cycle)',
    category: 'Kozmik',
    subcategory: 'Döngüsel Zaman & Dişil Ritim',
    meaning: 'Hilalden dolunaya ve karanlık aya uzanan kozmik döngü; büyüme, olgunlaşma, bırakma ve yenilenme ritmi.',
    archetypes: ['Mistik', 'Zaman Muhafızı', 'Dönüştürücü'],
    positiveThemes: ['döngüsel kabulleniş', 'sürekli yenilenme', 'zamanlama bilgeliği', 'içsel ritim'],
    shadowThemes: ['duygusal gelgitlerde savrulma'],
    relatedChakras: [2, 6],
    relatedElements: ['Su', 'Eter'],
    relatedNumerology: [2, 9],
    relatedAstrology: ['Yengeç', 'Balık', 'Akrep'],
    relatedEnneagram: [4, 9],
    relatedTotemThemes: ['hilal kavisleri', 'parlak dolunay', 'karanlık ay aynası'],
    suitableFor: ['Hayatın evrelerden ibaret olduğunu kavrayan ve döngüleriyle barışan ruhlar'],
    avoidWhen: ['Tamamen doğrusal ve statik yapay mekanik hedefler'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Dotwork', 'Geometric Alignment', 'Minimalist Moons'],
      bodyPlacements: ['Omurga Boyunca', 'Önkol Boydan Boya', 'Köprücük Kemiği', 'Kaburga'],
      compositionRole: 'Dikey veya yatay kılavuz hizalama aksı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Sıralı 5 veya 7 daire ve içlerindeki gölge yayları'
    },
    visualDescription: 'Hilal, ilk dördün, dolunay, son dördün ve hilal şeklinde sıralanmış ince dotwork kraterli aylar.',
    numerologyConnection: 'Yaşam Yolu 2 (Ay) ve 9 (Döngü Tamamlanması)',
    astrologyConnection: 'Yengeç (Ay Yöneticisi) ve Su Burçları',
    enneagramConnection: 'Tip 4 & Tip 9',
    visualKeywords: ['lunar phases spine tattoo', 'moon phases dotwork linework', 'crescent to full moon celestial']
  },
  {
    id: 'sym-solar-eclipse',
    name: 'Güneş Tutulması & Korona (Solar Eclipse & Corona)',
    category: 'Kozmik',
    subcategory: 'Karanlıktaki Işık Tacı & Kutsal Kavuşum',
    meaning: 'Güneş ve Ay’ın tam kavuşumu; en derin karanlığın ortasında parlayan ilahi ışık tacı (korona) ve ani uyanış.',
    archetypes: ['Simyacı', 'Gölgeyi Aydınlatan'],
    positiveThemes: ['karanlıkta parlayan ışık', 'büyük sıfırlanma', 'kutsal evlilik (Hieros Gamos)', 'derin dönüşüm'],
    shadowThemes: ['ani sarsıntılar', 'kontrol kaybı'],
    relatedChakras: [3, 7],
    relatedElements: ['Ateş', 'Su', 'Eter'],
    relatedNumerology: [1, 8, 0],
    relatedAstrology: ['Aslan', 'Yengeç'],
    relatedEnneagram: [8, 4],
    relatedTotemThemes: ['kara güneş diski', 'parıldayan korona ışınları', 'elmas yüzük etkisi'],
    suitableFor: ['Hayatında radikal bir dönüm noktası yaşayan ve karanlığından ışık doğuranlar'],
    avoidWhen: ['Tek düze, sakin ve sıradan rutin temalar'],
    designCompatibility: {
      recommendedStyles: ['Blackwork Halo', 'Fine Line Ray', 'Micro Realism Corona'],
      bodyPlacements: ['Sırt Üstü', 'Göğüs Kafesi', 'Önkol İç'],
      compositionRole: 'Merkezi dramatik odak ve radyal ışık kaynağı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dolu siyah merkez daire ve etrafından fışkıran asimetrik radyal ışın hatları'
    },
    visualDescription: 'Kara diski çevreleyen altın parıltılı korona alevleri ve tek noktadan parlayan elmas yüzük ışıltısı.',
    numerologyConnection: 'Yaşam Yolu 1 (Güneş) ve 8 (Dönüşüm)',
    astrologyConnection: 'Aslan ve Yengeç (Solar ve Lunar Birlik)',
    enneagramConnection: 'Tip 8 & Tip 4',
    visualKeywords: ['solar eclipse corona tattoo', 'totality eclipse black sun', 'diamond ring effect celestial tattoo']
  },
  {
    id: 'sym-polaris',
    name: 'Kutup Yıldızı (Polaris / North Star)',
    category: 'Kozmik',
    subcategory: 'Sabit Nirengi & Değişmez Kılavuz',
    meaning: 'Bütün gökkubbe dönerken yeri asla değişmeyen sabit yıldız; hakiki kuzey, sarsılmaz inanç ve mutlak sadakat.',
    archetypes: ['Kılavuz', 'Kutup Muhafızı'],
    positiveThemes: ['şaşmaz yön', 'sarsılmaz sadakat', 'umut ışığı', 'değişmez değerler'],
    shadowThemes: ['aşırı sabit fikirlilik'],
    relatedChakras: [6, 7],
    relatedElements: ['Eter', 'Hava'],
    relatedNumerology: [1, 7],
    relatedAstrology: ['Oğlak', 'Kova'],
    relatedEnneagram: [1, 6],
    relatedTotemThemes: ['8 kollu parlak yıldız', 'göksel eksen merkezi', 'denizci umudu'],
    suitableFor: ['Değişen dünyada kendi sabit ilkelerine ve hedeflerine sadık kalanlar'],
    avoidWhen: ['Sürekli değişkenlik ve kaypak akışlar'],
    designCompatibility: {
      recommendedStyles: ['Minimalist Starlight', 'Fine Line Nautical', 'Dotwork Sparkle'],
      bodyPlacements: ['Bilek', 'Ense', 'Köprücük Kemiği', 'Parmak'],
      compositionRole: 'Tepe kılavuz yıldızı veya pusula merkezi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dikey ve yatay uzun ışınlı 4 ana kol ve aralarda 4 kısa kol ile 8 köşeli yıldız'
    },
    visualDescription: 'Uzun dikey ve yatay elmas ışınları olan parlak 8 köşeli kuzey yıldızı ve mikro dotwork ışıltılar.',
    numerologyConnection: 'Yaşam Yolu 1 (Kutup) ve 7 (İlahi Işık)',
    astrologyConnection: 'Oğlak ve Kova (Göksel Tepe)',
    enneagramConnection: 'Tip 1 & Tip 6',
    visualKeywords: ['polaris north star tattoo', 'eight pointed celestial star fine line', 'guiding north star linework']
  },
  {
    id: 'sym-zodiac-wheel',
    name: 'Zodyak Çemberi (Celestial Zodiac Wheel)',
    category: 'Kozmik',
    subcategory: 'Göksel Zaman & 12 Arketip',
    meaning: '12 burcun göksel ekliptik yolu; insan psikolojisinin 12 temel arketipi, evrensel harmoni ve kozmik saat.',
    archetypes: ['Kozmik Gözlemci', 'Zaman Mimarı'],
    positiveThemes: ['tüm arketiplerin dengesi', 'evrensel senkronizasyon', 'kozmik saat', 'bütünlük'],
    shadowThemes: ['kadercilik', 'iradeyi yıldızlara bırakma'],
    relatedChakras: [1, 2, 3, 4, 5, 6, 7],
    relatedElements: ['Ateş', 'Toprak', 'Hava', 'Su'],
    relatedNumerology: [12, 3],
    relatedAstrology: ['Tüm 12 Burç'],
    relatedEnneagram: [9],
    relatedTotemThemes: ['12 kadran', 'takımyıldız işaretleri', 'ekliptik daire'],
    suitableFor: ['Astrolojik bilince sahip ve evrendeki 12 frekansı kendi içinde dengelemek isteyenler'],
    avoidWhen: ['Yalnızca tek bir burca veya minimal basit şekillere odaklananlar'],
    designCompatibility: {
      recommendedStyles: ['Astronomical Engraving', 'Fine Line Wheel', 'Geometric Astrolabe'],
      bodyPlacements: ['Sırt', 'Önkol İç', 'Kürek Kemiği'],
      compositionRole: 'Merkezi kozmik armatür veya çevreleyen takımyıldız çemberi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: '12 eşit sektöre bölünmüş eşmerkezli çemberler ve merkez güneş noktası'
    },
    visualDescription: '12 eşit dilime bölünmüş antik gök haritası diski, burç glifleri ve derecelendirme çizgileri.',
    numerologyConnection: '12 Sayısı (Tamamlanmış Döngü) ve Yaşam Yolu 3',
    astrologyConnection: 'Zodyak Ekliptiği',
    enneagramConnection: 'Tip 9 (Tüm Tiplerin Kapsayıcısı)',
    visualKeywords: ['zodiac wheel linework tattoo', 'astrological chart celestial wheel', 'constellations circle fine line']
  },
  {
    id: 'sym-sirius',
    name: 'Sirius & Akyıldız (Sirius / Dog Star)',
    category: 'Kozmik',
    subcategory: 'Mavi Işık & Yüksek İnisiyasyon',
    meaning: 'Gökyüzünün en parlak yıldızı; yüksek ruhsal frekans, eski Mısır’da Nil taşkınlarının müjdecisi ve uyanış.',
    archetypes: ['Mistik Uyanışçı', 'Ruhsal Rehber'],
    positiveThemes: ['yüksek bilinç parıltısı', 'ilahi haber', 'manevi liderlik', 'keskin berraklık'],
    shadowThemes: ['aşırı yoğun ışıkta yanma korkusu'],
    relatedChakras: [6, 7],
    relatedElements: ['Ateş', 'Eter'],
    relatedNumerology: [11, 1],
    relatedAstrology: ['Yengeç', 'Aslan'],
    relatedEnneagram: [5, 7],
    relatedTotemThemes: ['mavi ışıltı', 'beş köşeli yanan yıldız', 'nil taşkını habercisi'],
    suitableFor: ['Yüksek sezgisel frekans taşıyan ve ruhani uyanış sürecine giren arayışçılar'],
    avoidWhen: ['Karanlık, kasvetli ve topraksı ağır projeler'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Sparkle', 'Dotwork Radiant', 'Sacred Star'],
      bodyPlacements: ['Önkol', 'Köprücük Kemiği', 'Alın / Üçüncü Göz Ekseni'],
      compositionRole: 'Tepe ışık kaynağı veya odak yıldızı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkezden dışa uzanan 5 veya 6 uzun elmas ışın ve mikro hale çemberi'
    },
    visualDescription: 'Büyüleyici parıltısıyla öne çıkan kristalize yıldız motifi, narin mikro-dotwork ışık halesi.',
    numerologyConnection: 'Üstat 11 ve Yaşam Yolu 1',
    astrologyConnection: 'Yengeç (Sirius 14° Yengeç)',
    enneagramConnection: 'Tip 5 & Tip 7',
    visualKeywords: ['sirius dog star tattoo', 'brightest star linework', 'egyptian sacred star sirius tattoo']
  },
  {
    id: 'sym-comet',
    name: 'Kuyruklu Yıldız & Astral Işık (Comet / Astral Fire)',
    category: 'Kozmik',
    subcategory: 'Nadir Dönüşüm & Göksel İşaret',
    meaning: 'Yıllarda bir görünen nadir göksel haberci; beklenmedik ilham, ani dönüşüm ve gökyüzünü yaran ışık izi.',
    archetypes: ['Kâşif', 'Asi'],
    positiveThemes: ['nadir yetenek', 'beklenmedik uyanış', 'hızlı sıçrama', 'özgün iz bırakma'],
    shadowThemes: ['kuyruğunda toz ve kaos bırakma'],
    relatedChakras: [3, 6],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [5, 1],
    relatedAstrology: ['Yay', 'Kova'],
    relatedEnneagram: [7, 8],
    relatedTotemThemes: ['buz ve toz kuyruğu', 'parlak çekirdek', 'eğik yörünge'],
    suitableFor: ['Hayatında sıra dışı, benzersiz bir iz bırakmak ve nadir potansiyelini sergilemek isteyenler'],
    avoidWhen: ['Sakin, durağan ve durağan klasik yapılar'],
    designCompatibility: {
      recommendedStyles: ['Dynamic Fine Line', 'Dotwork Trail', 'Minimalist Stardust'],
      bodyPlacements: ['Köprücük Kemiği Boyunca', 'Önkol Kavis', 'Kaburga'],
      compositionRole: 'Dinamik diyagonal akış çizgisi veya göksel hareket motifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dairesel parlak çekirdek ve arkasından uzanan paralel dalgalı hız çizgileri'
    },
    visualDescription: 'Işıltılı parlak çekirdek ve arkasından süzülen incecik parçacıklı toz/ışık kuyruğu.',
    numerologyConnection: 'Yaşam Yolu 5 ve 1',
    astrologyConnection: 'Yay ve Kova',
    enneagramConnection: 'Tip 7 & Tip 8',
    visualKeywords: ['shooting star comet linework', 'celestial comet tail tattoo', 'astral fire stardust fine line']
  },
  {
    id: 'sym-spiral-galaxy',
    name: 'Spiral Galaksi & Kozmik Girdap (Spiral Galaxy / Vortex)',
    category: 'Kozmik',
    subcategory: 'Merkezkaç Dengesi & Sonsuz Genişleme',
    meaning: 'Milyarlarca yıldızın merkezdeki kara delik etrafında kusursuzca dönmesi; evrenin sonsuz genişlemesi ve merkezkaç dengesi.',
    archetypes: ['Kozmik Gezgin', 'Bütünleştirici'],
    positiveThemes: ['sonsuzluk bilinci', 'büyük resim', 'merkezde kalma gücü', 'sürekli evrim'],
    shadowThemes: ['kendi önemsizliğinde kaybolma'],
    relatedChakras: [7],
    relatedElements: ['Eter'],
    relatedNumerology: [0, 9],
    relatedAstrology: ['Kova', 'Balık'],
    relatedEnneagram: [5, 9],
    relatedTotemThemes: ['samanyolu sarmalı', 'milyonlarca yıldız noktası', 'yerçekimi merkezi'],
    suitableFor: ['Evrenin sonsuzluğu karşısında huşu duyan ve kendi içsel evrenini keşfetmek isteyenler'],
    avoidWhen: ['Aşırı yerel, küçük ve dar odaklı tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Micro Dotwork Galaxy', 'Fine Line Spiral', 'Negative Space Nebula'],
      bodyPlacements: ['Önkol', 'Sırt Kürek Kemiği', 'Göğüs Kafesi'],
      compositionRole: 'Merkezi derinlik girdabı veya arka plan yıldız tozu',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkezden iki zıt yöne açılan logaritmik spiral kolları'
    },
    visualDescription: 'Merkezdeki parlak çekirdekten dışarı doğru dönen iki zarif spiral kol ve mikro dotwork yıldız tozları.',
    numerologyConnection: 'Yaşam Yolu 9 ve Sonsuz Sıfır',
    astrologyConnection: 'Kova ve Balık',
    enneagramConnection: 'Tip 5 & Tip 9',
    visualKeywords: ['milky way spiral galaxy tattoo', 'cosmic vortex sacred geometry', 'stardust galaxy linework']
  },
  {
    id: 'sym-equinox-solstice',
    name: 'Gündönümü & Ekinoks (Solstice & Equinox Cross)',
    category: 'Kozmik',
    subcategory: 'Işık ve Karanlığın Mevsimsel Dengesi',
    meaning: 'Gündüz ve gecenin eşitlendiği ekinokslar ve ışığın en uzun/en kısa olduğu gündönümleri; doğanın 4 ana durağı.',
    archetypes: ['Zaman Çarkı', 'Dengeleyici'],
    positiveThemes: ['mevsimsel ritim', 'ışık-karanlık dengesi', 'doğanın döngüsüne uyum', 'bilinçli geçiş'],
    shadowThemes: ['mevsimsel duygu dalgalanmaları'],
    relatedChakras: [4, 1],
    relatedElements: ['Toprak', 'Ateş', 'Hava', 'Su'],
    relatedNumerology: [4],
    relatedAstrology: ['Koç (İlkbahar)', 'Yengeç (Yaz)', 'Terazi (Sonbahar)', 'Oğlak (Kış)'],
    relatedEnneagram: [1, 9],
    relatedTotemThemes: ['güneş haçı', 'dört mevsim kardinali', 'ışık dönüşümü'],
    suitableFor: ['Kendi hayatında mevsimlerin bilgeliğini taşıyan, denge ve döngü insanları'],
    avoidWhen: ['Yalnızca tek bir mevsim veya tek bir elemente saplanma'],
    designCompatibility: {
      recommendedStyles: ['Solar Cross Geometry', 'Fine Line Four Seasons', 'Minimalist Axes'],
      bodyPlacements: ['Bilek', 'Ense', 'Önkol İç'],
      compositionRole: 'Merkezi 4 yönlü denge haçı veya kılavuz aksı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Daire içine yerleştirilmiş eşit kollu güneş haçı (solar cross) ve 4 köşe işareti'
    },
    visualDescription: 'Daire içine çizilmiş eşit kollu güneş haçı, 4 köşesinde ilkbahar, yaz, sonbahar ve kış mikro sembolleri.',
    numerologyConnection: 'Yaşam Yolu 4 (4 Mevsim ve 4 Yön)',
    astrologyConnection: 'Öncü Burçlar: Koç, Yengeç, Terazi, Oğlak',
    enneagramConnection: 'Tip 1 & Tip 9',
    visualKeywords: ['solar cross wheel tattoo', 'four seasons equinox solstice', 'celtic sun cross fine line']
  },
  {
    id: 'sym-ursa-major',
    name: 'Büyük Ayı Takımyıldızı (Ursa Major / Big Dipper)',
    category: 'Kozmik',
    subcategory: 'Göksel Cezve & Yol Gösterici 7 Yıldız',
    meaning: 'Kuzey göğünün 7 parlak yıldızı; gökteki cezve, Kutup Yıldızı’nı işaret eden rehber takımyıldız ve gece sığınağı.',
    archetypes: ['Rehber', 'Gece Bekçisi'],
    positiveThemes: ['yol bulma', 'kadim kılavuzluk', 'gece güvenliği', 'dayanıklılık'],
    shadowThemes: ['yoldan çıkma endişesi'],
    relatedChakras: [6, 7],
    relatedElements: ['Hava', 'Toprak'],
    relatedNumerology: [7],
    relatedAstrology: ['Büyük Ayı / Kutup Çevresi'],
    relatedEnneagram: [6, 5],
    relatedTotemThemes: ['7 yıldız düğümü', 'cezve formu', 'kuzeye bakan hat'],
    suitableFor: ['Karanlıkta bile yolunu bulabilen, kadim gökyüzü kılavuzluğuna güvenenler'],
    avoidWhen: ['Kaotik, düzensiz ve takımyıldız formu taşımayan tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Constellation Dotwork', 'Fine Line Star Map', 'Minimalist Coordinates'],
      bodyPlacements: ['Köprücük Kemiği', 'Önkol Boydan Boya', 'Kürek Kemiği'],
      compositionRole: 'Yıldız haritası arka planı veya doğrusal rehber hat',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: '7 adet düğüm noktası ve bunları bağlayan kırık doğrusal poligon'
    },
    visualDescription: 'Hassas dotwork yıldız noktaları ve bunları birbirine bağlayan ince kılavuz çizgileriyle Büyük Ayı formu.',
    numerologyConnection: 'Yaşam Yolu 7 (7 Kutsal Yıldız)',
    astrologyConnection: 'Kutup Takımyıldızları',
    enneagramConnection: 'Tip 6 & Tip 5',
    visualKeywords: ['ursa major constellation tattoo', 'big dipper fine line star map', 'seven stars constellation']
  },
  {
    id: 'sym-orion-belt',
    name: 'Orion Takımyıldızı & Avcı Kemeri (Orion’s Belt)',
    category: 'Kozmik',
    subcategory: 'Göksel Avcı & 3 Kral Yıldızı',
    meaning: 'Gökyüzünün dev avcısı ve kemerindeki 3 hizalı yıldız (Alnitak, Alnilam, Mintaka); piramitlerin hizası ve kozmik güç.',
    archetypes: ['Göksel Avcı', 'Savaşçı'],
    positiveThemes: ['hizalanma', 'göksel güç', 'piramidal matematik', 'yüksek hedef'],
    shadowThemes: ['aşırı avlanma hırsı'],
    relatedChakras: [3, 6],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [3, 1],
    relatedAstrology: ['Boğa', 'İkizler'],
    relatedEnneagram: [8, 3],
    relatedTotemThemes: ['3 kemer yıldızı', 'avcı yayı', 'betelgeuse kırmızısı'],
    suitableFor: ['Gözünü en yüksek yıldızlara diken ve hedefini asla şaşırmayan avcı ruhlar'],
    avoidWhen: ['Yumuşak, pasif ve eylemsiz arayışlar'],
    designCompatibility: {
      recommendedStyles: ['Constellation Geometry', 'Fine Line Star Map', 'Minimalist Trio'],
      bodyPlacements: ['Önkol İç', 'Köprücük Altı', 'Omurga'],
      compositionRole: '3 yıldızlı simetrik denge veya avcı yayı aksı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Diyagonal eksende tam hizalanmış 3 eşit yıldız noktası ve çevreleyen kum saati poligonu'
    },
    visualDescription: 'Karakteristik kum saati biçimli Orion takımyıldızı, merkezde mükemmel hizalanmış 3 kemer yıldızı.',
    numerologyConnection: 'Yaşam Yolu 3 (Üç Kral) ve 1',
    astrologyConnection: 'Boğa ve İkizler Sınırı',
    enneagramConnection: 'Tip 8 & Tip 3',
    visualKeywords: ['orions belt constellation tattoo', 'orion hunter sacred geometry', 'three stars alignment fine line']
  },
  {
    id: 'sym-meteor-shower',
    name: 'Meteor Yağmuru & Kayan Yıldızlar (Meteor Shower)',
    category: 'Kozmik',
    subcategory: 'Göksel Dilek Kıvılcımları & Hızlı Değişim',
    meaning: 'Atmosferde parıldayan kayan yıldız izleri; anlık ilham, saf niyetler, göksel dilekler ve hızla gerçekleşen kadersel dönüşüm.',
    archetypes: ['Hayalperest', 'Gezgin Ruh'],
    positiveThemes: ['saf niyet', 'hızlı değişim', 'göksel mucize', 'aydınlanan gece'],
    shadowThemes: ['gelip geçicilik'],
    relatedChakras: [6, 7],
    relatedElements: ['Ateş', 'Eter'],
    relatedNumerology: [1, 5],
    relatedAstrology: ['Yay', 'Kova'],
    relatedEnneagram: [7, 4],
    relatedTotemThemes: ['paralel ışık çizgileri', 'parlayan baş noktası', 'yıldız tozu'],
    suitableFor: ['Kaderin mucizelerine inanan, anlık ilhamlarla hızlı atılımlar yapan hayalperestler'],
    avoidWhen: ['Durağan ve ağırbaşlı hantal temalar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Streaks', 'Dotwork Dust', 'Minimalist Cosmic'],
      bodyPlacements: ['Köprücük Kemiği', 'Bilek', 'Kaburga Yan'],
      compositionRole: 'Diyagonal akış çizgileri veya göksel kıvılcım şeridi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Paralel açılı diyagonal çizgiler ve uçlarında minik parıltı yıldızları'
    },
    visualDescription: 'Gece göğünde paralel diyagonal hatlar halinde hızla süzülen ince çizgisel kayan yıldızlar.',
    numerologyConnection: 'Yaşam Yolu 1 ve 5',
    astrologyConnection: 'Yay ve Kova',
    enneagramConnection: 'Tip 7 & Tip 4',
    visualKeywords: ['meteor shower tattoo linework', 'shooting stars fine line design', 'celestial wish star streak']
  },
  {
    id: 'sym-supernova',
    name: 'Süpernova & Yaratıcı Patlama (Supernova Explosion)',
    category: 'Kozmik',
    subcategory: 'Büyük Dağılma & Yeni Yıldızların Doğumu',
    meaning: 'Ömrünü tamamlayan dev yıldızın patlayarak uzaya tüm elementleri saçması; eski dar kabuğun parçalanıp milyarlarca yeni yıldıza hayat vermesi.',
    archetypes: ['Yaratıcı', 'Yıkıcı ve Dönüştürücü'],
    positiveThemes: ['yaratıcı dönüşüm', 'özgürleşme', 'elementlerin doğuşu', 'büyük atılım'],
    shadowThemes: ['aşırı şiddetli patlama'],
    relatedChakras: [3, 7],
    relatedElements: ['Ateş', 'Eter'],
    relatedNumerology: [9, 1],
    relatedAstrology: ['Koç', 'Aslan', 'Kova'],
    relatedEnneagram: [8, 7],
    relatedTotemThemes: ['radyal ışık patlaması', 'şok dalgaları', 'yıldız tozu saçılımı'],
    suitableFor: ['Eski hayatının kalıplarını kırıp büyük ve görkemli bir yaratım enerjisiyle patlayanlar'],
    avoidWhen: ['Sessiz, kapalı ve durgun münzevi süreçler'],
    designCompatibility: {
      recommendedStyles: ['Sacred Dotwork Explosion', 'Dynamic Fine Line', 'Cosmic Blackwork'],
      bodyPlacements: ['Sırt', 'Omuz Başı', 'Uyluk'],
      compositionRole: 'Merkezden dışa doğru yayılan patlama enerjisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkez noktadan dışarı fışkıran çok katmanlı radyal çizgiler ve dalgalar'
    },
    visualDescription: 'Merkezindeki yoğun çekirdekten dış uzaya geometrik dalgalar halinde yayılan kozmik süpernova patlaması.',
    numerologyConnection: 'Yaşam Yolu 9 ve 1',
    astrologyConnection: 'Koç ve Aslan',
    enneagramConnection: 'Tip 8 & Tip 7',
    visualKeywords: ['supernova explosion tattoo', 'cosmic starburst linework', 'stellar explosion sacred geometry']
  },
  {
    id: 'sym-blood-moon',
    name: 'Kanlı Ay & Tam Ay Tutulması (Blood Moon Lunar Eclipse)',
    category: 'Kozmik',
    subcategory: 'Duygusal Doruk & Bilinçaltının Uyanışı',
    meaning: 'Dünyanın gölgesinde kızıla bürünen dolunay; derin bilinçaltı dürtülerinin arınması, bastırılmış hislerin özgürleşmesi ve ruhsal dönüşüm.',
    archetypes: ['Mistik', 'Gölge Rehberi'],
    positiveThemes: ['duygusal katarsis', 'gizli güçlerin uyanışı', 'derin sezgi', 'arınma'],
    shadowThemes: ['duygusal türbülans'],
    relatedChakras: [2, 6],
    relatedElements: ['Su', 'Ateş'],
    relatedNumerology: [2, 9],
    relatedAstrology: ['Akrep', 'Boğa', 'Yengeç'],
    relatedEnneagram: [4, 8],
    relatedTotemThemes: ['kızıl gölgeli ay', 'dünya gölgesi kavisleri', 'derin okyanus gelgitleri'],
    suitableFor: ['Kendi derin hisleriyle yüzleşip onları sanat ve güce dönüştüren yoğun karakterler'],
    avoidWhen: ['Yalnızca yüzeysel ve duygudan uzak yapılar'],
    designCompatibility: {
      recommendedStyles: ['Red & Black Dotwork', 'Fine Line Eclipse Phases', 'Occult Celestial'],
      bodyPlacements: ['Sternum', 'Önkol İç', 'Ense Altı'],
      compositionRole: 'Merkezi mistik ay odağı veya tutulma evreleri',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İki iç içe geçen daire yayı ve koyu gölge hilali'
    },
    visualDescription: 'Gölgeli dokusu ve çevresindeki ince kılavuz evre yaylarıyla tam ay tutulmasındaki dolunay diski.',
    numerologyConnection: 'Yaşam Yolu 2 ve 9',
    astrologyConnection: 'Akrep ve Boğa',
    enneagramConnection: 'Tip 4 & Tip 8',
    visualKeywords: ['blood moon tattoo linework', 'lunar eclipse dotwork design', 'red moon sacred celestial']
  },
  {
    id: 'sym-aurora',
    name: 'Kutup Işıkları (Aurora Borealis / Australis)',
    category: 'Kozmik',
    subcategory: 'Göksel Manyetizma & Eterik Işık Dansı',
    meaning: 'Güneş rüzgarlarının Dünya\'nın manyetik kalkanıyla buluştuğu eterik dans; gökyüzü ile yeryüzü arasındaki ilahi fısıltı ve büyü.',
    archetypes: ['Büyücü', 'Rüya Gören'],
    positiveThemes: ['ilahi temas', 'eterik akış', 'manyetik koruma', 'büyüleyici zarafet'],
    shadowThemes: ['gerçeklikten kopuk hayalperestlik'],
    relatedChakras: [4, 7],
    relatedElements: ['Eter', 'Hava'],
    relatedNumerology: [7, 11],
    relatedAstrology: ['Kova', 'Balık'],
    relatedEnneagram: [4, 9],
    relatedTotemThemes: ['dalgalanan ışık perdeleri', 'gece göğü parıltısı', 'manyetik dalgalar'],
    suitableFor: ['Hayatın içindeki görünmez büyüyü hisseden, hassas ve ilham dolu ruhlar'],
    avoidWhen: ['Sert, mekanik ve katı geometrik yapılar'],
    designCompatibility: {
      recommendedStyles: ['Waterflow Dotwork', 'Fine Line Wave Curtain', 'Micro Realistic Glow'],
      bodyPlacements: ['Kaburga', 'Sırt Üst', 'Önkol'],
      compositionRole: 'Gökyüzü boyunca süzülen dalgalı perde veya arka plan akışı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dalgalanan dikey paralel sinüs çizgileri ve üstten seyrekleşen gradyan'
    },
    visualDescription: 'Gece göğünde bir perde gibi kavislenerek dalgalanan ince çizgisel kutup ışığı hatları.',
    numerologyConnection: 'Yaşam Yolu 7 ve Üstat 11',
    astrologyConnection: 'Kova ve Balık',
    enneagramConnection: 'Tip 4 & Tip 9',
    visualKeywords: ['aurora borealis tattoo linework', 'northern lights curtain fine line', 'celestial aurora waves']
  }
];
