import { SymbolLibraryItem } from '../../types';

export const ELEMENT_SYMBOLS: SymbolLibraryItem[] = [
  {
    id: 'sym-alchemical-fire',
    name: 'Simyasal Ateş Üçgeni (Alchemical Fire)',
    category: 'Element',
    subcategory: 'Simyasal Ateş & Dönüştürücü Kıvılcım',
    meaning: 'Yukarı bakan eşkenar üçgen; yükselen alev, irade, tutku, dönüştürücü kıvılcım ve eylem cesareti.',
    archetypes: ['Savaşçı', 'Simyacı'],
    positiveThemes: ['dönüştürücü tutku', 'irade gücü', 'eylem cesareti', 'yaratıcı kıvılcım'],
    shadowThemes: ['öfke patlamaları', 'yakıp yıkma'],
    relatedChakras: [3],
    relatedElements: ['Ateş'],
    relatedNumerology: [1, 3],
    relatedAstrology: ['Koç', 'Aslan', 'Yay'],
    relatedEnneagram: [8, 3],
    relatedTotemThemes: ['yukarı bakan üçgen', 'kor alev', 'solar parlama'],
    suitableFor: ['Eylemsizliği kırıp hayatına tutku, cesaret ve net bir irade katmak isteyenler'],
    avoidWhen: ['Zaten aşırı öfkeli ve sakinleşmeye çalışan yangın süreçleri'],
    designCompatibility: {
      recommendedStyles: ['Minimalist Geometry', 'Alchemical Linework', 'Fine Line Triad'],
      bodyPlacements: ['Bilek', 'Önkol İç', 'Ense', 'Parmak'],
      compositionRole: 'Tepe yönlendirici açısı veya simyasal glif mührü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Tabanı yatay, tepesi yukarı bakan tek parça eşkenar üçgen'
    },
    visualDescription: 'Kusursuz yukarı bakan eşkenar üçgen, içinde mikro kıvılcım veya güneş diski.',
    numerologyConnection: 'Yaşam Yolu 1 ve 3 (Ateş ve İfade)',
    astrologyConnection: 'Koç, Aslan, Yay (Ateş Üçlüsü)',
    enneagramConnection: 'Tip 8 & Tip 3',
    visualKeywords: ['alchemical fire triangle tattoo', 'fire element sacred geometry', 'upward triangle linework']
  },
  {
    id: 'sym-alchemical-water',
    name: 'Simyasal Su Üçgeni (Alchemical Water)',
    category: 'Element',
    subcategory: 'Simyasal Su & Sezgisel Akış',
    meaning: 'Aşağı bakan eşkenar üçgen; alıcı kâse, sezgisel derinlik, şifa, duygusal akış ve bilinçaltı.',
    archetypes: ['Şifacı', 'Mistik'],
    positiveThemes: ['sezgisel kavrayış', 'şifa', 'duygusal esneklik', 'alıcılık'],
    shadowThemes: ['duygularda boğulma', 'sınır koyamama'],
    relatedChakras: [2, 4],
    relatedElements: ['Su'],
    relatedNumerology: [2, 9],
    relatedAstrology: ['Yengeç', 'Akrep', 'Balık'],
    relatedEnneagram: [4, 9],
    relatedTotemThemes: ['aşağı bakan üçgen', 'şifa damlası', 'derin göl'],
    suitableFor: ['Katılaşmış kalbini yumuşatmak, sezgilerine güvenmek ve akışa teslim olmak isteyenler'],
    avoidWhen: ['Aşırı melankoli ve somut eyleme geçme ihtiyacı olan süreçler'],
    designCompatibility: {
      recommendedStyles: ['Minimalist Geometry', 'Alchemical Symbol', 'Fine Line Water'],
      bodyPlacements: ['Bilek', 'Kaburga', 'Köprücük Altı'],
      compositionRole: 'Alt kadeh tabanı veya su akışı odak glifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Tepesi aşağı bakan tek parça eşkenar üçgen (dişil kadeh)'
    },
    visualDescription: 'Tepesi aşağı bakan eşkenar üçgen, içinde su dalgası damlası veya hilal.',
    numerologyConnection: 'Yaşam Yolu 2 ve 9 (Su Frekansı)',
    astrologyConnection: 'Yengeç, Akrep, Balık (Su Üçlüsü)',
    enneagramConnection: 'Tip 4 & Tip 9',
    visualKeywords: ['alchemical water triangle tattoo', 'water element chalice linework', 'downward triangle symbol']
  },
  {
    id: 'sym-alchemical-air',
    name: 'Simyasal Hava Üçgeni (Alchemical Air)',
    category: 'Element',
    subcategory: 'Zihinsel Genişleme & Kavramsal Berraklık',
    meaning: 'Yatay çizgiyle kesilen yukarı üçgen; zihinsel yükseliş, bilgi akışı, iletişim, nefes ve özgürlük.',
    archetypes: ['Düşünür', 'Haberci'],
    positiveThemes: ['zihinsel berraklık', 'kavramsal deha', 'iletişim gücü', 'hafiflik'],
    shadowThemes: ['aşırı rasyonalize etme', 'köksüzlük'],
    relatedChakras: [4, 5],
    relatedElements: ['Hava'],
    relatedNumerology: [5, 7],
    relatedAstrology: ['İkizler', 'Terazi', 'Kova'],
    relatedEnneagram: [5, 7],
    relatedTotemThemes: ['çizgili yukarı üçgen', 'rüzgar nefesi', 'tüy hafifliği'],
    suitableFor: ['Düşüncelerini netleştirmek, yeni fikirler üretmek ve özgürleşmek isteyenler'],
    avoidWhen: ['Topraklanma ve fiziksel somutlaşma arayan temalar'],
    designCompatibility: {
      recommendedStyles: ['Alchemical Linework', 'Fine Line Vector', 'Minimalist Glyph'],
      bodyPlacements: ['Önkol İç', 'Ense', 'Bilek'],
      compositionRole: 'Hava akışı düğümü veya zihinsel odak glifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Yukarı bakan eşkenar üçgenin yatay bir çizgiyle üst üçte birden kesilmesi'
    },
    visualDescription: 'Yukarı bakan eşkenar üçgen ve onu yatay olarak kesen ince çizgi.',
    numerologyConnection: 'Yaşam Yolu 5 ve 7 (Zihinsel Uyanış)',
    astrologyConnection: 'İkizler, Terazi, Kova (Hava Üçlüsü)',
    enneagramConnection: 'Tip 5 & Tip 7',
    visualKeywords: ['alchemical air triangle tattoo', 'air element glyph linework', 'alchemical symbol for air']
  },
  {
    id: 'sym-alchemical-earth',
    name: 'Simyasal Toprak Üçgeni (Alchemical Earth)',
    category: 'Element',
    subcategory: 'Maddeye Bürünme & Sarsılmaz Dayanıklılık',
    meaning: 'Yatay çizgiyle kesilen aşağı üçgen; maddeye form verme, topraklanma, sarsılmaz beden ve sabır.',
    archetypes: ['İnşa Eden', 'Toprak Muhafızı'],
    positiveThemes: ['sağlam köklenme', 'fiziksel güç', 'somut sonuç alma', 'dayanıklılık'],
    shadowThemes: ['ağırkanlılık', 'maddeye saplanma'],
    relatedChakras: [1],
    relatedElements: ['Toprak'],
    relatedNumerology: [4, 8],
    relatedAstrology: ['Boğa', 'Başak', 'Oğlak'],
    relatedEnneagram: [1, 8],
    relatedTotemThemes: ['çizgili aşağı üçgen', 'kara taş', 'sabit temel'],
    suitableFor: ['Fikirlerini somut projelere dönüştürmek ve dünyada sarsılmaz bir kök salmak isteyenler'],
    avoidWhen: ['Hafif, uçucu ve rüzgarlı narin işler'],
    designCompatibility: {
      recommendedStyles: ['Alchemical Linework', 'Minimalist Grounding', 'Geometric Earth'],
      bodyPlacements: ['Ayak Bileği', 'Önkol Kaidesi', 'Sırt Alt Omurga'],
      compositionRole: 'Alt topraklama mührü veya kaide taşıyıcısı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Aşağı bakan eşkenar üçgenin yatay bir çizgiyle alt üçte birden kesilmesi'
    },
    visualDescription: 'Aşağı bakan eşkenar üçgen ve onu yatay olarak kesen düz çizgi.',
    numerologyConnection: 'Yaşam Yolu 4 ve 8 (Toprak ve Madde)',
    astrologyConnection: 'Boğa, Başak, Oğlak (Toprak Üçlüsü)',
    enneagramConnection: 'Tip 1 & Tip 8',
    visualKeywords: ['alchemical earth triangle tattoo', 'earth element symbol linework', 'grounding alchemy glyph']
  },
  {
    id: 'sym-lightning-bolt',
    name: 'Şimşek & Yıldırım Çizgisi (Lightning Bolt / Kundalini Strike)',
    category: 'Element',
    subcategory: 'Ani Aydınlanma & Göksel Kıvılcım',
    meaning: 'Gökyüzü ile yeryüzünü anında birleştiren kıvılcım; ani aydınlanma (Satori), Kundalini şoku ve ilahi temas.',
    archetypes: ['Uyanışçı', 'Yıkıcı/Yenileyici'],
    positiveThemes: ['ani idrak', 'yüksek elektrik enerjisi', 'karanlığı yaran ışık', 'hızlı değişim'],
    shadowThemes: ['yıkıcı öfke', 'ani şoklar'],
    relatedChakras: [3, 7],
    relatedElements: ['Ateş', 'Hava', 'Eter'],
    relatedNumerology: [1, 11],
    relatedAstrology: ['Kova (Uranüs Şimşeği)', 'Koç'],
    relatedEnneagram: [8, 7],
    relatedTotemThemes: ['zikzak hat', 'parlak kıvılcım', 'göksel deşarj'],
    suitableFor: ['Hayatında aniden gözü açılan ve yüksek bir enerjiyle dönüşenler'],
    avoidWhen: ['Yavaş, sabırlı ve sakinleştirici terapi süreçleri'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Electric', 'Minimalist Zigzag', 'Geometric Bolt'],
      bodyPlacements: ['Önkol Yanı', 'Kaburga', 'Kulak Arkası / Boyun'],
      compositionRole: 'Dikey keskin enerji hattı veya iki sembolü bağlayan ark',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Keskin açılı zikzak kırık çizgi ve alt ucu sivri ok'
    },
    visualDescription: 'İncecik keskin zikzak çizgisi, tepede minik kıvılcım noktaları ve alta inen keskin ok.',
    numerologyConnection: 'Üstat 11 (Aydınlanma Kanalı) ve 1',
    astrologyConnection: 'Kova (Uranüs Yıldırımı)',
    enneagramConnection: 'Tip 8 & Tip 7',
    visualKeywords: ['lightning bolt fine line tattoo', 'sacred lightning flash linework', 'kundalini bolt tattoo']
  },
  {
    id: 'sym-ocean-wave',
    name: 'Okyanus Dalgası & Büyük Dalga (Ocean Wave / Seigaiha)',
    category: 'Element',
    subcategory: 'Sonsuz Ritim & Yüzeye Çıkış',
    meaning: 'Okyanusun engellenemez kabarması, kıyıya vuran güç ve geri çekilen sükunet; sonsuz ritim ve arınma.',
    archetypes: ['Akış Ustası', 'Şifacı'],
    positiveThemes: ['arınma', 'büyük güç', 'akışta ustalaşma', 'ritmik yenilenme'],
    shadowThemes: ['duygu tsunamisi'],
    relatedChakras: [2],
    relatedElements: ['Su'],
    relatedNumerology: [2, 7],
    relatedAstrology: ['Balık', 'Akrep', 'Yengeç'],
    relatedEnneagram: [4, 9],
    relatedTotemThemes: ['köpüklü tepe', 'akışkan kavis', 'derin su tabanı'],
    suitableFor: ['Hayatın dalgalarıyla savaşmak yerine onların üzerinde sörf yapmayı öğrenenler'],
    avoidWhen: ['Katı, sabit ve kaskatı mimari kurallar'],
    designCompatibility: {
      recommendedStyles: ['Japanese Ukiyo-e Linework', 'Fine Line Wave', 'Single-Line Curl'],
      bodyPlacements: ['Bilek Sarmalı', 'Önkol İç', 'Kaburga Yanı', 'Ayak Bileği'],
      compositionRole: 'Alt kaideyi saran dinamik su hareketi veya yan dalga akışı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Logaritmik spiral şeklinde kıvrılan su tepesi ve paralel dalga kavisleri'
    },
    visualDescription: 'Kıvrılarak kırılan Hokusai tarzı zarif dalga ucu, köpük damlaları ve akışkan su çizgileri.',
    numerologyConnection: 'Yaşam Yolu 2 ve 7 (Su Sezgisi)',
    astrologyConnection: 'Balık ve Yengeç',
    enneagramConnection: 'Tip 4 & Tip 9',
    visualKeywords: ['great wave linework tattoo', 'delicate ocean wave fine line', 'seigaiha sacred water pattern']
  },
  {
    id: 'sym-mountain-peak',
    name: 'Yüce Dağ Zirvesi (Sacred Mountain Peak)',
    category: 'Element',
    subcategory: 'Doruk Noktası & Sarsılmaz Sabır',
    meaning: 'Gökyüzüyle buluşan zirve, sabırla tırmanılan yol, fırtınalarda kıpırdamayan dağ ve yalnızlığın asaleti.',
    archetypes: ['Münzevi', 'Zirveye Ulaşan'],
    positiveThemes: ['yüksek hedefler', 'sarsılmaz sabır', 'göğe yakınlık', 'içsel sükunet'],
    shadowThemes: ['ulaşılmazlık kibri'],
    relatedChakras: [1, 7],
    relatedElements: ['Toprak', 'Hava'],
    relatedNumerology: [4, 7],
    relatedAstrology: ['Oğlak'],
    relatedEnneagram: [1, 5],
    relatedTotemThemes: ['karlı zirve', 'granit sırtlar', 'yükselen üçgen'],
    suitableFor: ['Zorlu engelleri adım adım tırmanıp kendi doruğuna ulaşan sabırlı ruhlar'],
    avoidWhen: ['Hızlı, sabırsız ve anlık geçici hevesler'],
    designCompatibility: {
      recommendedStyles: ['Geometric Mountain', 'Fine Line Ridge', 'Dotwork Peak'],
      bodyPlacements: ['Önkol', 'Bilek', 'Kürek Kemiği', 'Göğüs Altı'],
      compositionRole: 'Sağlam üçgen taban veya yükseliş ekseni',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Birbirini kesen iki veya üç üçgen sırt çizgisi ve dikey doruk noktası'
    },
    visualDescription: 'Keskin sırt hatlarıyla göğe yükselen üçgen dağ zirveleri, ince gölge hatları ve tepede güneş/ay.',
    numerologyConnection: 'Yaşam Yolu 4 (Sağlam Zemin) ve 7 (Dorukta İnziva)',
    astrologyConnection: 'Oğlak (Dağ Keçisi / Satürn)',
    enneagramConnection: 'Tip 1 & Tip 5',
    visualKeywords: ['sacred mountain peak tattoo', 'geometric mountain ridge linework', 'fine line alpine peak']
  },
  {
    id: 'sym-wind-spiral',
    name: 'Rüzgar Spirali & Dört Yön (Wind Spiral / Zephyr)',
    category: 'Element',
    subcategory: 'Görünmeyen Güç & Sonsuz Nefes',
    meaning: 'Görünmeyen ama her şeyi hareket ettiren nefes (Prana / Ruah); esneklik, özgürlük ve ilahi ilham.',
    archetypes: ['Özgür Gezgin', 'Nefes Ustası'],
    positiveThemes: ['taze nefes', 'hafifleme', 'özgür akış', 'görünmeyen rehberlik'],
    shadowThemes: ['uçup gitme', 'tutunamama'],
    relatedChakras: [4, 5],
    relatedElements: ['Hava'],
    relatedNumerology: [5, 0],
    relatedAstrology: ['İkizler', 'Kova'],
    relatedEnneagram: [7, 9],
    relatedTotemThemes: ['kıvrılan hava akımı', 'yaprak savruluşu', 'hafif esinti'],
    suitableFor: ['Tıkanmış hayatına taze bir nefes üflemek ve hafiflemek isteyenler'],
    avoidWhen: ['Ağır, hantal ve aşırı topraklı sabit yapılar'],
    designCompatibility: {
      recommendedStyles: ['Single-Line Flow', 'Fine Line Breeze', 'Minimalist Swirl'],
      bodyPlacements: ['Bilek', 'Köprücük Kemiği', 'Boyun Kökü'],
      compositionRole: 'Diğer katı formları birbirine bağlayan hafif hava akışı çizgisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'S-biçiminde kıvrılan paralel hava akımı çizgileri ve minik spiral uçlar'
    },
    visualDescription: 'Zarifçe kıvrılan ince rüzgar çizgileri ve rüzgarda süzülen mikro botanik yapraklar.',
    numerologyConnection: 'Yaşam Yolu 5 (Hava ve Hareket)',
    astrologyConnection: 'İkizler ve Kova',
    enneagramConnection: 'Tip 7 & Tip 9',
    visualKeywords: ['wind swirl linework tattoo', 'breath of life prana tattoo', 'flowing breeze air element']
  },
  {
    id: 'sym-solar-flare',
    name: 'Çöl Güneşi & Solar Kıvılcım (Desert Sun / Solar Flare)',
    category: 'Element',
    subcategory: 'Ham Isı & Arındırıcı Ateş',
    meaning: 'Gölgesiz mutlak aydınlık, saf yaşam enerjisi, fazlalıklardan arındıran çöl güneşi ve içsel ateş.',
    archetypes: ['Güneş Hükümdarı', 'Arındırıcı'],
    positiveThemes: ['saf netlik', 'yaşam enerjisi', 'gölgesiz dürüstlük', 'solar güç'],
    shadowThemes: ['yakıcı kuraklık', 'merhametsizlik'],
    relatedChakras: [3],
    relatedElements: ['Ateş'],
    relatedNumerology: [1, 19],
    relatedAstrology: ['Aslan', 'Koç'],
    relatedEnneagram: [3, 8],
    relatedTotemThemes: ['radyal ışınlar', 'çöl ufku', 'altın parlama'],
    suitableFor: ['İçindeki ateşi ve özgüveni söndürmeden parlatmak isteyen solar ruhlar'],
    avoidWhen: ['Serinlik ve su aranan sakinleştirici süreçler'],
    designCompatibility: {
      recommendedStyles: ['Geometric Sun', 'Fine Line Radiant', 'Dotwork Halo'],
      bodyPlacements: ['Omuz Başı', 'Ense', 'Önkol İç'],
      compositionRole: 'Merkezi ısı kaynağı veya tepe radyal tacı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkez çember etrafında ardışık uzun ve dalgalı radyal üçgen ışınlar'
    },
    visualDescription: 'Merkezde tam daire, çevresinde kıvrımlı ve düz ışınların ritmik ardışıklığıyla parlayan güneş.',
    numerologyConnection: 'Yaşam Yolu 1 ve 19 (Güneş Sayısı)',
    astrologyConnection: 'Aslan (Güneş Yöneticisi)',
    enneagramConnection: 'Tip 3 & Tip 8',
    visualKeywords: ['desert sun radiant tattoo', 'sacred solar flare linework', 'sun rays geometric tattoo']
  },
  {
    id: 'sym-volcano',
    name: 'Volkan & Magma (Sacred Volcano)',
    category: 'Element',
    subcategory: 'Derinlerden Yükselen Güç & Yeni Toprak',
    meaning: 'Derinlerde biriken enerjinin yaratıcı patlaması; lavların soğuyup yeni adalar ve bereketli topraklar yaratması.',
    archetypes: ['Dönüştürücü', 'Yaratıcı Güç'],
    positiveThemes: ['derin gücün açığa çıkması', 'yeni zemin yaratma', 'katarsis', 'özgün dönüşüm'],
    shadowThemes: ['öfke patlamaları', 'yakıcı kontrolsüzlük'],
    relatedChakras: [1, 3],
    relatedElements: ['Ateş', 'Toprak'],
    relatedNumerology: [8, 1],
    relatedAstrology: ['Akrep', 'Koç'],
    relatedEnneagram: [8],
    relatedTotemThemes: ['lav akışı', 'krater dumanı', 'kara bazalt taş'],
    suitableFor: ['İçindeki devasa yaratıcı veya dönüştürücü potansiyeli serbest bırakmak isteyenler'],
    avoidWhen: ['Sakin ve çatışmasız denge aranan dönemler'],
    designCompatibility: {
      recommendedStyles: ['Etching Volcano', 'Fine Line Geology', 'Black & Grey Contrast'],
      bodyPlacements: ['Pazu', 'Önkol', 'Baldır'],
      compositionRole: 'Merkezi patlayıcı enerji ekseni veya taban kaidesi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Kesik üçgen dağ konisi ve kraterden yukarı açılan radyal alev/duman ışınları'
    },
    visualDescription: 'Konik volkan silueti, kraterinden yukarı yükselen ince duman ve geometrik lav çizgileri.',
    numerologyConnection: 'Yaşam Yolu 8 ve 1 (Dönüşüm ve Başlangıç)',
    astrologyConnection: 'Akrep ve Koç (Plüton ve Mars)',
    enneagramConnection: 'Tip 8 (Meydan Okuyan)',
    visualKeywords: ['volcano eruption linework tattoo', 'magma earth fire sacred geometry', 'volcanic mountain tattoo']
  },
  {
    id: 'sym-lightning-flash',
    name: 'Kozmik Şimşek & Yıldırım Oku (Lightning Flash)',
    category: 'Element',
    subcategory: 'Ani Aydınlanma & Göksel Kıvılcım',
    meaning: 'Bulutları yarıp yeryüzüne inen saf elektrik ateşi; ani uyanış, cehaleti delen satori idraki ve yaratıcı ilham şoku.',
    archetypes: ['İlham Perisi', 'Göksel Savaşçı'],
    positiveThemes: ['ani aydınlanma', 'hızlı vizyon', 'saf enerji', 'karanlığı delme'],
    shadowThemes: ['yıkıcı acelecilik', 'ani öfke'],
    relatedChakras: [3, 6, 7],
    relatedElements: ['Ateş', 'Hava', 'Eter'],
    relatedNumerology: [1, 11],
    relatedAstrology: ['Kova', 'Koç', 'Yay'],
    relatedEnneagram: [7, 8],
    relatedTotemThemes: ['zikzak kırık hat', 'elektrik kıvılcımı', 'gök gürültüsü'],
    suitableFor: ['Hayatında anlık ilham patlamalarıyla yön bulan, cesur ve dinamik yaratıcılar'],
    avoidWhen: ['Yavaş, ağır ve tamamen durağan süreçler'],
    designCompatibility: {
      recommendedStyles: ['Minimalist Fine Line', 'Geometric Lightning', 'Dotwork Spark'],
      bodyPlacements: ['Bilek', 'Kulak Arkası / Boyun', 'Önkol Yan', 'Parmak'],
      compositionRole: 'Dikey enerji iletim oku veya anlık kıvılcım detayı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Keskin açılı zikzak hat ve ucunda sivri ok ucu'
    },
    visualDescription: 'Keskin açılı kırık zikzak hatlarıyla gökten inen tek ve net çizgili şimşek oku.',
    numerologyConnection: 'Yaşam Yolu 1 ve Üstat 11',
    astrologyConnection: 'Kova (Uranüs) ve Koç',
    enneagramConnection: 'Tip 7 & Tip 8',
    visualKeywords: ['lightning bolt tattoo linework', 'minimalist lightning flash', 'sacred lightning arrow symbol']
  },
  {
    id: 'sym-ocean-vortex',
    name: 'Okyanus Girdabı (Ocean Vortex & Deep Waters)',
    category: 'Element',
    subcategory: 'Derin Bilinçaltı & Teslimiyet Akıntısı',
    meaning: 'Okyanusun en derin akıntılarının oluşturduğu sarmal girdap; yüzeydeki dalgaların ötesine geçip bilinçaltının derinliklerine inme ve yenilenerek doğma.',
    archetypes: ['Derin Arayıcı', 'Deniz Simyacısı'],
    positiveThemes: ['derin teslimiyet', 'bilinçaltı arınması', 'akıntıya uyum', 'yenilenme'],
    shadowThemes: ['kendi duygularında boğulma hissi'],
    relatedChakras: [2, 6],
    relatedElements: ['Su'],
    relatedNumerology: [2, 7],
    relatedAstrology: ['Balık', 'Akrep', 'Yengeç'],
    relatedEnneagram: [4, 9],
    relatedTotemThemes: ['içe doğru dönen su dalgaları', 'deniz köpüğü', 'merkez sükûneti'],
    suitableFor: ['Kendi derin duygularından korkmayan, akışa teslim olarak dönüşen duygusal ve sezgisel ruhlar'],
    avoidWhen: ['Katı, kontrolcü ve duygudan uzak yapılar'],
    designCompatibility: {
      recommendedStyles: ['Waterflow Dotwork', 'Fine Line Ripple', 'Japanese Wave Motif'],
      bodyPlacements: ['Önkol İç', 'Kaburga', 'Omuz Çevresi'],
      compositionRole: 'İçe çeken dinamik sarmal veya kompozisyonun su tabanı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Eşmerkezli logaritmik dalga spirali ve damlacık noktaları'
    },
    visualDescription: 'Dairesel bir merkez etrafında sarmal olarak içe doğru kıvrılan zarif okyanus dalga çizgileri.',
    numerologyConnection: 'Yaşam Yolu 2 ve 7',
    astrologyConnection: 'Balık ve Akrep',
    enneagramConnection: 'Tip 4 & Tip 9',
    visualKeywords: ['ocean vortex tattoo', 'whirlpool sacred geometry linework', 'flowing water spiral tattoo']
  },
  {
    id: 'sym-celestial-wind',
    name: 'Kozmik Rüzgar Gülü & Eter Nefesi (Wind Rose of Aether)',
    category: 'Element',
    subcategory: 'Dört Yönün Nefesi & Görünmez Ruh',
    meaning: 'Kuzey, güney, doğu ve batı rüzgarlarının birleştiği eterik nefes; görünmeyen fakat tüm hayatı hareket ettiren kutsal rüzgarın bilgeliği.',
    archetypes: ['Gezgin', 'Hava Ruhu'],
    positiveThemes: ['özgür yönelim', 'taze nefes', 'zihinsel ferahlık', 'ufuk açıklığı'],
    shadowThemes: ['köklenememe', 'havailik'],
    relatedChakras: [4, 5],
    relatedElements: ['Hava', 'Eter'],
    relatedNumerology: [5, 4],
    relatedAstrology: ['İkizler', 'Terazi', 'Kova'],
    relatedEnneagram: [7, 5],
    relatedTotemThemes: ['dört yapraklı rüzgar gülü', 'kavisli hava akımları', 'pusula yaprakları'],
    suitableFor: ['Fikirleri ve hayalleri sınırsız olan, her yöne özgürce seyahat eden açık zihinler'],
    avoidWhen: ['Ağır, hantal ve tamamen toprağa saplanmış yapılar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Compass', 'Art Nouveau Breeze', 'Sacred Geometric Winds'],
      bodyPlacements: ['Köprücük Kemiği', 'Bilek', 'Ense Altı'],
      compositionRole: 'Yönlendirici pusula ekseni veya hafif esinti tamamlayıcısı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dört ana yönü gösteren sivri elmas yapraklar ve çevreleyen hava halkaları'
    },
    visualDescription: 'Zarif kavisli rüzgar akımlarıyla çevrelenmiş, dört yöne açılan geometrik rüzgar gülü pusulası.',
    numerologyConnection: 'Yaşam Yolu 5 ve 4',
    astrologyConnection: 'İkizler ve Terazi',
    enneagramConnection: 'Tip 7 & Tip 5',
    visualKeywords: ['wind rose tattoo linework', 'breath of aether sacred geometry', 'nautical wind rose fine line']
  },
  {
    id: 'sym-crystal-geode',
    name: 'Kutsal Kristal Geod (Sacred Crystal Geode & Quartz)',
    category: 'Element',
    subcategory: 'Kayada Saklı Işık & Kristal Berraklık',
    meaning: 'Dışı sıradan bir kaya içi ise milyonlarca parıldayan ametist/kuvars kristalleriyle dolu kutsal taş; içsel saflık, korunmuş güzellik ve kristalize olmuş bilinç.',
    archetypes: ['Münzevi', 'İçsel Cevher'],
    positiveThemes: ['içsel saflık', 'kristal berraklık', 'özdeğer', 'korunmuş parlaklık'],
    shadowThemes: ['dış kabuğunu kırmaya korkma'],
    relatedChakras: [6, 7, 4],
    relatedElements: ['Toprak', 'Eter'],
    relatedNumerology: [7, 4, 11],
    relatedAstrology: ['Başak', 'Oğlak', 'Balık'],
    relatedEnneagram: [4, 5],
    relatedTotemThemes: ['geometrik kristal uçları', 'kaya kabuğu', 'ışık prizması'],
    suitableFor: ['Dış görünüşün ötesinde zengin bir iç dünyası olan, kendi özündeki cevheri keşfedenler'],
    avoidWhen: ['Yüzeysel ve gösteriş odaklı sığ yapılar'],
    designCompatibility: {
      recommendedStyles: ['Geometric Crystal Linework', 'Dotwork Mineral', 'Fine Line Prism'],
      bodyPlacements: ['Önkol', 'Sternum Altı', 'Kürek Kemiği'],
      compositionRole: 'Merkezi kristal odak veya zemin kristal kümesi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Açılı altıgen prizmalar ve keskin uçlu kristal yüzeyleri'
    },
    visualDescription: 'Dışındaki sert taş kabuğu aralanmış, içindeki geometrik fasetli kuvars kristal prizmaları parıldayan geod.',
    numerologyConnection: 'Yaşam Yolu 7 ve 4',
    astrologyConnection: 'Başak ve Oğlak',
    enneagramConnection: 'Tip 4 & Tip 5',
    visualKeywords: ['crystal geode linework tattoo', 'sacred quartz crystal geometry', 'amethyst geode fine line tattoo']
  }
];
