import { SymbolLibraryItem } from '../../types';

export const GEOMETRY_SYMBOLS: SymbolLibraryItem[] = [
  {
    id: 'sym-metatron',
    name: 'Metatron Küpü (Metatron Cube)',
    category: 'Geometri',
    subcategory: 'Platonik Matris & Kozmik Koruma',
    meaning: 'Evrenin 5 Platonik katısını ve tüm yaratılış şablonlarını içeren ilahi koruma matrisi.',
    archetypes: ['Mimar', 'Bilge', 'Muhafız'],
    positiveThemes: ['yüksek kozmik nizam', 'psişik kalkan', 'çok boyutlu denge', 'kutsal geometri'],
    shadowThemes: ['aşırı kusursuzluk takıntısı', 'soğuk rasyonalizm'],
    relatedChakras: [1, 2, 3, 4, 5, 6, 7],
    relatedElements: ['Toprak', 'Su', 'Hava', 'Ateş', 'Eter'],
    relatedNumerology: [4, 11, 22, 33],
    relatedAstrology: ['Kova', 'Başak'],
    relatedEnneagram: [1, 5],
    relatedTotemThemes: ['13 çember', 'bağlayıcı doğrular', 'ilahi mimari'],
    suitableFor: ['Kişisel alanını korumak ve hayatında kusursuz bir düzen kurmak isteyenler'],
    avoidWhen: ['Yalnızca organik, asimetrik ve serbest akışkan arayışlarda fazla geometrik kalabilir'],
    designCompatibility: {
      recommendedStyles: ['Sacred Geometry', 'Fine Line', 'Dotwork', 'Geometric Blackwork'],
      bodyPlacements: ['Sırt Merkezi', 'Göğüs Kafesi', 'Önkol İç', 'Kürek Kemiği Arası'],
      compositionRole: 'Kompozisyonun taşıyıcı arka plan armatürü veya merkez mührü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: '13 kürenin merkezlerini birleştiren 78 düz çizgi ve iç içe geçmiş hekzagram'
    },
    visualDescription: 'Kesişen hassas 13 çember ve bunları birbirine bağlayan kristalize 03RL kılavuz doğruları.',
    numerologyConnection: 'Üstat Sayılar 11, 22, 33 ve Yaşam Yolu 4',
    astrologyConnection: 'Kova ve Başak (Kozmik mimari)',
    enneagramConnection: 'Tip 1 & Tip 5',
    visualKeywords: ['metatron cube linework', 'sacred geometry vector', 'platonic solids inscribed', 'crisp dotwork geometry']
  },
  {
    id: 'sym-flower-of-life',
    name: 'Yaşam Çiçeği (Flower of Life)',
    category: 'Geometri',
    subcategory: 'Evrensel Şablon & Birlik',
    meaning: 'Varoluşun birbiriyle kesişen 19 çemberi; birlik, evrensel harmoni, yaşam döngüsü ve kutsal rezonans.',
    archetypes: ['Yaratıcı', 'Şifacı', 'Bütünleştirici'],
    positiveThemes: ['birlik bilinci', 'bütünsel şifa', 'evrensel desen', 'sonsuz bağlantı'],
    shadowThemes: ['sınırların belirsizleşmesi', 'bireyselliğin kaybolması'],
    relatedChakras: [4, 7],
    relatedElements: ['Eter', 'Su'],
    relatedNumerology: [9, 19],
    relatedAstrology: ['Terazi', 'Balık'],
    relatedEnneagram: [9],
    relatedTotemThemes: ['kesişen çemberler', 'altılı simetri', 'yaratılış çiçeği'],
    suitableFor: ['İçsel kaosunu dinginleştirip evrensel düzenle senkronize olmak isteyenler'],
    avoidWhen: ['Sert ve keskin çatışma/savunma odaklı temalarda fazla yumuşak kalabilir'],
    designCompatibility: {
      recommendedStyles: ['Dotwork Mandala', 'Fine Line', 'Geometric Backpiece'],
      bodyPlacements: ['Sırt', 'Omuz Başı', 'Göğüs', 'Baldır'],
      compositionRole: 'Tüm kompozisyonu arkadan kucaklayan hassas mandala matrisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Eşit yarıçaplı 19 kesişen çember ve çevreleyen çift dairesel sınır'
    },
    visualDescription: 'Birbirinin merkezinden geçen 19 eşit çemberin oluşturduğu 6 yapraklı kutsal desen.',
    numerologyConnection: '19 İlahi Yardım ve Yaşam Yolu 9',
    astrologyConnection: 'Terazi ve Balık',
    enneagramConnection: 'Tip 9 (Birlik Bilinci)',
    visualKeywords: ['flower of life circles', 'sacred overlapping spheres', 'mandala life pattern']
  },
  {
    id: 'sym-fibonacci',
    name: 'Fibonacci Altın Spirali (Golden Ratio Spiral)',
    category: 'Geometri',
    subcategory: 'Doğal Büyüme & İlahi Oran',
    meaning: 'Doğanın büyüme formülü (Phi: 1.618), sürekli genişleyen bilinç, nautilus formu ve estetik kusursuzluk.',
    archetypes: ['Kâşif', 'Yaratıcı'],
    positiveThemes: ['genişleyen bilinç', 'doğal evrim', 'altın oran estetiği', 'sonsuz büyüme'],
    shadowThemes: ['doyumsuzluk', 'merkezden uzaklaşma korkusu'],
    relatedChakras: [3, 6],
    relatedElements: ['Hava', 'Toprak'],
    relatedNumerology: [3, 5],
    relatedAstrology: ['Yay', 'Terazi'],
    relatedEnneagram: [7, 3],
    relatedTotemThemes: ['nautilus kabuğu', 'spiral galaksi', 'logaritmik büyüme'],
    suitableFor: ['Kişisel gelişimini ve bilincini adım adım genişletmek isteyen vizyonerler'],
    avoidWhen: ['Statik, durağan ve tamamen kapalı simetri arayan tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Mathematical Linework', 'Dotwork Spiral'],
      bodyPlacements: ['Önkol İç', 'Kürek Kemiği', 'Boyun Kökü', 'Kaburga'],
      compositionRole: 'Tasarımı hareketlendiren dinamik kılavuz yay ve göz yönlendirici eksen',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Fibonacci kareleri gridi ve kesintisiz altın oran spiral eğrisi'
    },
    visualDescription: '1, 1, 2, 3, 5, 8, 13 oranlı karelerden doğan pürüzsüz logaritmik spiral çizgisi.',
    numerologyConnection: 'Yaşam Yolu 3 ve 5 (Genişleme)',
    astrologyConnection: 'Yay ve Terazi',
    enneagramConnection: 'Tip 7 & Tip 3',
    visualKeywords: ['golden ratio nautilus spiral', 'sacred fibonacci grid', 'spiral galaxy geometric line']
  },
  {
    id: 'sym-sri-yantra',
    name: 'Sri Yantra',
    category: 'Geometri',
    subcategory: 'Tantra & Eril-Dişil Polarite',
    meaning: 'Eril (Şiva) ve dişil (Şakti) enerjilerin 9 iç içe üçgenle mükemmel birleşimi, yüksek odak ve sınırsız bolluk.',
    archetypes: ['Hükümdar', 'Mistik', 'Yaratıcı'],
    positiveThemes: ['kutupların dengesi', 'manifestasyon gücü', 'tepe odak', 'manevi refah'],
    shadowThemes: ['aşırı karmaşıklık', 'zihinsel yorgunluk'],
    relatedChakras: [6, 7, 3],
    relatedElements: ['Ateş', 'Eter'],
    relatedNumerology: [3, 6, 9],
    relatedAstrology: ['Koç', 'Aslan'],
    relatedEnneagram: [3, 8],
    relatedTotemThemes: ['bindu merkezi', 'iç içe 9 üçgen', 'lotus halkaları'],
    suitableFor: ['Eril ve dişil taraflarını dengelemek ve hedeflerine sarsılmaz odaklanmak isteyenler'],
    avoidWhen: ['Fazla minik ve sıkışık alanlarda (mikro boyutta detaylar birbirine girebilir)'],
    designCompatibility: {
      recommendedStyles: ['Sacred Geometry', 'Ultra-Fine Line', 'Dotwork'],
      bodyPlacements: ['Sırt Tam Merkez', 'Göğüs Kafesi', 'Uyluk Üstü'],
      compositionRole: 'Merkezi yüksek frekanslı meditasyon odak noktası',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: '4 yukarı 5 aşağı bakan 9 kesişen ikizkenar üçgen ve merkezi bindu noktası'
    },
    visualDescription: 'Merkezdeki bindu noktasından yayılan 9 kesişen üçgen, etrafında lotus yaprakları ve koruyucu kapı.',
    numerologyConnection: 'Yaşam Yolu 3, 6, 9 triad dengesi',
    astrologyConnection: 'Koç ve Aslan (Solar odak)',
    enneagramConnection: 'Tip 3 & Tip 8',
    visualKeywords: ['interlocking triangles sri yantra', 'vedic sacred yantra', 'precise fine lines']
  },
  {
    id: 'sym-seed-of-life',
    name: 'Yaşam Tohumu (Seed of Life)',
    category: 'Geometri',
    subcategory: 'Yaratılışın Şablonu',
    meaning: 'Yaratılışın 7 döngüsünü temsil eden 7 iç içe çember; her yeni fikrin, projenin ve yaşamın kutsal tohumu.',
    archetypes: ['Yaratıcı', 'Masum'],
    positiveThemes: ['yeni başlangıçlar', 'yaratılış kıvılcımı', 'sadelik içinde güç', 'doğurganlık'],
    shadowThemes: ['tohum halinde kalıp eyleme geçememe'],
    relatedChakras: [2, 4],
    relatedElements: ['Su', 'Eter'],
    relatedNumerology: [7, 1],
    relatedAstrology: ['Yengeç', 'Koç'],
    relatedEnneagram: [1, 9],
    relatedTotemThemes: ['7 çember', 'merkezi küre', '6 dış taç'],
    suitableFor: ['Hayatında yepyeni bir doğum, başlangıç veya yaratım projesi başlatanlar'],
    avoidWhen: ['Ağır, koyu ve yıkım/bitiş temalı projelerde fazla umut dolu kalabilir'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Minimalist Geometry', 'Dotwork'],
      bodyPlacements: ['Bilek İçi', 'Ense Altı', 'Önkol', 'Köprücük Kemiği Yanı'],
      compositionRole: 'Minimalist merkezi mühür veya daha büyük mandalanın çekirdeği',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Bir merkezi çember ve çevresine tam oturan 6 çember kesişimi'
    },
    visualDescription: 'Merkezi bir çember ve onun çeperlerinden geçen 6 simetrik çemberin oluşturduğu 6 yapraklı tohum rozeti.',
    numerologyConnection: '7 Kutsal Döngü ve Yaşam Yolu 1 (Tohum)',
    astrologyConnection: 'Yengeç ve Koç',
    enneagramConnection: 'Tip 1 & Tip 9',
    visualKeywords: ['seed of life sacred geometry', 'seven circles creation', 'minimalist sacred geometry seed']
  },
  {
    id: 'sym-merkaba',
    name: 'Merkaba (Yıldız Tetrahedron)',
    category: 'Geometri',
    subcategory: 'Işık Beden & Boyutlar Arası Taşıt',
    meaning: 'Zıt yönlere dönen iki tetrahedron (Mer: Işık, Ka: Ruh, Ba: Beden); ruhsal yükseliş ve boyutlar arası kalkan.',
    archetypes: ['Mistik', 'Gezgin', 'Simyacı'],
    positiveThemes: ['ışık beden aktivasyonu', 'kutupların simyası', 'zaman-mekan ötesi vizyon', 'koruma'],
    shadowThemes: ['dünyadan kopukluk', 'aşırı zihinsel soyutlanma'],
    relatedChakras: [4, 6, 7],
    relatedElements: ['Ateş', 'Hava', 'Eter'],
    relatedNumerology: [8, 11],
    relatedAstrology: ['Kova', 'Yay'],
    relatedEnneagram: [5, 7],
    relatedTotemThemes: ['iç içe iki piramit', 'yıldız tetrahedron', 'dönen ışık alanı'],
    suitableFor: ['Meditatif derinlik, astral denge ve çok boyutlu koruma isteyen arayışçılar'],
    avoidWhen: ['Topraksı ve dünyevi somut iş odaklı konularda havada kalabilir'],
    designCompatibility: {
      recommendedStyles: ['3D Sacred Geometry', 'Fine Line', 'Dotwork Stippling'],
      bodyPlacements: ['Sırt Üst', 'Önkol Dış', 'Göğüs Kafesi'],
      compositionRole: 'Merkezi kristal odak veya koruyucu göğüs mührü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İki boyutlu projeksiyonda hekzagram yıldızı ve 3D derinlik kılavuz hatları'
    },
    visualDescription: 'Biri yukarı (eril/göksel) diğeri aşağı (dişil/yeryüzü) bakan iki tetrahedronun 3D izometrik çizimi.',
    numerologyConnection: 'Yaşam Yolu 8 ve Üstat 11',
    astrologyConnection: 'Kova ve Yay',
    enneagramConnection: 'Tip 5 & Tip 7',
    visualKeywords: ['merkaba star tetrahedron', 'sacred geometry light body', '3d geometric star linework']
  },
  {
    id: 'sym-torus',
    name: 'Torus (Dönen Enerji Alanı)',
    category: 'Geometri',
    subcategory: 'Kendi Kendini Besleyen Yaşam Döngüsü',
    meaning: 'Evrenin, galaksilerin, kalbin ve insan aurasının kendi kendini besleyen dinamik enerji girdabı ve donut formu.',
    archetypes: ['Bütünleştirici', 'Simyacı'],
    positiveThemes: ['sonsuz enerji akışı', 'öz-yeterlilik', 'aura kalkanı', 'merkezlenme'],
    shadowThemes: ['kendi döngüsünde sıkışıp kalma'],
    relatedChakras: [4],
    relatedElements: ['Eter', 'Hava'],
    relatedNumerology: [0, 9],
    relatedAstrology: ['Balık', 'Terazi'],
    relatedEnneagram: [9, 5],
    relatedTotemThemes: ['simit formu', 'kalp manyetik alanı', 'içe ve dışa spiral akış'],
    suitableFor: ['Kendi enerjisini tüketmeden kendi kaynağından beslenmek isteyen şifacılar'],
    avoidWhen: ['Açık uçlu, çizgisel ve hedefe kilitli ok tasarımları'],
    designCompatibility: {
      recommendedStyles: ['Vector Line Art', 'Fine Line Moire', 'Dotwork'],
      bodyPlacements: ['Göğüs Merkezi', 'Önkol İç', 'Sırt'],
      compositionRole: 'Kalp hizası enerjetik omurga merkezi veya küresel kafes',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Kesişen elips spiralleri ile oluşturulmuş 3D torus kafesi'
    },
    visualDescription: 'Merkezdeki sıfır noktasından çıkıp dışarı dönerek tekrar tabandan içeri giren dinamik çizgi kafesi.',
    numerologyConnection: 'Yaşam Yolu 9 ve Çemberin Tamamlanması',
    astrologyConnection: 'Balık ve Terazi',
    enneagramConnection: 'Tip 9 & Tip 5',
    visualKeywords: ['torus sacred geometry', 'vortex energy lines', 'torus donut linework', 'heart electromagnetic field']
  },
  {
    id: 'sym-vesica-piscis',
    name: 'Vesica Piscis (Balık Kesiti / Kutsal Kapı)',
    category: 'Geometri',
    subcategory: 'Yaratılış Kapısı & İki Dünyanın Kesişimi',
    meaning: 'İki eşit çemberin merkezlerinden kesiştiği ilahi ara alan; ruh ile maddenin birleştiği kutsal doğum kapısı.',
    archetypes: ['Yaratıcı', 'Köprü Kuran'],
    positiveThemes: ['boyutlar arası kapı', 'dişil yaratım gücü', 'ruh-madde sentezi', 'ilahi oran'],
    shadowThemes: ['kararsızlık', 'iki dünya arasında sıkışma'],
    relatedChakras: [2, 6],
    relatedElements: ['Su', 'Eter'],
    relatedNumerology: [2, 11],
    relatedAstrology: ['Balık', 'Yengeç'],
    relatedEnneagram: [4, 9],
    relatedTotemThemes: ['kesişen iki küre', 'badem formu mandorla', 'ilahi göz'],
    suitableFor: ['İki farklı dünyayı, kariyeri veya içsel zıtlığı bir potada eritmek isteyenler'],
    avoidWhen: ['Tekil monolitik ve tamamen tek yöne odaklı yapılar'],
    designCompatibility: {
      recommendedStyles: ['Minimalist Fine Line', 'Classical Mandorla', 'Sacred Dotwork'],
      bodyPlacements: ['Önkol', 'Köprücük Ortası', 'Omurga'],
      compositionRole: 'Merkezi çerçeve (mandorla) veya üçüncü göz kapısı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İki kesişen çemberin ortasında kalan badem şekilli lens'
    },
    visualDescription: 'İki dairenin birleşimiyle oluşan dikey badem formu (mandorla) ve içindeki altın oran çizgileri.',
    numerologyConnection: 'Yaşam Yolu 2 (Kutsal İkili) ve Üstat 11',
    astrologyConnection: 'Balık ve Yengeç',
    enneagramConnection: 'Tip 4 & Tip 9',
    visualKeywords: ['vesica piscis sacred geometry', 'mandorla portal linework', 'two intersecting circles']
  },
  {
    id: 'sym-celtic-knot',
    name: 'Kelt Düğümü & Triquetra (Celtic Knot)',
    category: 'Geometri',
    subcategory: 'Sonsuz Düğüm & Kesintisiz Döngü',
    meaning: 'Başlangıcı ve sonu olmayan kesintisiz çizgi; kaderin dokusu, ebedi ruh, üçlü tanrıça ve ilahi koruma.',
    archetypes: ['Muhafız', 'Dokumacı'],
    positiveThemes: ['kesintisiz koruma', 'ebediyet', 'kader bağı', 'kırılmaz sadakat'],
    shadowThemes: ['kendi düğümlerinde boğulma', 'çözümsüzlük döngüsü'],
    relatedChakras: [4, 6],
    relatedElements: ['Toprak', 'Su'],
    relatedNumerology: [3, 6],
    relatedAstrology: ['Boğa', 'Yengeç'],
    relatedEnneagram: [6, 1],
    relatedTotemThemes: ['sonsuz ilmek', 'üçlü kavis', 'kesintisiz şerit'],
    suitableFor: ['Hayatında kopmaz bir bağ, koruyucu zırh ve ebedi sadakat arayanlar'],
    avoidWhen: ['Hafif hava ve sürekli değişen rüzgarlı temalarda fazla sıkı kalabilir'],
    designCompatibility: {
      recommendedStyles: ['Celtic Knotwork', 'Fine Line Ribbon', 'Blackwork'],
      bodyPlacements: ['Bilek', 'Pazu', 'Kürek Kemiği', 'Bacak'],
      compositionRole: 'Bağlayıcı köprü çerçeve veya koruyucu merkez rozeti',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Üstten ve alttan geçen tek parçalı kesintisiz şerit geometrisi'
    },
    visualDescription: 'Birbirinin altından ve üstünden geçen kesintisiz tek şerit ve üçlü döngü oluşturan triquetra kavisleri.',
    numerologyConnection: 'Yaşam Yolu 3 (Üçleme) ve 6 (Koruma)',
    astrologyConnection: 'Boğa ve Yengeç',
    enneagramConnection: 'Tip 6 & Tip 1',
    visualKeywords: ['celtic knotwork linework', 'triquetra infinite knot', 'sacred continuous ribbon tattoo']
  },
  {
    id: 'sym-labyrinth',
    name: 'Chartres Labirenti (Classical Labyrinth)',
    category: 'Geometri',
    subcategory: 'İçsel Arayış & Merkeze Yolculuk',
    meaning: 'Çıkmazı olmayan tek patikalı (unicursal) kutsal yol; dış dünyadan öz benliğin merkezine yapılan hac yolculuğu.',
    archetypes: ['Gezgin', 'Münzevi'],
    positiveThemes: ['içsel merkezlenme', 'kaybolmadan arayış', 'meditasyon', 'öz-keşif'],
    shadowThemes: ['yolun uzunluğundan yorulma', 'içine kapanma'],
    relatedChakras: [6, 1],
    relatedElements: ['Toprak', 'Eter'],
    relatedNumerology: [7, 4],
    relatedAstrology: ['Başak', 'Oğlak'],
    relatedEnneagram: [5, 4],
    relatedTotemThemes: ['tek patika', 'merkez gül', 'konsantrik dönüşler'],
    suitableFor: ['Kendi merkezini bulmak ve karmaşık hayat yolunda sakin adımlarla ilerlemek isteyenler'],
    avoidWhen: ['Aceleci, patlayıcı ve ani eylem gerektiren savaşçı hedefler'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Concentric', 'Dotwork Path', 'Medieval Engraving'],
      bodyPlacements: ['Önkol', 'Sırt Üstü', 'Göğüs Kafesi'],
      compositionRole: 'Merkezi zemin mandalası veya taşıyıcı harita tabanı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkeze doğru kıvrılan tek hatlı dairesel labirent kanalları'
    },
    visualDescription: 'Chartres katedrali zeminindeki gibi tek girişli, 11 eşmerkezli halkalı geometrik labirent patikası.',
    numerologyConnection: 'Yaşam Yolu 7 (İçsel Hac) ve 4 (Sağlam Yol)',
    astrologyConnection: 'Başak ve Oğlak',
    enneagramConnection: 'Tip 5 & Tip 4',
    visualKeywords: ['chartres labyrinth floor plan', 'unicursal labyrinth linework', 'sacred path to center']
  },
  {
    id: 'sym-heptagram',
    name: 'Heptagram (7 Köşeli Büyücü Yıldızı)',
    category: 'Geometri',
    subcategory: 'Gezegenler Küresi & İlahi Gizem',
    meaning: 'Bölünemez 7 kutsal ilke, 7 klasik gezegen, periler yıldızı ve görünmeyen dünyaların simyasal anahtarı.',
    archetypes: ['Büyücü', 'Gezgin'],
    positiveThemes: ['mistik derinlik', 'yüksek algı', 'astrolojik senkronisite', 'büyüleyici zarafet'],
    shadowThemes: ['anlaşılmazlık', 'dünyadan kopukluk'],
    relatedChakras: [7, 6],
    relatedElements: ['Eter', 'Hava'],
    relatedNumerology: [7],
    relatedAstrology: ['Kova', 'Balık', 'Yay'],
    relatedEnneagram: [5, 7],
    relatedTotemThemes: ['7 sivri uç', 'kesintisiz tek çizgi yıldız', 'gezegenler çemberi'],
    suitableFor: ['Ezoterik çalışmalara ilgi duyan ve 7 sayısının mistik frekansıyla rezonansa girenler'],
    avoidWhen: ['Kaba materyalist, basit 4 köşeli katı yapılar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Star', 'Astrological Sigil', 'Dotwork Accent'],
      bodyPlacements: ['Bilek', 'Ense', 'Önkol Üstü', 'Parmak / El'],
      compositionRole: 'Tepe kılavuz yıldızı veya astrolojik gezegen düğümü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: '7/2 veya 7/3 oranında çizilmiş kesintisiz 7 köşeli yıldız poligonu'
    },
    visualDescription: 'Tek bir hatla çizilen, keskin ve asil 7 sivri köşeli mistik yıldız hatları.',
    numerologyConnection: 'Yaşam Yolu 7 ve Kutsal Heptad',
    astrologyConnection: 'Kova, Balık ve Yay',
    enneagramConnection: 'Tip 5 & Tip 7',
    visualKeywords: ['heptagram seven pointed star', 'faery star sacred geometry', 'elven star linework']
  },
  {
    id: 'sym-ouroboros-geo',
    name: 'Geometrik Ouroboros (Sonsuzluk Aksı)',
    category: 'Geometri',
    subcategory: 'Simyasal Devir & Lemniskat',
    meaning: 'Kendi kuyruğunu yutan döngüsel geometri ve sonsuzluk işareti (Lemniskat); her sonun yeni bir başlangıç olması.',
    archetypes: ['Simyacı', 'Bütünleştirici'],
    positiveThemes: ['sürekli yenilenme', 'zamansızlık', 'öz-tamamlanma', 'sonsuz döngü'],
    shadowThemes: ['aynı hataları tekrarlama döngüsü'],
    relatedChakras: [1, 7],
    relatedElements: ['Ateş', 'Su'],
    relatedNumerology: [8, 0],
    relatedAstrology: ['Akrep', 'Oğlak'],
    relatedEnneagram: [8, 9],
    relatedTotemThemes: ['sonsuzluk sekizlisi', 'kuyruğu ısıran daire', 'matematiksel lemniskat'],
    suitableFor: ['Döngüsel zamanı kavrayıp hayatını sürekli bir üst seviyede yenilemek isteyenler'],
    avoidWhen: ['Tamamen doğrusal ve geçmişi tamamen reddeden temalar'],
    designCompatibility: {
      recommendedStyles: ['Minimalist Geometry', 'Fine Line', 'Moebius Strip Linework'],
      bodyPlacements: ['Bilek', 'Önkol Yan', 'Köprücük Kemiği'],
      compositionRole: 'Bağlayıcı sonsuzluk çerçevesi veya merkez simya düğümü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Möbius şeridi şeklinde kıvrılan çift hatlı geometrik lemniskat'
    },
    visualDescription: 'Geometrik prizmatik çizgilerden inşa edilmiş, kuyruğuyla kenetlenen sonsuzluk halkası.',
    numerologyConnection: 'Yaşam Yolu 8 (Sonsuzluk) ve Tamamlanma',
    astrologyConnection: 'Akrep ve Oğlak',
    enneagramConnection: 'Tip 8 & Tip 9',
    visualKeywords: ['geometric ouroboros', 'infinity lemniscate linework', 'moebius strip sacred geometry']
  },
  {
    id: 'sym-dodecahedron',
    name: 'Dodekahedron (12 Yüzlü Platonik Katı)',
    category: 'Geometri',
    subcategory: 'Eter Elementi & Kozmik Bilinç',
    meaning: 'Platon’un evrenin tamamını tanımladığı 12 beşgen yüzlü kutsal katı; Eter (Kozmos) elementi ve yüksek bilinç.',
    archetypes: ['Kozmik Mimar', 'Bilge'],
    positiveThemes: ['yüksek kozmik vizyon', 'bütünsel uyum', 'ilahi matematik', 'evrensel bağ'],
    shadowThemes: ['aşırı zihinsellik', 'bedenden kopukluk'],
    relatedChakras: [7, 6],
    relatedElements: ['Eter'],
    relatedNumerology: [12, 3],
    relatedAstrology: ['Kova', 'Balık'],
    relatedEnneagram: [5, 1],
    relatedTotemThemes: ['12 beşgen', 'altın oran kenarlar', 'kozmik küre'],
    suitableFor: ['Evrensel bilinci derisinde taşımak ve eterik frekansını yükseltmek isteyenler'],
    avoidWhen: ['Kaba, ağır ve dünyevi çamur temalarında fazla yüce kalabilir'],
    designCompatibility: {
      recommendedStyles: ['Wireframe Sacred Geometry', 'Fine Line Dotwork', 'Isometric 3D'],
      bodyPlacements: ['Önkol', 'Sırt Kürek Kemiği Arası', 'Göğüs Kafesi'],
      compositionRole: 'Merkezi çok boyutlu kristal kafes veya tepe vizyon rozeti',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: '12 adet birbirine kilitlenmiş düzenli beşgenin tel kafes izometrik çizimi'
    },
    visualDescription: '12 adet muntazam beşgen yüzeyin oluşturduğu 3D izometrik tel kafes küre illüzyonu.',
    numerologyConnection: '12 Zodyak Burcu ve Üstat 33',
    astrologyConnection: 'Kova ve Balık (Kozmik Eter)',
    enneagramConnection: 'Tip 5 & Tip 1',
    visualKeywords: ['dodecahedron wireframe', 'sacred geometry platonic solids', 'aether element geometry']
  },
  {
    id: 'sym-icosahedron',
    name: 'İkozahedron (20 Yüzlü Platonik Katı)',
    category: 'Geometri',
    subcategory: 'Su Elementi & Akışkan Dönüşüm',
    meaning: '20 eşkenar üçgenden oluşan Platonik katı; Su elementi, duygusal akışkanlık, esneklik ve dönüşüm.',
    archetypes: ['Şifacı', 'Simyacı'],
    positiveThemes: ['duygusal esneklik', 'akışta kalma', 'kristalize arınma', 'uyum sağlama'],
    shadowThemes: ['duygularda boğulma'],
    relatedChakras: [2],
    relatedElements: ['Su'],
    relatedNumerology: [2, 8],
    relatedAstrology: ['Yengeç', 'Akrep', 'Balık'],
    relatedEnneagram: [4, 9],
    relatedTotemThemes: ['20 eşkenar üçgen', 'su molekülü kafesi', 'akış kristali'],
    suitableFor: ['Duygularını berraklaştırmak ve akışa teslim olarak güçlenmek isteyenler'],
    avoidWhen: ['Sert ve kırılmaz katılık aranan monolitik tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line 3D', 'Dotwork Shading', 'Minimalist Polyhedron'],
      bodyPlacements: ['Önkol İç', 'Kaburga Yanı', 'Bilek'],
      compositionRole: 'Su dalgalarını veya lotus merkezini taşıyan geometrik çekirdek',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: '20 adet eşkenar üçgenin birleşimiyle oluşan dışbükey kristal çokgen'
    },
    visualDescription: 'İncecik üçgen yüzeylerin oluşturduğu 3D su kristali ikozahedron tel kafesi.',
    numerologyConnection: 'Yaşam Yolu 2 (Su) ve 8',
    astrologyConnection: 'Yengeç, Akrep ve Balık (Su Üçlüsü)',
    enneagramConnection: 'Tip 4 & Tip 9',
    visualKeywords: ['icosahedron water element', 'platonic solid icosahedron linework', 'crystal polyhedron fine line']
  },
  {
    id: 'sym-octahedron',
    name: 'Oktahedron (8 Yüzlü Platonik Katı)',
    category: 'Geometri',
    subcategory: 'Hava Elementi & Zihinsel Denge',
    meaning: 'Taban tabana yapışmış iki piramit (8 eşkenar üçgen); Hava elementi, zihinsel denge, çift yönlü ayna ve tarafsızlık.',
    archetypes: ['Yargıç', 'Gözlemci'],
    positiveThemes: ['zihinsel berraklık', 'tarafsız bakış', 'çift yönlü denge', 'sezgisel akıl'],
    shadowThemes: ['aşırı soğukluk', 'duygulardan kopma'],
    relatedChakras: [4, 5],
    relatedElements: ['Hava'],
    relatedNumerology: [4, 8],
    relatedAstrology: ['İkizler', 'Terazi', 'Kova'],
    relatedEnneagram: [5, 1],
    relatedTotemThemes: ['çift piramit', 'elmas kristali', 'hava kafesi'],
    suitableFor: ['Her iki tarafı da eşit tartan objektif zihin ve dengeli kalp arayanlar'],
    avoidWhen: ['Tamamen tutkulu, ateşli ve fevri patlamalar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Prism Reflection', 'Minimalist Vector'],
      bodyPlacements: ['Önkol', 'Köprücük Kemiği Ortası', 'Omurga'],
      compositionRole: 'Merkezi denge elması veya ufuk ekseni düğümü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkezi kare tabanlı iki zıt piramitin elmas silueti'
    },
    visualDescription: 'Elmas formunda üst üste duran iki piramitin oluşturduğu 8 yüzlü hava kristali.',
    numerologyConnection: 'Yaşam Yolu 4 ve 8 (Denge Eksenleri)',
    astrologyConnection: 'Terazi, İkizler ve Kova (Hava Triadı)',
    enneagramConnection: 'Tip 5 & Tip 1',
    visualKeywords: ['octahedron air element', 'diamond octahedron sacred geometry', 'double pyramid linework']
  },
  {
    id: 'sym-hexahedron',
    name: 'Küp & Hekzahedron (Toprak Elementi)',
    category: 'Geometri',
    subcategory: 'Toprak Elementi & Sarsılmaz Temel',
    meaning: '6 kare yüzlü mükemmel küp; Toprak elementi, sarsılmaz temel, maddi dünyaya sağlam basma ve ilahi nizam.',
    archetypes: ['Mimar', 'Hükümdar'],
    positiveThemes: ['sağlam zemin', 'güvenilirlik', 'maddi başarı', 'sarsılmazlık'],
    shadowThemes: ['katılık', 'inatçılık', 'ağırkanlılık'],
    relatedChakras: [1],
    relatedElements: ['Toprak'],
    relatedNumerology: [4, 22],
    relatedAstrology: ['Boğa', 'Başak', 'Oğlak'],
    relatedEnneagram: [1, 8],
    relatedTotemThemes: ['4x4 temel', 'küp taşı', 'sarsılmaz kaide'],
    suitableFor: ['Hayatında sağlam bir temel kurmak, uçuşan enerjilerini topraklamak isteyenler'],
    avoidWhen: ['Hafif, uçucu ve sınır tanımayan rüzgar temalarında fazla ağır kalabilir'],
    designCompatibility: {
      recommendedStyles: ['Isometric Linework', 'Fine Line Architectural', 'Dotwork Shading'],
      bodyPlacements: ['Ayak Bileği Üstü', 'Önkol Kaidesi', 'Sırt Alt Omurga'],
      compositionRole: 'Tüm kompozisyonun üzerine oturduğu sağlam kaide veya zemin taşı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: '6 eş karenin oluşturduğu izometrik küp perspektifi'
    },
    visualDescription: 'Kusursuz açılarla çizilmiş 3D izometrik küp, ince kılavuz eksen çizgileri.',
    numerologyConnection: 'Yaşam Yolu 4 ve Üstat 22 (Büyük Mimar)',
    astrologyConnection: 'Boğa, Başak ve Oğlak (Toprak)',
    enneagramConnection: 'Tip 1 & Tip 8',
    visualKeywords: ['cube platonic solid', 'earth element hexahedron', 'isometric cube sacred geometry']
  },
  {
    id: 'sym-penrose',
    name: 'Penrose Karo Karoları (Aperiyodik Geometri)',
    category: 'Geometri',
    subcategory: 'Sonsuz Düzen & Deterministik Kaos',
    meaning: 'Hiçbir zaman kendini birebir tekrar etmeyen ama sonsuza kadar kusursuz bir düzenle devam eden 5 katlı simetri.',
    archetypes: ['Kâşif', 'Simyacı'],
    positiveThemes: ['benzersizlik', 'kaos içindeki gizli nizam', 'sonsuz olasılık', 'özgün ritim'],
    shadowThemes: ['karmaşada kaybolma'],
    relatedChakras: [6, 7],
    relatedElements: ['Eter', 'Hava'],
    relatedNumerology: [5, 11],
    relatedAstrology: ['Kova', 'İkizler'],
    relatedEnneagram: [5, 7],
    relatedTotemThemes: ['aperiyodik döşeme', 'beşli simetri', 'altın oran eşkenar dörtgenler'],
    suitableFor: ['Kalıplara sığmayan, hayatında hem yüksek düzeni hem de eşsiz özgünlüğü arayanlar'],
    avoidWhen: ['Klasik, düz çizgili veya monoton sıradan minimal işler'],
    designCompatibility: {
      recommendedStyles: ['Mathematical Fine Line', 'Dotwork Pattern', 'Abstract Geometric Sleeve'],
      bodyPlacements: ['Önkol Boydan Boya', 'Uyluk', 'Sırt'],
      compositionRole: 'Genişleyen arka plan zemin deseni veya dinamik doku',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İki farklı altın oran romboidin aperiyodik olarak birbirine kilitlenmesi'
    },
    visualDescription: 'İki farklı altın oran eşkenar dörtgenin sonsuz çeşitlilikte birleştiği hipnotik döşeme deseni.',
    numerologyConnection: 'Yaşam Yolu 5 ve 11',
    astrologyConnection: 'Kova ve İkizler',
    enneagramConnection: 'Tip 5 & Tip 7',
    visualKeywords: ['penrose tiling linework', 'aperiodic sacred geometry', 'golden ratio rhombuses pattern']
  },
  {
    id: 'sym-tesseract',
    name: 'Tesseract (4 Boyutlu Hiperküp)',
    category: 'Geometri',
    subcategory: 'Yüksek Boyutlu Vizyon',
    meaning: '3 boyutlu uzayın sınırlarını aşan 4. boyut küpü; algının kapılarını aralama, illüzyonların ötesi ve yüksek idrak.',
    archetypes: ['Mistik', 'Kâşif'],
    positiveThemes: ['yüksek boyutlu kavrayış', 'sınırları aşma', 'kuantum zihin', 'derin vizyon'],
    shadowThemes: ['gerçeklik algısının sarsılması'],
    relatedChakras: [6, 7],
    relatedElements: ['Eter'],
    relatedNumerology: [8, 11],
    relatedAstrology: ['Kova', 'Akrep'],
    relatedEnneagram: [5],
    relatedTotemThemes: ['iç içe küpler', 'köşeleri birleştiren kirişler', 'hiper uzay'],
    suitableFor: ['Sıradan dünyanın sınırlarını aşan derin düşünürler ve vizyonerler'],
    avoidWhen: ['Tamamen geleneksel, nostaljik ve pastoral doğa temaları'],
    designCompatibility: {
      recommendedStyles: ['Hyper-Minimalist Linework', 'Cyber-Geometric', 'Fine Line 3D'],
      bodyPlacements: ['Önkol', 'Pazu Yanı', 'Kürek Kemiği'],
      compositionRole: 'Fütüristik odak noktası veya kuantum zihin mührü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dış büyük küpün içindeki küçük küpe 8 köşeden bağlandığı şeffaf projeksiyon'
    },
    visualDescription: 'Biri diğerinin içinde duran iki küpün köşelerinin diyagonal hatlarla bağlandığı 4D hiperküp projeksiyonu.',
    numerologyConnection: 'Yaşam Yolu 8 ve Üstat 11',
    astrologyConnection: 'Kova ve Akrep',
    enneagramConnection: 'Tip 5 (Araştırmacı Vizyoner)',
    visualKeywords: ['tesseract 4d hypercube', 'fourth dimension geometry linework', 'quantum cube sacred geometry']
  },
  {
    id: 'sym-unicursal-hexagram',
    name: 'Tek Hatlı Heksagram (Unicursal Hexagram)',
    category: 'Geometri',
    subcategory: 'Kesintisiz Altı Köşeli Yıldız & Güneş Çiçeği',
    meaning: 'Kalemi kağıttan kaldırmadan tek bir kesintisiz çizgiyle çizilen 6 köşeli yıldız; mikrokozmos ile makrokozmosun kesintisiz birliği ve ilahi koruma.',
    archetypes: ['Mistik', 'Simyacı'],
    positiveThemes: ['kesintisiz akış', 'ilahi koruma', 'güneş-ay birliği', 'bütünsel mühür'],
    shadowThemes: ['kendini fazla gizleme'],
    relatedChakras: [4, 6],
    relatedElements: ['Ateş', 'Su', 'Hava', 'Toprak'],
    relatedNumerology: [6, 1],
    relatedAstrology: ['Güneş', 'Aslan', 'Kova'],
    relatedEnneagram: [5, 1],
    relatedTotemThemes: ['tek hatlı altıgen', 'merkez gül detayı', 'geometrik düğüm'],
    suitableFor: ['İçindeki zıtlıkları kesintisiz bir çizgide birleştirmek ve güçlü bir koruyucu mühür isteyenler'],
    avoidWhen: ['Dağınık ve rastgele soyut kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Sacred Geometry Fine Line', 'Dotwork', 'Architectural Linework'],
      bodyPlacements: ['Göğüs Kafesi / Sternum', 'Üst Sırt Omurga', 'Önkol İç'],
      compositionRole: 'Merkezi yüksek frekans jeneratörü veya kalp çakrası kilidi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Tek bir kesintisiz çizgiyle çizilmiş altı köşeli ilmek'
    },
    visualDescription: 'Tek bir hat üzerinden çizilen, merkezinde dört yapraklı çiçek oluşturan kesintisiz heksagram yıldızı.',
    numerologyConnection: 'Yaşam Yolu 6 ve 1',
    astrologyConnection: 'Aslan ve Kova',
    enneagramConnection: 'Tip 5 & Tip 1',
    visualKeywords: ['unicursal hexagram linework tattoo', 'sacred geometry continuous star', 'thelema sacred hexagram']
  },
  {
    id: 'sym-fruit-of-life',
    name: 'Yaşam Meyvesi (Fruit of Life)',
    category: 'Geometri',
    subcategory: '13 Kutsal Küre & Kozmik Anahtar',
    meaning: 'Yaşam Çiçeği\'nin kalbinden doğan 13 mükemmel çember; evrenin tüm fiziksel ve moleküler yapı taşlarının (Platonik Cisimler) anahtarı.',
    archetypes: ['Mimar', 'Yaratıcı'],
    positiveThemes: ['yaratımın tamamlanması', 'yapısal mükemmellik', 'kozmik şablon'],
    shadowThemes: ['katı mükemmeliyetçilik'],
    relatedChakras: [6, 7],
    relatedElements: ['Eter', 'Bütün Elementler'],
    relatedNumerology: [4, 13, 22],
    relatedAstrology: ['Oğlak', 'Kova'],
    relatedEnneagram: [1, 5],
    relatedTotemThemes: ['13 eşit çember', 'kadim plan', 'formların anası'],
    suitableFor: ['Hayatında sağlam temelli, mükemmel orantılı ve sarsılmaz bir düzen inşa etmek isteyenler'],
    avoidWhen: ['Dağınık ve rastgele soyut kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Precision Dotwork', 'Fine Line Geometry', 'Sacred Line Matrix'],
      bodyPlacements: ['Sırt Merkez', 'Önkol', 'Uyluk'],
      compositionRole: 'Evrensel altyapı matrisi ve arkada duran düzen mimarisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Düzgün altıgen doğrultusunda sıralanan 13 teğet çember şablonu'
    },
    visualDescription: 'Yedi çemberli Yaşam Tohumu\'nun genişleyerek 13 simetrik çembere ulaştığı kutsal geometrik form.',
    numerologyConnection: 'Yaşam Yolu 4 ve Üstat 22',
    astrologyConnection: 'Oğlak ve Kova',
    enneagramConnection: 'Tip 1 & Tip 5',
    visualKeywords: ['fruit of life sacred geometry', '13 circles matrix tattoo', 'metatron seed framework']
  },
  {
    id: 'sym-mobius-strip',
    name: 'Möbius Şeridi (Möbius Strip)',
    category: 'Geometri',
    subcategory: 'Tek Boyutlu Sonsuzluk & İç-Dış Birliği',
    meaning: 'Yalnızca tek bir yüzeyi ve tek bir kenarı olan topolojik şerit; iç dünya ile dış dünyanın birliği, sonsuz tekillik ve yanılsamaların ötesi.',
    archetypes: ['Simyacı', 'Bütünleştirici'],
    positiveThemes: ['iç-dış birliği', 'sonsuz devamlılık', 'zıtlıkların illüzyonu', 'tamamlanmışlık'],
    shadowThemes: ['kendi döngüsünde sıkışıp kalma'],
    relatedChakras: [4, 6],
    relatedElements: ['Eter', 'Hava'],
    relatedNumerology: [0, 8],
    relatedAstrology: ['Kova', 'Balık'],
    relatedEnneagram: [9, 5],
    relatedTotemThemes: ['bükümlü şerit', 'tek yüzeyli sonsuzluk', 'sürekli yürüyüş'],
    suitableFor: ['Kendi iç dünyası ile dış yaşamı arasında ayrım kalmadığını hisseden, bütüncül düşünenler'],
    avoidWhen: ['Durgun, statik ve tamamen köşeli yapılar'],
    designCompatibility: {
      recommendedStyles: ['3D Minimalist Linework', 'Optical Illusion Geometry', 'Fine Line Shading'],
      bodyPlacements: ['Bilek Çevresi', 'Önkol İç', 'Ense'],
      compositionRole: 'Sonsuz döngüsel çerçeve veya bileklik halkası',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Bir yarım tur bükülmüş sonsuzluk şeridi konturu'
    },
    visualDescription: 'Bükülerek kendi içine bağlanan, tek bir kesintisiz yüzey oluşturan zarif 3D Möbius halkası.',
    numerologyConnection: 'Yaşam Yolu 8 ve 0',
    astrologyConnection: 'Kova ve Balık',
    enneagramConnection: 'Tip 9 & Tip 5',
    visualKeywords: ['mobius strip tattoo linework', 'infinity loop 3d geometry', 'topological sacred geometry']
  },
  {
    id: 'sym-golden-spiral-nautilus',
    name: 'Nautilus & Altın Spiral (Golden Spiral Vortex)',
    category: 'Geometri',
    subcategory: 'Logaritmik Büyüme & Kusursuz Oran',
    meaning: 'Nautilus kabuğundaki logaritmik altın spiral; büyürken orantısını ve özünü hiç kaybetmeyen kusursuz evrim ve içten dışa genişleme.',
    archetypes: ['Mimar', 'Evrimleşen Ruh'],
    positiveThemes: ['doğal büyüme', 'özünü koruyarak genişleme', 'altın oran zarafeti', 'merkezden evrene'],
    shadowThemes: ['sonsuz genişlemede kaybolma'],
    relatedChakras: [4, 6],
    relatedElements: ['Su', 'Eter'],
    relatedNumerology: [1, 6, 8],
    relatedAstrology: ['Yengeç', 'Boğa'],
    relatedEnneagram: [4, 7],
    relatedTotemThemes: ['nautilus odacıkları', 'altın dikdörtgenler', 'içten dışa açılan kabuk'],
    suitableFor: ['Hayatında olgunlaşıp büyürken kendi köklerine ve asaletine sadık kalanlar'],
    avoidWhen: ['Sert köşeli ve askeri katı yapılar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Golden Ratio', 'Fibonacci Dotwork', 'Architectural Shell'],
      bodyPlacements: ['Önkol', 'Kürek Kemiği', 'Kaburga'],
      compositionRole: 'Dinamik sarmal büyüme aksı veya kompozisyon odağı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Altın dikdörtgenler dizisi içine oturan logaritmik eğri yayı'
    },
    visualDescription: 'İç odacıkları altın oran kareleriyle çizilmiş, merkezden dışa kusursuz kavisle genişleyen Nautilus spirali.',
    numerologyConnection: 'Fibonacci ve Altın Sayı Phi (1.618)',
    astrologyConnection: 'Yengeç ve Boğa',
    enneagramConnection: 'Tip 4 & Tip 7',
    visualKeywords: ['golden spiral nautilus tattoo', 'fibonacci shell sacred geometry', 'logarithmic spiral linework']
  },
  {
    id: 'sym-ouroboros-geometry',
    name: 'Geometrik Ouroboros (Geometric Ouroboros)',
    category: 'Geometri',
    subcategory: 'Sonsuz Döngü & Kendi Kendini Yaratan',
    meaning: 'Kendi kuyruğunu ısıran geometrik yılan/ejderha halkası; başlangıç ve sonun birliği, yıkım ve yeniden yaratımın ebedi çemberi.',
    archetypes: ['Simyacı', 'Yeniden Doğan'],
    positiveThemes: ['ebedi yenilenme', 'döngüsel bilgelik', 'kendi kendine yetme', 'bütünlük'],
    shadowThemes: ['kendi kuyruğunda takılıp kalma'],
    relatedChakras: [1, 2, 7],
    relatedElements: ['Ateş', 'Toprak', 'Su'],
    relatedNumerology: [0, 8, 9],
    relatedAstrology: ['Akrep', 'Oğlak'],
    relatedEnneagram: [8, 4],
    relatedTotemThemes: ['dairesel yılan', 'sonsuzluk düğümü', 'kuyruk yutma'],
    suitableFor: ['Büyük krizleri aşıp her defasında kendini sıfırdan ve daha güçlü yaratanlar'],
    avoidWhen: ['Düz çizgisel ve sonlu bir hedef arayanlar'],
    designCompatibility: {
      recommendedStyles: ['Etching / Gravür', 'Sacred Line Blackwork', 'Fine Line Geometric'],
      bodyPlacements: ['Önkol Çevresi (Bileklik/Manşet)', 'Sternum', 'Omuz'],
      compositionRole: 'Ana tasarımı çevreleyen koruyucu ve birleştirici dış halka',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Tek bir Möbius şeridi veya geometrik pürüzsüz halka konturu'
    },
    visualDescription: 'Sadeleştirilmiş keskin geometrik pullara sahip, kendi kuyruğunu ısıran kusursuz dairesel Ouroboros.',
    numerologyConnection: 'Yaşam Yolu 8 ve 0',
    astrologyConnection: 'Akrep ve Oğlak',
    enneagramConnection: 'Tip 8 & Tip 4',
    visualKeywords: ['geometric ouroboros linework', 'snake eating tail circular tattoo', 'alchemical cycle geometry']
  },
  {
    id: 'sym-pentagram-golden',
    name: 'Altın Oran Pentagramı (Golden Pentagram)',
    category: 'Geometri',
    subcategory: 'Mikrokozmos & Beş Element',
    meaning: 'İnsan bedeninin (Da Vinci Vitruvius) ve doğanın 5 elementinin (Toprak, Su, Ateş, Hava, Eter) altın oranla kesiştiği koruyucu yıldız.',
    archetypes: ['Muhafız', 'Büyücü'],
    positiveThemes: ['beş element uyumu', 'insanın kutsal oranları', 'güçlü koruma kalkanı', 'irade'],
    shadowThemes: ['güç zehirlenmesi'],
    relatedChakras: [3, 4, 6],
    relatedElements: ['Bütün 5 Element'],
    relatedNumerology: [5, 1],
    relatedAstrology: ['Koç', 'Aslan', 'Kova'],
    relatedEnneagram: [8, 1],
    relatedTotemThemes: ['altın oran kesişimleri', 'beş uçlu simetri', 'daire içine hapsedilmiş yıldız'],
    suitableFor: ['Kişisel iradesini beş elementin dengesiyle hizalayıp güçlü bir koruma isteyenler'],
    avoidWhen: ['Yalnızca pasif veya kaderci yaklaşımlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Minimalist', 'Sacred Line Art', 'Geometric Dotwork'],
      bodyPlacements: ['Bilek İç', 'Ense Altı', 'Önkol Dış'],
      compositionRole: 'Merkezi koruma mührü veya element köprüleri bağlantısı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Kesişen beş altın oran çizgisi ve çevreleyen tek daire'
    },
    visualDescription: 'Her bir çizgisi altın oranla bölünen, tek hatla çizilmiş beş köşeli yıldız ve ince dış çemberi.',
    numerologyConnection: 'Yaşam Yolu 5 ve 1',
    astrologyConnection: 'Koç ve Kova',
    enneagramConnection: 'Tip 8 & Tip 1',
    visualKeywords: ['golden ratio pentagram', 'sacred pentacle linework', 'five elements star tattoo design']
  }
];
