import { SymbolLibraryItem } from '../../types';

export const MYTHOLOGY_SYMBOLS: SymbolLibraryItem[] = [
  {
    id: 'sym-hekate',
    name: 'Hekate / Üçlü Tanrıça (Hecate Triple Moon)',
    category: 'Mitoloji',
    subcategory: 'Kavşaklar & Ayın Evreleri',
    meaning: 'Kavşakların rehberi, anahtar tutan, büyü, ayın evreleri, dişil gizem ve gölge ile aydınlığın rehberi.',
    archetypes: ['Büyücü', 'Kavşak Rehberi', 'Gölge Muhafızı'],
    positiveThemes: ['sezgisel kavrayış', 'kavşakta doğru seçim', 'dişil güç', 'gece bilgeliği'],
    shadowThemes: ['karanlıkta kaybolma korkusu', 'aşırı gizemcilik'],
    relatedChakras: [6, 7],
    relatedElements: ['Su', 'Eter'],
    relatedNumerology: [7, 2, 3],
    relatedAstrology: ['Akrep', 'Yengeç'],
    relatedEnneagram: [4, 6],
    relatedTotemThemes: ['üçlü ay', 'meşale ve anahtar', 'kavşak köpekleri'],
    suitableFor: ['Hayatında kritik bir yol ayrımında olan ve sezgisel rehberlik arayanlar'],
    avoidWhen: ['Yalnızca açık, saf güneşsel ve gölgesiz naif yaklaşımlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Gothic Mystical', 'Dotwork Lunar'],
      bodyPlacements: ['Sırt Üst', 'Önkol İç', 'Kaburga', 'Köprücük Kemiği'],
      compositionRole: 'Tepe kılavuz tacı veya merkezi ay sembolü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Büyüyen hilal, dolunay dairesi ve küçülen hilalden oluşan üçlü ay glifi'
    },
    visualDescription: 'Hilal-dolunay-hilal kombinasyonu, ortada antik anahtar ve iki yana uzanan meşale alevleri.',
    numerologyConnection: 'Yaşam Yolu 7 ve 2',
    astrologyConnection: 'Akrep ve Yengeç',
    enneagramConnection: 'Tip 4w5 & Tip 6',
    visualKeywords: ['triple moon goddess symbol', 'hecate torch and key', 'three faces silhouette', 'lunar phases']
  },
  {
    id: 'sym-anubis',
    name: 'Anubis & Kalp Tartısı (Anubis & Feather of Maat)',
    category: 'Mitoloji',
    subcategory: 'Ruhların Rehberi & Hakikat Terazisi',
    meaning: 'Ruhların karanlıktan ışığa rehberi (Psikopomp), Maat tüyüyle kalbin tartılması, mutlak dürüstlük ve vicdan.',
    archetypes: ['Rehber', 'Yargıç', 'Muhafız'],
    positiveThemes: ['vicdan huzuru', 'korkusuz geçiş', 'mutlak adalet', 'derin sadakat'],
    shadowThemes: ['aşırı suçluluk duygusu', 'kendini acımasızca yargılama'],
    relatedChakras: [4, 1],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [8, 1],
    relatedAstrology: ['Terazi', 'Akrep'],
    relatedEnneagram: [1, 8],
    relatedTotemThemes: ['çakal başı', 'maat tüyü', 'altın terazi'],
    suitableFor: ['Kendi vicdanıyla barışık yaşayan, hakikat ve adalet arayışında olanlar'],
    avoidWhen: ['Hafif, tasasız ve sorumsuz oyuncu temalar'],
    designCompatibility: {
      recommendedStyles: ['Egyptian Linework', 'Black & Grey', 'Fine Line Engraving'],
      bodyPlacements: ['Önkol Dış', 'Pazu', 'Baldır', 'Sırt Kürek Kemiği'],
      compositionRole: 'Merkezi asil figür veya adalet terazisi armatürü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dengeli terazi yatay kirişi, merkez dik aks ve askı üçgenleri'
    },
    visualDescription: 'Asil çakal başlı Anubis profili, elinde ankh asası ve Maat tüyünün tartıldığı simetrik terazi.',
    numerologyConnection: 'Yaşam Yolu 8 ve 1',
    astrologyConnection: 'Terazi ve Akrep',
    enneagramConnection: 'Tip 1 (Adalet) & Tip 8',
    visualKeywords: ['jackal headed anubis', 'scale of truth weighing feather', 'egyptian hieroglyphs', 'gold and black anubis']
  },
  {
    id: 'sym-prometheus',
    name: 'Prometheus Meşalesi (Prometheus Fire)',
    category: 'Mitoloji',
    subcategory: 'Kutsal Ateş & İsyankar Bilgelik',
    meaning: 'İnsanlık için tanrılardan çalınan kutsal ateş; aydınlanma, bedel ödemekten korkmayan cesaret ve özgür irade.',
    archetypes: ['Asi', 'Kahraman', 'Yaratıcı'],
    positiveThemes: ['aydınlanma kıvılcımı', 'cesur vizyon', 'bağımsız irade', 'yenilik'],
    shadowThemes: ['bedel ödeme korkusu', 'aşırı kural tanımazlık'],
    relatedChakras: [3, 6],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [1, 5],
    relatedAstrology: ['Kova', 'Koç'],
    relatedEnneagram: [8, 7],
    relatedTotemThemes: ['meşale alevi', 'kırılan zincirler', 'ışık taşıyıcı'],
    suitableFor: ['Kendi yolunu çizen, tabuları yıkan ve topluma ışık tutan vizyonerler'],
    avoidWhen: ['Tamamen geleneksel kurallara uymak ve boyun eğmek istenen süreçler'],
    designCompatibility: {
      recommendedStyles: ['Dynamic Linework', 'Neo-Classical', 'Etching'],
      bodyPlacements: ['Önkol İç', 'Pazu', 'Omurga'],
      compositionRole: 'Merkezi dikey meşale veya yükselen alev hatları',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Yukarı doğru yükselen sivri alev üçgenleri ve kırık halka vektörleri'
    },
    visualDescription: 'Antik meşale içinden göğe yükselen spiral alevler ve alt kaidede çözülmüş zincir halkaları.',
    numerologyConnection: 'Yaşam Yolu 1 ve 5',
    astrologyConnection: 'Kova ve Koç',
    enneagramConnection: 'Tip 8w7 & Tip 7',
    visualKeywords: ['flaming torch of wisdom', 'hands holding sacred fire', 'rebel titan myth']
  },
  {
    id: 'sym-isis-wings',
    name: 'İsis & Koruyucu Kanatları (Wings of Isis)',
    category: 'Mitoloji',
    subcategory: 'Şifa Anası & Yeniden Diriliş',
    meaning: 'Parçalanmış olanı bir araya getirme gücü, sınırsız anne şefkati, koruyucu kanatlar ve ilahi sihir.',
    archetypes: ['Büyük Anne', 'Şifacı', 'Büyücü'],
    positiveThemes: ['kapsayıcı koruma', 'kırılan parçaları onarma', 'sevgiyle şifa', 'yeniden doğuş'],
    shadowThemes: ['aşırı fedakarlık', 'kendini tüketme'],
    relatedChakras: [4, 7],
    relatedElements: ['Hava', 'Su'],
    relatedNumerology: [6, 2],
    relatedAstrology: ['Yengeç', 'Başak', 'Balık'],
    relatedEnneagram: [2, 9],
    relatedTotemThemes: ['açılmış kanatlar', 'ankh anahtarı', 'güneş diski ve boynuzlar'],
    suitableFor: ['Büyük bir travmayı onarıp parçalarını birleştiren ve koruyucu zarafet isteyenler'],
    avoidWhen: ['Sert, kaba ve mekanik saldırgan temalar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Egyptian', 'Classical Wings', 'Micro Detail'],
      bodyPlacements: ['Göğüs Altı (Underbust)', 'Sırt Kürek Kemikleri Arası', 'Köprücük Kemiği'],
      compositionRole: 'Tasarımı iki yana saran geniş koruyucu kanat çerçevesi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İki yana simetrik açılan kavisli tüy yayları ve merkez daire'
    },
    visualDescription: 'İki yana asilce açılmış tüylü İsis kanatları, merkezde güneş diski ve ankh tılsımı.',
    numerologyConnection: 'Yaşam Yolu 6 (Koşulsuz Sevgi) ve 2',
    astrologyConnection: 'Yengeç ve Başak',
    enneagramConnection: 'Tip 2 & Tip 9',
    visualKeywords: ['winged isis goddess linework', 'egyptian protective wings tattoo', 'sacred isis ankh']
  },
  {
    id: 'sym-eye-of-horus',
    name: 'Horus’un Gözü & Wadjet (Eye of Horus)',
    category: 'Mitoloji',
    subcategory: 'Bütünlük & Kutsal Koruma',
    meaning: 'Parçalanıp tekrar birleşen kutsal göz (1/2, 1/4, 1/8 oranları); ilahi koruma, sağlık, sezgi ve yenilmezlik.',
    archetypes: ['Gözlemci', 'Muhafız', 'Şifacı'],
    positiveThemes: ['tüm illüzyonları gören bakış', 'sağlık ve bütünlük', 'nazar kalkanı', 'sezgisel uyanış'],
    shadowThemes: ['sürekli tetikte olma ve paranoya'],
    relatedChakras: [6],
    relatedElements: ['Güneş / Ateş', 'Hava'],
    relatedNumerology: [1, 7],
    relatedAstrology: ['Koç', 'Aslan'],
    relatedEnneagram: [6, 8],
    relatedTotemThemes: ['şahin gözü', 'gözyaşı damlası spirali', 'güneş bakışı'],
    suitableFor: ['Kem gözlerden korunmak, sezgilerini keskinleştirmek ve sağlığını mühürlemek isteyenler'],
    avoidWhen: ['Aşırı soyut ve işaretsiz minimal arayışlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Egyptian', 'Geometric Linework', 'Minimalist Amulet'],
      bodyPlacements: ['Ense', 'Bilek İçi', 'Önkol', 'Köprücük Altı'],
      compositionRole: 'Merkezi koruma gözü veya tepe vizyon mührü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Üst kaş yayı, badem göz ve altındaki matematiksel spiral uzantı'
    },
    visualDescription: 'Karakteristik şahin gözü hatları, altından sarkan damla spirali ve geometrik altın oran oranları.',
    numerologyConnection: 'Yaşam Yolu 1 (Lider Göz) ve 7 (İçsel Sezgi)',
    astrologyConnection: 'Aslan (Solar Güç) ve Koç',
    enneagramConnection: 'Tip 6 & Tip 8',
    visualKeywords: ['eye of horus wadjet linework', 'egyptian sacred eye protective tattoo', 'all seeing falcon eye']
  },
  {
    id: 'sym-athena-shield',
    name: 'Athena & Bilgelik Kalkanı (Aegis of Athena)',
    category: 'Mitoloji',
    subcategory: 'Stratejik Akıl & Adil Savunma',
    meaning: 'Öfkesiz strateji, adil akıl, dokunulmaz savunma kalkanı (Aegis), zeka ve bilgelik.',
    archetypes: ['Savaşçı Kraliçe', 'Stratejist', 'Bilge'],
    positiveThemes: ['soğukkanlı akıl', 'sarsılmaz savunma', 'adalet', 'stratejik zafer'],
    shadowThemes: ['aşırı duygusuzluk', 'sürekli taktiksel düşünme'],
    relatedChakras: [5, 6],
    relatedElements: ['Hava', 'Toprak'],
    relatedNumerology: [1, 5, 8],
    relatedAstrology: ['Başak', 'Oğlak', 'Kova'],
    relatedEnneagram: [1, 5],
    relatedTotemThemes: ['aegis kalkanı', 'baykuş tüyü', 'mızrak ucu'],
    suitableFor: ['Duygusal tepkiler yerine stratejik akılla hayatını yönetmek isteyen liderler'],
    avoidWhen: ['Yalnızca duygusal taşkınlık ve saf içgüdüsel eylem arzulanan durumlar'],
    designCompatibility: {
      recommendedStyles: ['Classical Hellenic', 'Fine Line Armor', 'Geometric Shield'],
      bodyPlacements: ['Omuz Başı', 'Önkol Dış', 'Sırt Kürek Kemiği'],
      compositionRole: 'Koruyucu dairesel armatür veya merkez kalkan motifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Eşmerkezli daireler, merkezde medusa düğümü ve çapraz mızrak aksı'
    },
    visualDescription: 'Kabartmalı antik Yunan kalkanı, ortasında koruyucu motif ve arkasında çapraz mızrak çizgisi.',
    numerologyConnection: 'Yaşam Yolu 1 ve 5 (Stratejik Zeka)',
    astrologyConnection: 'Başak ve Oğlak',
    enneagramConnection: 'Tip 1 & Tip 5',
    visualKeywords: ['athena aegis shield', 'greek goddess armor linework', 'owl and spear athena tattoo']
  },
  {
    id: 'sym-hermes-caduceus',
    name: 'Hermes Kadüse & Kanatlı Asa (Caduceus of Hermes)',
    category: 'Mitoloji',
    subcategory: 'Simya & Zıt Kutupların Dengesi',
    meaning: 'Birbirine sarılan iki yılan (Kundalini / DNA), kanatlı asa; haberleşme, simya, şifa ve zıtların uzlaşması.',
    archetypes: ['Haberci', 'Simyacı', 'Gezgin'],
    positiveThemes: ['hızlı kavrayış', 'kutupların barışması', 'şifa akışı', 'iletişim gücü'],
    shadowThemes: ['kurnazlık', 'yüzeysellik'],
    relatedChakras: [5, 6],
    relatedElements: ['Hava'],
    relatedNumerology: [5, 2],
    relatedAstrology: ['İkizler', 'Başak'],
    relatedEnneagram: [7, 3],
    relatedTotemThemes: ['çift yılan sarılışı', 'kanatlı tepe', 'merkezi asa omurgası'],
    suitableFor: ['İletişim, ticaret, simya ve zıt kutuplar arasında hızlı köprü kurmak isteyenler'],
    avoidWhen: ['Hareketsiz, durağan ve ağır köklenme arayışları'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Caduceus', 'Alchemical Engraving', 'Geometric DNA'],
      bodyPlacements: ['Omurga Boyunca', 'Önkol', 'Baldır'],
      compositionRole: 'Merkezi dikey omurga veya yükselen akış çizgisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkezi dikey doğru etrafında 3 kez kesişen çift sinüs dalgası ve tepe kanatları'
    },
    visualDescription: 'Merkezi asaya sarılmış simetrik iki yılan, tepede açılmış iki küçük zarif kanat.',
    numerologyConnection: 'Yaşam Yolu 5 (Hareket ve Zeka) ve 2 (İkili Denge)',
    astrologyConnection: 'İkizler ve Başak (Merkür / Hermes)',
    enneagramConnection: 'Tip 7 & Tip 3',
    visualKeywords: ['caduceus staff fine line', 'hermes wings and snakes', 'alchemical caduceus tattoo']
  },
  {
    id: 'sym-shahmaran',
    name: 'Şahmaran (Anadolu Yılanlar Şahı)',
    category: 'Mitoloji',
    subcategory: 'Kadim Anadolu Şifası & Fedakarlık',
    meaning: 'Yarısı insan yarısı yılan; yeryüzünün ve bitkilerin tüm şifalı sırlarını bilen, sadakat ve bilge fedakarlık.',
    archetypes: ['Şifacı', 'Bilge Kraliçe', 'Muhafız'],
    positiveThemes: ['tüm bitkilerin sırrı', 'koşulsuz şifa', 'sadakat', 'derin içsel zarafet'],
    shadowThemes: ['ihanete uğrama korkusu', 'aşırı sır saklama'],
    relatedChakras: [4, 6],
    relatedElements: ['Toprak', 'Su'],
    relatedNumerology: [7, 9],
    relatedAstrology: ['Akrep', 'Boğa'],
    relatedEnneagram: [2, 4],
    relatedTotemThemes: ['taçlı yılan gövdesi', 'yedi başlı pullar', 'şifalı otlar'],
    suitableFor: ['Anadolu köklerine bağlı, tıp, şifa ve fedakarlık erdemini taşıyanlar'],
    avoidWhen: ['Yılan figüründen hoşlanmayan veya yalnızca Batı klasik mitolojisi arayanlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Anatolian', 'Ornamental Line Art', 'Botanical Fusion'],
      bodyPlacements: ['Önkol İç', 'Sırt Omurga', 'Uyluk'],
      compositionRole: 'Merkezi mistik figür veya şifalı bitkilerle sarılı omurga',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dikey S-kıvrımlı yılan hattı, tepe taç geometrisi ve yaprak motifleri'
    },
    visualDescription: 'Zarif taçlı kadın çehresi, kıvrımlı pullu gövde ve etrafında açan şifalı dağ bitkileri.',
    numerologyConnection: 'Yaşam Yolu 7 (Gizli Sırlar) ve 9 (Evrensel Şifa)',
    astrologyConnection: 'Akrep ve Boğa',
    enneagramConnection: 'Tip 2 & Tip 4',
    visualKeywords: ['shahmaran anatolian mythology', 'snake queen fine line tattoo', 'sacred serpent woman healer']
  },
  {
    id: 'sym-valkyrie',
    name: 'Valkyrie & Kuzey Kanatları (Valkyrie Helm & Wings)',
    category: 'Mitoloji',
    subcategory: 'İskandinav Cesaret & Kader Dokuması',
    meaning: 'Savaş meydanında onurlu ruhları seçen göksel savaşçı; korkusuz cesaret, kader dokuması ve onurlu geçiş.',
    archetypes: ['Savaşçı Kadın', 'Kader Rehberi'],
    positiveThemes: ['korkusuzluk', 'onur', 'kendi kaderini sahiplenme', 'manevi koruma'],
    shadowThemes: ['sürekli savaş modunda kalma', 'dinlenememe'],
    relatedChakras: [3, 7],
    relatedElements: ['Hava', 'Ateş'],
    relatedNumerology: [1, 8],
    relatedAstrology: ['Koç', 'Yay'],
    relatedEnneagram: [8, 6],
    relatedTotemThemes: ['kanatlı miğfer', 'kuzgun refakati', 'kuzey kılıcı'],
    suitableFor: ['Kendi hayat mücadelesinde korkusuzca savaşan ve onurundan ödün vermeyenler'],
    avoidWhen: ['Tamamen kırılgan ve barışçıl pasif naiflik süreçleri'],
    designCompatibility: {
      recommendedStyles: ['Norse Linework', 'Fine Line Gothic', 'Black & Grey'],
      bodyPlacements: ['Omuz / Pazu', 'Sırt Kürek Kemiği', 'Önkol Dış'],
      compositionRole: 'Merkezi miğfer/kanat odağı veya koruyucu kalkan',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Kanatlı miğfer V-açısı ve keskin İskandinav rün hatları'
    },
    visualDescription: 'Kanatlı Viking miğferi profili, rüzgarda dalgalanan örgülü saçlar ve keskin rünik hatlar.',
    numerologyConnection: 'Yaşam Yolu 1 ve 8 (Cesaret ve Otorite)',
    astrologyConnection: 'Koç ve Yay',
    enneagramConnection: 'Tip 8 & Tip 6',
    visualKeywords: ['valkyrie winged helmet tattoo', 'norse mythology fine line', 'nordic shieldmaiden linework']
  },
  {
    id: 'sym-cybele',
    name: 'Kibele & Toprak Ana (Cybele / Magna Mater)',
    category: 'Mitoloji',
    subcategory: 'Doğanın Ham Gücü & Doğurganlık',
    meaning: 'Dağların kraliçesi, vahşi doğanın evcilleştirilemez anası, sarsılmaz taht ve doğurgan yaşam kaynağı.',
    archetypes: ['Toprak Ana', 'Hükümdar'],
    positiveThemes: ['ham yaşam gücü', 'köklenme', 'bereket', 'doğanın efendisi olma'],
    shadowThemes: ['yutucu ana arketipi', 'aşırı kontrol'],
    relatedChakras: [1, 2],
    relatedElements: ['Toprak'],
    relatedNumerology: [4, 6],
    relatedAstrology: ['Boğa', 'Başak', 'Oğlak'],
    relatedEnneagram: [8, 1],
    relatedTotemThemes: ['aslanlı taht', 'duvar tacı (corona muralis)', 'dağ zirvesi'],
    suitableFor: ['Kendi dişil kudretini, köklerini ve hayat yaratma gücünü taçlandırmak isteyenler'],
    avoidWhen: ['Hafif, uçarı ve temelsiz tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Classical Relief / Taş Heykel', 'Fine Line Engraving', 'Neo-Traditional'],
      bodyPlacements: ['Sırt', 'Pazu', 'Uyluk'],
      compositionRole: 'Görkemli merkezi taht veya dağ kaidesi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Kale duvarı tacı geometrisi ve iki yanda simetrik aslan silueti'
    },
    visualDescription: 'Taş duvar tacı takmış ana tanrıça profili, iki yanında koruyucu aslan hatları.',
    numerologyConnection: 'Yaşam Yolu 4 (Toprak Temeli) ve 6 (Besleyicilik)',
    astrologyConnection: 'Boğa ve Başak',
    enneagramConnection: 'Tip 8 & Tip 1',
    visualKeywords: ['cybele anatolian mother goddess', 'magna mater linework tattoo', 'anatolian archaeological relief']
  },
  {
    id: 'sym-huginn-muninn',
    name: 'Huginn & Muninn (Düşünce ve Hafıza)',
    category: 'Mitoloji',
    subcategory: 'Kozmik Vizyon & Hafıza Uyanışı',
    meaning: 'Odin’in iki omzundaki kuzgunlar; Huginn (Düşünce/Gelecek) ve Muninn (Hafıza/Geçmiş); zihnin tüm dünyayı taraması.',
    archetypes: ['Gözlemci', 'Haberci'],
    positiveThemes: ['derin zihinsel kavrayış', 'hafızanın uyanışı', 'stratejik öngörü', 'yüksekten bakış'],
    shadowThemes: ['hafızanın yükü altında ezilme', 'aşırı düşünce fırtınası'],
    relatedChakras: [6],
    relatedElements: ['Hava'],
    relatedNumerology: [7, 2],
    relatedAstrology: ['İkizler', 'Kova'],
    relatedEnneagram: [5, 6],
    relatedTotemThemes: ['çift kuzgun', 'rüzgarda süzülüş', 'valknut düğümü'],
    suitableFor: ['Geçmişin hafızasıyla geleceğin vizyonunu birleştirmek isteyen derin zihinler'],
    avoidWhen: ['Hafif, tasasız ve yüzeysel eğlence temaları'],
    designCompatibility: {
      recommendedStyles: ['Norse Dotwork', 'Fine Line Ravens', 'Geometric Valknut'],
      bodyPlacements: ['İki Omuz (Simetrik)', 'Önkol', 'Sırt Kürek Kemikleri'],
      compositionRole: 'İki yana simetrik uçan ikiz refakatçiler veya merkez Valknut çevresi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İki zıt yöne bakan üçgen kanat hatları ve merkezde Valknut düğümü'
    },
    visualDescription: 'Zıt yönlere süzülen iki kuzgun silueti, ortada ince rünik pusula (Vegvisir) veya Valknut.',
    numerologyConnection: 'Yaşam Yolu 7 ve 2',
    astrologyConnection: 'İkizler ve Kova',
    enneagramConnection: 'Tip 5 & Tip 6',
    visualKeywords: ['huginn and muninn ravens', 'odin ravens fine line tattoo', 'thought and memory ravens']
  },
  {
    id: 'sym-gilgamesh',
    name: 'Gılgamış & Yaşam Otu (Gilgamesh & The Plant of Life)',
    category: 'Mitoloji',
    subcategory: 'Ölümlülüğün Kabulü & Kadim Arayış',
    meaning: 'Mezopotamya destanı; ebediyet arayışı, derin dostluk (Enkidu), ölümlülüğün olgun kabulü ve mirasını inşa etme.',
    archetypes: ['Kahraman', 'Kâşif', 'İnşa Eden'],
    positiveThemes: ['kahramanın olgunlaşması', 'sadık dostluk', 'kalıcı eser bırakma', 'kabul bilgeliği'],
    shadowThemes: ['ölüm korkusu', 'anlamsızlık krizleri'],
    relatedChakras: [3, 4],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [8, 4],
    relatedAstrology: ['Aslan', 'Oğlak'],
    relatedEnneagram: [8, 3],
    relatedTotemThemes: ['uruk surları', 'deniz dibi yaşam otu', 'boğa boynuzları'],
    suitableFor: ['Hayatta büyük kayıplar yaşayıp bilgeliğe ulaşan ve adını tarihe yazdırmak isteyenler'],
    avoidWhen: ['Küçük, önemsiz ve geçici anlık hevesler'],
    designCompatibility: {
      recommendedStyles: ['Cuneiform Mesopotamian', 'Fine Line Relief', 'Engraving'],
      bodyPlacements: ['Pazu', 'Önkol Dış', 'Sırt'],
      compositionRole: 'Epik anlatı kompozisyonunun güçlü merkezi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Çivi yazısı silindirik mühür hatları ve Uruk surları dişleri'
    },
    visualDescription: 'Asur/Babil tarzı sakallı güçlü kral profili, elinde deniz dibinden çıkarılan gençlik otu.',
    numerologyConnection: 'Yaşam Yolu 8 ve 4',
    astrologyConnection: 'Aslan ve Oğlak',
    enneagramConnection: 'Tip 8 & Tip 3',
    visualKeywords: ['gilgamesh epic linework', 'mesopotamian cuneiform tattoo', 'ancient sumerian hero']
  },
  {
    id: 'sym-apollo-lyre',
    name: 'Apollon & Altın Lir (Lyre of Apollo)',
    category: 'Mitoloji',
    subcategory: 'Müzikal Harmoni & Güneş Işığı',
    meaning: 'Evrenin telleri arasındaki matematiksel armoni, müzik, kehanet, altın güneş ışığı ve sanatsal ilham.',
    archetypes: ['Sanatçı', 'Güneş Tanrısı'],
    positiveThemes: ['sanatsal dehâ', 'evrensel harmoni', 'aydınlık zihin', 'ilahi estetik'],
    shadowThemes: ['kibir', 'kusursuzluk baskısı'],
    relatedChakras: [5, 3],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [3, 1],
    relatedAstrology: ['Aslan', 'İkizler'],
    relatedEnneagram: [3, 4],
    relatedTotemThemes: ['altın teller', 'kaplumbağa kabuğu lir', 'defne dalları'],
    suitableFor: ['Sanatçılar, müzisyenler ve hayatında kusursuz bir harmoni ve neşe arayanlar'],
    avoidWhen: ['Karanlık, ağır ve kasvetli yeraltı temaları'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Hellenic', 'Classical Line Art', 'Micro Realism'],
      bodyPlacements: ['Önkol İç', 'Köprücük Kemiği', 'Kaburga'],
      compositionRole: 'Merkezi zarafet odağı veya defne çelengi içi motifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'U-formunda kavisli lir gövdesi ve paralel 7 ince tel çizgisi'
    },
    visualDescription: 'Zarif antik lir, üzerindeki 7 altın tel ve çevresinde parıldayan güneş ışınları.',
    numerologyConnection: 'Yaşam Yolu 3 (Yaratıcı İfade) ve 1',
    astrologyConnection: 'Aslan (Solar Parlaklık)',
    enneagramConnection: 'Tip 3 & Tip 4',
    visualKeywords: ['apollo lyre fine line', 'greek musical harp linework', 'classical golden lyre tattoo']
  },
  {
    id: 'sym-persephone',
    name: 'Persephone & Nar Tacı (Persephone Queen of Underworld)',
    category: 'Mitoloji',
    subcategory: 'Yeraltı Kraliçesi & Baharın Uyanışı',
    meaning: 'Masumiyetten yeraltı kraliçeliğine geçiş; kendi gölgesini sahiplenerek güçlenme, baharın gelişi ve döngüsel yenilenme.',
    archetypes: ['Dönüşen Kadın', 'Gölge Kraliçesi'],
    positiveThemes: ['gölgeyi taçlandırma', 'dayanıklılık', 'mevsimsel uyanış', 'derin otorite'],
    shadowThemes: ['tutsaklık hissi', 'melankoli'],
    relatedChakras: [2, 1, 6],
    relatedElements: ['Toprak', 'Su'],
    relatedNumerology: [8, 4],
    relatedAstrology: ['Akrep', 'Boğa', 'Başak'],
    relatedEnneagram: [4, 8],
    relatedTotemThemes: ['nar tohumları', 'karanlık çiçekler', 'yeraltı tahtı'],
    suitableFor: ['Kendi karanlığından korkmayıp onu kişisel gücüne dönüştüren güçlü ruhlar'],
    avoidWhen: ['Yüzeysel neşe ve acıyı tamamen yok sayan yaklaşımlar'],
    designCompatibility: {
      recommendedStyles: ['Gothic Botanical', 'Fine Line', 'Black & Grey'],
      bodyPlacements: ['Önkol', 'Sırt Kürek Kemiği', 'Kaburga'],
      compositionRole: 'Merkezi dönüşüm figürü veya nar dalı ile sarılı taç',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Açılmış nar silueti, hilal taç ve sarmaşık çiçek hatları'
    },
    visualDescription: 'Taç takmış zarif kraliçe silueti, elinde açık nar meyvesi ve çevresinde bahar çiçekleri.',
    numerologyConnection: 'Yaşam Yolu 8 ve 4',
    astrologyConnection: 'Akrep ve Boğa',
    enneagramConnection: 'Tip 4 & Tip 8',
    visualKeywords: ['persephone queen of underworld', 'pomegranate goddess linework', 'gothic mythology tattoo']
  },
  {
    id: 'sym-thoth',
    name: 'Thoth & Kozmik Kalem (Thoth Baboon / Ibis)',
    category: 'Mitoloji',
    subcategory: 'Kutsal Yazıtlar & Kozmik Denge',
    meaning: 'Kutsal geometrinin, yazının, takvimlerin ve ayın efendisi; ilahi kayıtların tutucusu ve mutlak zihinsel berraklık.',
    archetypes: ['Kâtip', 'Bilge', 'Kozmik Hakem'],
    positiveThemes: ['yüksek entelektüel güç', 'doğru kelimelerin gücü', 'kozmik kayıtlar', 'adalet'],
    shadowThemes: ['her şeyi analiz edip hissetmeme'],
    relatedChakras: [5, 6, 7],
    relatedElements: ['Hava', 'Eter'],
    relatedNumerology: [7, 11],
    relatedAstrology: ['Kova', 'Başak', 'İkizler'],
    relatedEnneagram: [5, 1],
    relatedTotemThemes: ['ibis kuşu gagası', 'ay diski başlığı', 'kamış kalem ve papirüs'],
    suitableFor: ['Yazarlar, araştırmacılar, bilim insanları ve kelimelerin kutsal gücüne inananlar'],
    avoidWhen: ['Duygusal sezgisel ve tamamen kuralsız plansız arayışlar'],
    designCompatibility: {
      recommendedStyles: ['Hieroglyphic Fine Line', 'Geometric Engraving', 'Minimalist Scribe'],
      bodyPlacements: ['Önkol İç', 'Bilek', 'Kürek Kemiği'],
      compositionRole: 'Merkezi kâtip odağı veya hiyeroglif kılavuz sütunu',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İbis kuşunun kavisli gagası çizgisi, ay küresi ve dikey papirüs ekseni'
    },
    visualDescription: 'İbis kuşu başlı Thoth profili, başında hilal-dolunay tacı ve elinde kozmik kalem.',
    numerologyConnection: 'Yaşam Yolu 7 ve Üstat 11',
    astrologyConnection: 'Kova ve Başak',
    enneagramConnection: 'Tip 5 & Tip 1',
    visualKeywords: ['thoth ibis head god tattoo', 'egyptian scribe of gods', 'sacred geometry thoth linework']
  },
  {
    id: 'sym-griffin',
    name: 'Kutsal Grifon (Griffin / Gryphon)',
    category: 'Mitoloji',
    subcategory: 'Gök ve Yer Krallığı & Hazine Muhafızı',
    meaning: 'Aslanın cesareti ve yer hakimiyeti ile kartalın göksel vizyonunun birleşimi; kutsal değerlerin ve ruhsal hazinelerin sarsılmaz muhafızı.',
    archetypes: ['Muhafız', 'Güneş Savaşçısı', 'Hükümdar'],
    positiveThemes: ['çifte asalet', 'ruhsal hazineleri koruma', 'korkusuz gözetleme', 'yer-gök birliği'],
    shadowThemes: ['aşırı sahiplenme ve hırçınlık'],
    relatedChakras: [1, 3, 6],
    relatedElements: ['Toprak', 'Hava', 'Ateş'],
    relatedNumerology: [1, 8],
    relatedAstrology: ['Aslan', 'Koç', 'Yay'],
    relatedEnneagram: [8, 6],
    relatedTotemThemes: ['kartal başı ve pençeleri', 'aslan gövdesi', 'altın kanatlar'],
    suitableFor: ['Kendi değerlerini, ailesini ve kutsal emanetlerini canı pahasına koruyan cesur ruhlar'],
    avoidWhen: ['Yumuşak, pasif ve teslimiyetçi temalar'],
    designCompatibility: {
      recommendedStyles: ['Classical Engraving', 'Medieval Heraldic Line', 'Fine Line Mythological'],
      bodyPlacements: ['Sırt Merkez', 'Pazu / Omuz', 'Önkol Dış', 'Göğüs Yan'],
      compositionRole: 'Görkemli ana koruyucu figür veya iki taraflı armorial denge',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Açılmış kanat kavisleri, kavisli gaga çizgisi ve aslan pençesi dinamik hatları'
    },
    visualDescription: 'Kartal başı ve dev kanatları olan, aslan gövdesi üzerinde şahlanmış antik heraldik grifon figürü.',
    numerologyConnection: 'Yaşam Yolu 1 ve 8',
    astrologyConnection: 'Aslan ve Koç',
    enneagramConnection: 'Tip 8 & Tip 6',
    visualKeywords: ['griffin mythical tattoo linework', 'heraldic gryphon engraving design', 'guardian griffin fine line']
  },
  {
    id: 'sym-caduceus',
    name: 'Hermes Kadüseusu (Caduceus of Hermes)',
    category: 'Mitoloji',
    subcategory: 'Zıtlıkların Dengesi & Şifalı Asa',
    meaning: 'Kanatlı bir asa etrafına dolanan iki kutup yılanı (İda ve Pingala); eril-dişil zıtlıkların barışması, şifa ve aracılık ustalığı.',
    archetypes: ['Şifacı', 'Elçi', 'Simyacı'],
    positiveThemes: ['kutupların dengesi', 'iletişim gücü', 'şifa', 'kundalini yükselişi'],
    shadowThemes: ['aldatıcı ikilik'],
    relatedChakras: [1, 4, 6],
    relatedElements: ['Hava', 'Eter'],
    relatedNumerology: [5, 2, 7],
    relatedAstrology: ['İkizler', 'Başak'],
    relatedEnneagram: [5, 7],
    relatedTotemThemes: ['çift yılan dolanımı', 'kanatlı merkez asa', 'sekiz sayısı formu kesişim'],
    suitableFor: ['İçindeki zıt yönleri dengelemek, tıbbi/ruhsal şifa veya iletişim ustalığını simgelemek isteyenler'],
    avoidWhen: ['Yalnızca tek yönlü ve kutuplaşmış agresif kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Classic Engraving', 'Fine Line Symmetry', 'Medical Sacred Line'],
      bodyPlacements: ['Omurga Boyunca', 'Önkol Merkez', 'Baldır'],
      compositionRole: 'Mükemmel dikey simetri ekseni veya omurga dengeleyicisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dikey bir eksen etrafında çift sinüs dalgası oluşturan iki çizgi ve tepe kanatları'
    },
    visualDescription: 'Tepesinde açılmış bir çift kuş kanadı bulunan asaya simetrik olarak sarılmış iki bilge yılan.',
    numerologyConnection: 'Yaşam Yolu 5 ve 2',
    astrologyConnection: 'İkizler ve Başak',
    enneagramConnection: 'Tip 5 & Tip 7',
    visualKeywords: ['hermes caduceus linework', 'two snakes staff tattoo', 'healing alchemy symmetry caduceus']
  },
  {
    id: 'sym-medusa-mirror',
    name: 'Medusa & Gorgoneion Koruyucu Aynası',
    category: 'Mitoloji',
    subcategory: 'Gölge Korunması & Negatifliği Geri Yansıtma',
    meaning: 'Atehe\'nin kalkanına kazınan Medusa başı (Gorgoneion); kötülüğü taşlaştıran, yargıları aynalayan ve kadim dişil gücü koruyan güçlü tılsım.',
    archetypes: ['Gölge Savaşçısı', 'Koruyucu'],
    positiveThemes: ['negatifi püskürtme', 'yansıtıcı ayna', 'travmayı güce çevirme', 'dokunulmazlık'],
    shadowThemes: ['öfke patlamaları', 'duygusal taşlaşma'],
    relatedChakras: [1, 3, 6],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [8, 13],
    relatedAstrology: ['Akrep', 'Koç'],
    relatedEnneagram: [8, 6],
    relatedTotemThemes: ['yılan saçlar', 'delip geçen bakışlar', 'bronz ayna kalkan'],
    suitableFor: ['İhanetleri veya haksızlıkları aşıp kendi sınırlarını ve dişiliğini dokunulmaz kılanlar'],
    avoidWhen: ['Yumuşak çocuksu ve pasif naif tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Dark Neo-Classical', 'Fine Line Portrait', 'Etching Blackwork'],
      bodyPlacements: ['Uyluk Ön', 'Üst Kol', 'Kürek Kemiği'],
      compositionRole: 'Merkezi koruyucu miğfer/kalkan mührü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Yılan kıvrımlı dalgalı radyal saç çizgileri ve merkez delici göz çifti'
    },
    visualDescription: 'Zarif ve vakur bir kadın yüzü, saçlarından dökülen dalgalı yılan hatları ve delici bakışları.',
    numerologyConnection: 'Yaşam Yolu 8 ve 4',
    astrologyConnection: 'Akrep ve Koç',
    enneagramConnection: 'Tip 8 & Tip 6',
    visualKeywords: ['medusa gorgon tattoo linework', 'protective medusa fine line', 'mythological snake hair portrait']
  },
  {
    id: 'sym-ishtar-star',
    name: 'İştar & İnanna Yıldızı (Eight-Pointed Star of Ishtar)',
    category: 'Mitoloji',
    subcategory: 'Aşk, Savaş & Yeraltından Dönüş',
    meaning: 'Mezopotamya tanrıçası İştar\'ın 8 köşeli Venüs yıldızı; aşkın, cesaretin, yeraltına cesurca inip tahtını geri almanın kadim mührü.',
    archetypes: ['Savaşçı Kraliçe', 'Aşık'],
    positiveThemes: ['cesur tutku', 'karanlıktan zaferle çıkış', 'venüs parıltısı', 'bağımsız güç'],
    shadowThemes: ['yıkıcı kıskançlık'],
    relatedChakras: [2, 4, 3],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [8, 6],
    relatedAstrology: ['Boğa', 'Terazi', 'Akrep'],
    relatedEnneagram: [8, 2],
    relatedTotemThemes: ['sekiz ışınlı yıldız', 'aslan refakati', 'sabah ve akşam yıldızı'],
    suitableFor: ['Kendi karanlık dönemlerinden başarıyla geçmiş, hem sevgiye hem savaşa muktedir bağımsız ruhlar'],
    avoidWhen: ['Aşırı çekingen ve iddiasız temalar'],
    designCompatibility: {
      recommendedStyles: ['Mesopotamian Sacred Line', 'Fine Line Geometric', 'Gold Accent Dotwork'],
      bodyPlacements: ['Bilek', 'Sternum', 'Ense / Omuz Başı'],
      compositionRole: 'Merkezi Venüs odak yıldızı veya kılavuz ışık',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Sekiz sivri ucu olan iç içe iki kare veya radyal sivri ışın yıldızı'
    },
    visualDescription: 'Antik Babil kabartmalarındaki gibi, merkezinde küçük bir güneş ve sekiz sivri ok uçlu İştar yıldızı.',
    numerologyConnection: 'Yaşam Yolu 8 ve 6',
    astrologyConnection: 'Boğa ve Terazi',
    enneagramConnection: 'Tip 8 & Tip 2',
    visualKeywords: ['star of ishtar linework', 'inanna eight pointed star tattoo', 'mesopotamian goddess star symbol']
  },
  {
    id: 'sym-valkyrie-wings',
    name: 'Valkür Kanatları & Mührü (Valkyrie Wings)',
    category: 'Mitoloji',
    subcategory: 'Cesaret & Onurlu Ruhların Seçimi',
    meaning: 'İskandinav mitolojisinde savaş meydanında en onurlu ruhları seçip Valhalla\'ya taşıyan Valkürler; cesaret, koruma ve kaderi dik durarak karşılama.',
    archetypes: ['Savaşçı Ruh', 'Kader Muhafızı'],
    positiveThemes: ['onurlu cesaret', 'korkusuz seçim', 'sadakat', 'kanatlı koruma'],
    shadowThemes: ['ölüme fazla meyilli olma'],
    relatedChakras: [3, 4, 1],
    relatedElements: ['Hava', 'Ateş'],
    relatedNumerology: [1, 9],
    relatedAstrology: ['Koç', 'Yay'],
    relatedEnneagram: [8, 6],
    relatedTotemThemes: ['kuzgun kanadı miğfer', 'mızrak ucu', 'kutup ışıkları'],
    suitableFor: ['Korkusuzca doğru olanı savunan, zorlukların üstüne cesurca yürüyen savaşçı ruhlar'],
    avoidWhen: ['Pasif ve edilgen kabullenişler'],
    designCompatibility: {
      recommendedStyles: ['Norse Fine Line', 'Blackwork Stippling', 'Geometric Nordic'],
      bodyPlacements: ['Kürek Kemikleri', 'Önkol Yan', 'Bacak Baldır'],
      compositionRole: 'İki yana açılan koruyucu kanat çerçevesi veya merkez mızrak motifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Açılı geometrik kanat tüyleri ve merkez dikey mızrak çizgisi'
    },
    visualDescription: 'İskandinav miğferini andıran iki yana açılmış keskin tüylü kanatlar ve merkezindeki savaşçı mızrağı.',
    numerologyConnection: 'Yaşam Yolu 1 ve 9',
    astrologyConnection: 'Koç ve Yay',
    enneagramConnection: 'Tip 8 & Tip 6',
    visualKeywords: ['valkyrie wings norse tattoo', 'viking valkyrie spear linework', 'nordic protective wings design']
  }
];
