import { SymbolLibraryItem } from '../../types';

export const PLANT_SYMBOLS: SymbolLibraryItem[] = [
  {
    id: 'sym-lotus',
    name: 'Kutsal Lotus (Nilüfer)',
    category: 'Bitki/Çiçek',
    subcategory: 'Kutsal Çiçek & Aydınlanma',
    meaning: 'Bulanık çamurlu sulardan tertemiz açan aydınlanma, saf ruh, duygusal arınma ve yeniden doğum.',
    archetypes: ['Mistik', 'Şifacı', 'Masum'],
    positiveThemes: ['ruhsal saflık', 'karanlıktan aydınlığa geçiş', 'içsel dinginlik', 'yeniden doğuş'],
    shadowThemes: ['çamura saplanma hissi', 'aşırı dünyevilikten kaçış', 'duygusal kapanma'],
    relatedChakras: [4, 7],
    relatedElements: ['Su', 'Eter'],
    relatedNumerology: [9, 33],
    relatedAstrology: ['Balık', 'Yengeç'],
    relatedEnneagram: [9, 2],
    relatedTotemThemes: ['su üstünde yükseliş', 'lekesiz kalma', 'manevi köklenme'],
    suitableFor: ['Ruhsal dönüşüm ve duygusal yenilenme arayanlar', 'Zorlu dönemlerden güçlenerek çıkanlar'],
    avoidWhen: ['Aşırı topraklanma ve katı yapısal kurallar gerektiren durumlarda tek başına kullanılmamalıdır'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Micro Realism', 'Dotwork', 'Sacred Geometry'],
      bodyPlacements: ['Önkol İç', 'Sırt Omurga', 'Göğüs Kafesi', 'Ense Altı'],
      compositionRole: 'Merkezi taç odak veya alt çanak kaidesi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dışa doğru katman katman açılan konsantrik elipsler ve taban çemberi'
    },
    visualDescription: 'Kutsal geometri halkalarından yükselen hassas 03RL taç yapraklar ve merkezde altın oran tohum yuvası.',
    numerologyConnection: 'Yaşam Yolu 9 ve Üstat 33',
    astrologyConnection: 'Balık ve Yengeç (Su arınması)',
    enneagramConnection: 'Tip 9 (Huzur) & Tip 2',
    visualKeywords: ['unfolding sacred lotus', 'unalome with lotus', 'water ripples and lily', 'geometric lotus']
  },
  {
    id: 'sym-black-rose',
    name: 'Kara Gül (Black Rose)',
    category: 'Bitki/Çiçek',
    subcategory: 'Gölge Çiçeği & Dönüşüm',
    meaning: 'Gizemli ve derin aşk, acının zarafete dönüşmesi, dokunulmaz kutsal sınırlar ve karanlıktan doğan güç.',
    archetypes: ['Asi', 'Aşık', 'Simyacı'],
    positiveThemes: ['derin sevgi', 'sağlam sınırlar', 'özgün zarafet', 'tutkulu direnç'],
    shadowThemes: ['kırılma korkusu', 'aşırı savunmacılık', 'melankoliye tutunma'],
    relatedChakras: [1, 4],
    relatedElements: ['Toprak', 'Su'],
    relatedNumerology: [6, 8],
    relatedAstrology: ['Akrep', 'Boğa'],
    relatedEnneagram: [4, 1],
    relatedTotemThemes: ['dikenli koruma', 'derin kökler', 'gizli güzellik'],
    suitableFor: ['Kişisel sınırlarını netleştirmek ve acısını güce dönüştürmek isteyenler'],
    avoidWhen: ['Yalnızca hafif ve oyuncu neşe aranan naif temalarda baskın kullanılmamalıdır'],
    designCompatibility: {
      recommendedStyles: ['Black & Grey', 'Fine Line', 'Blackwork', 'Gothic Floral'],
      bodyPlacements: ['Önkol Dış', 'Omuz Başlangıcı', 'Uyluk Yanı', 'Köprücük Kemiği'],
      compositionRole: 'Gölge kutbu dengeleyici odak veya hançer/yılan sarıcı motif',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Sarmal logaritmik spiral ve köşeli geometrik diken kılavuzları'
    },
    visualDescription: 'Kadife dokulu siyah taç yapraklar, keskin mikro dikenler ve ince damarlı botanik hatlar.',
    numerologyConnection: 'Yaşam Yolu 6 ve 8',
    astrologyConnection: 'Akrep ve Boğa (Venüs derinliği)',
    enneagramConnection: 'Tip 4 (Melankoli) & Tip 1',
    visualKeywords: ['black rose with thorns', 'dripping ink rose', 'blooming gothic rose', 'botanical fine line rose']
  },
  {
    id: 'sym-oak',
    name: 'Yaşam Ağacı & Meşe (Tree of Life / Oak)',
    category: 'Bitki/Çiçek',
    subcategory: 'Kutsal Ağaç & Aks',
    meaning: 'Köklerden göğe uzanan evrensel eksen (Axis Mundi), sarsılmaz dayanıklılık, soy bağı ve kadim koruma.',
    archetypes: ['Hükümdar', 'Bilge', 'Koruyucu'],
    positiveThemes: ['sarsılmaz köklenme', 'dayanıklılık', 'bilgelik', 'nesiller arası bağ'],
    shadowThemes: ['katılık', 'değişime direnç', 'aşırı yük taşıma'],
    relatedChakras: [1, 7],
    relatedElements: ['Toprak'],
    relatedNumerology: [4, 22],
    relatedAstrology: ['Oğlak', 'Boğa'],
    relatedEnneagram: [1, 8],
    relatedTotemThemes: ['derin kök', 'göğe yükselen gövde', 'fırtınada yıkılmama'],
    suitableFor: ['Hayatında sağlam bir zemin ve kalıcı bir omurga inşa etmek isteyenler'],
    avoidWhen: ['Hafif, tamamen akışkan ve serbest dalgalı minimal arayışlarda fazla ağır gelebilir'],
    designCompatibility: {
      recommendedStyles: ['Etching / Gravür', 'Fine Line', 'Geometric Dotwork', 'Blackwork'],
      bodyPlacements: ['Sırt Omurga', 'Pazu / Biceps', 'Bacak Kaval Kemiği Yanı'],
      compositionRole: 'Kompozisyonun dik taşıyıcı omurgası ve kök tabanı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dikey simetri ekseni, fraktal dallanma vektörleri ve dairesel taç kılavuzu'
    },
    visualDescription: 'Toprağın derinliklerine inen dallı kökler, güçlü kıvrımlı gövde ve geometrik çember içine oturan taç yapraklar.',
    numerologyConnection: 'Yaşam Yolu 4 (Sağlam Temel) ve Üstat 22',
    astrologyConnection: 'Oğlak ve Boğa (Toprak gücü)',
    enneagramConnection: 'Tip 1 & Tip 8',
    visualKeywords: ['roots and branches sacred tree', 'celtic yggdrasil', 'deep rooted oak', 'kabbalistic tree']
  },
  {
    id: 'sym-aconite',
    name: 'Akonit & Haşhaş (Aconite & Poppy)',
    category: 'Bitki/Çiçek',
    subcategory: 'Mistik Zehir & Rüya Florası',
    meaning: 'Mistik rüyalar, şifalı zehir, sınırları muhafaza etme, derin uyku ve bilincin perdesini aralama.',
    archetypes: ['Büyücü', 'Gölge Şifacısı'],
    positiveThemes: ['rüya bilinci', 'derin koruma', 'illüzyonları delme', 'sınır koyma'],
    shadowThemes: ['zehirlenme korkusu', 'gerçeklikten kopuş', 'aşırı şüphecilik'],
    relatedChakras: [6, 7],
    relatedElements: ['Su', 'Ateş'],
    relatedNumerology: [7, 11],
    relatedAstrology: ['Akrep', 'Balık'],
    relatedEnneagram: [5, 4],
    relatedTotemThemes: ['gece uyanışı', 'koruyucu bariyer', 'derin sezgi'],
    suitableFor: ['Bilinçaltı rüya çalışmaları yapan ve ruhsal alanını yabancı enerjilere kapatmak isteyenler'],
    avoidWhen: ['Yalnızca açık, doğrudan ve güneşsel parlaklık arzulanan saf solar kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Micro Realism', 'Dotwork', 'Botanical Engraving'],
      bodyPlacements: ['Önkol İç', 'Kaburga Yanı', 'Bilek Üstü'],
      compositionRole: 'Yardımcı mistik botanik dolgu veya dikey akış çizgisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Damla şeklinde tohum kapsülü ve keskin çan kavisleri'
    },
    visualDescription: 'Hassas tohum kapsülü (haşhaş kellesi), taç yapraklar ve ince botanik çizim hatları.',
    numerologyConnection: 'Yaşam Yolu 7 ve Üstat 11',
    astrologyConnection: 'Akrep ve Balık',
    enneagramConnection: 'Tip 5 & Tip 4',
    visualKeywords: ['botanical aconite flower', 'poppy seed pods', 'vintage herbalist ink drawing']
  },
  {
    id: 'sym-ginkgo',
    name: 'Ginkgo Biloba (Mabet Ağacı)',
    category: 'Bitki/Çiçek',
    subcategory: 'Kadim Hafıza & İkili Denge',
    meaning: 'Zamanın ötesinde hayatta kalma, kadim hafıza, yin-yang ikiliğinin tek yaprakta birleşmesi ve zarafet.',
    archetypes: ['Bilge', 'Barışçı', 'Dengeleyici'],
    positiveThemes: ['hafıza berraklığı', 'zamansızlık', 'ikiliğin uyumu', 'zarafet'],
    shadowThemes: ['geçmişe takılma', 'melankolik nostalji'],
    relatedChakras: [6, 4],
    relatedElements: ['Hava', 'Toprak'],
    relatedNumerology: [2, 7],
    relatedAstrology: ['İkizler', 'Terazi', 'Başak'],
    relatedEnneagram: [5, 9],
    relatedTotemThemes: ['yelpaze formu', 'antik direnç', 'ikili lob dengesi'],
    suitableFor: ['Zihinsel berraklık, hafıza sağlamlığı ve zıt kutuplar arasında denge arayanlar'],
    avoidWhen: ['Aşırı agresif veya sert yırtıcı savaşçı temalarıyla çatışabilir'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Minimalist', 'Asian Brush / Sumi-e', 'Dotwork'],
      bodyPlacements: ['Köprücük Kemiği', 'Bilek', 'Kulak Arkası / Boyun Yanı', 'Önkol'],
      compositionRole: 'İnce hava akışı taşıyıcısı veya ikili denge motifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkezden radyal açılan yelpaze ışınları ve yarık tepe yayı'
    },
    visualDescription: 'Ortadan ikiye ayrılmış karakteristik yelpaze yaprak damarları ve akışkan ince 03RL çizgiler.',
    numerologyConnection: 'Yaşam Yolu 2 (İkili Denge) ve 7 (Kadim Zihin)',
    astrologyConnection: 'İkizler, Terazi ve Başak',
    enneagramConnection: 'Tip 5 (Gözlemci) & Tip 9',
    visualKeywords: ['ginkgo biloba leaf linework', 'botanical fan leaf', 'delicate ginkgo fine line', 'yin yang ginkgo']
  },
  {
    id: 'sym-olive-branch',
    name: 'Zeytin Dalı (Olive Branch)',
    category: 'Bitki/Çiçek',
    subcategory: 'Kutsal Barış & Bereket',
    meaning: 'Kutsal barış, fırtına sonrası dinginlik, tanrısal koruma, bereket ve Athena’nın hediyesi.',
    archetypes: ['Barışçı', 'Hükümdar', 'Şifacı'],
    positiveThemes: ['içsel huzur', 'uzlaşma', 'bereket', 'onur'],
    shadowThemes: ['çatışmadan aşırı kaçış', 'pasif direniş'],
    relatedChakras: [4, 3],
    relatedElements: ['Toprak', 'Güneş / Ateş'],
    relatedNumerology: [6, 3],
    relatedAstrology: ['Boğa', 'Terazi', 'Aslan'],
    relatedEnneagram: [9, 2],
    relatedTotemThemes: ['akdeniz güneşi', 'gümüşi yaprak', 'dayanıklı gövde'],
    suitableFor: ['İçsel çatışmalarını sonlandırıp huzur ve asalet isteyenler'],
    avoidWhen: ['Kişi mücadeleci ve yıkıcı bir uyanış evresindeyse uygun olmayabilir'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Neo-Traditional', 'Dotwork', 'Micro Realism'],
      bodyPlacements: ['Köprücük Kemiği Boyunca', 'Bilek Sarmalı', 'Önkol Dış'],
      compositionRole: 'Geometrik çerçeveyi saran taç veya kaide süslemesi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkezi kavisli eksen üzerinde ardışık simetrik elips yapraklar'
    },
    visualDescription: 'Gümüşi dar yapraklar, küçük zeytin taneleri ve kavisli zarif dal akışı.',
    numerologyConnection: 'Yaşam Yolu 6 (Uyum) ve 3 (Bolluk)',
    astrologyConnection: 'Boğa ve Terazi (Venüs dengesi)',
    enneagramConnection: 'Tip 9 & Tip 2',
    visualKeywords: ['olive branch wreath', 'delicate olive leaves fine line', 'peace symbol botanical', 'athena olive']
  },
  {
    id: 'sym-laurel',
    name: 'Defne Yaprağı & Çelengi (Laurel Wreath)',
    category: 'Bitki/Çiçek',
    subcategory: 'Zafer & Kehanet',
    meaning: 'Kişisel zafer, ruhsal arınma, kehanet yeteneği, asalet ve Apollon’un tacı.',
    archetypes: ['Kahraman', 'Hükümdar', 'Gezgin'],
    positiveThemes: ['başarı', 'kendini aşma', 'onur', 'arınma'],
    shadowThemes: ['kibir', 'başkalarının onayına bağımlılık'],
    relatedChakras: [3, 7],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [1, 8],
    relatedAstrology: ['Aslan', 'Koç', 'Yay'],
    relatedEnneagram: [3, 8],
    relatedTotemThemes: ['güneş tacı', 'zafer çelengi', 'daphne metamorfozu'],
    suitableFor: ['Büyük bir mücadeleyi kazanmış ve kendi otoritesini ilan edenler'],
    avoidWhen: ['Aşırı tevazu ve görünmezlik arzulanan temalarda öne çıkarılmamalıdır'],
    designCompatibility: {
      recommendedStyles: ['Classical Engraving', 'Fine Line', 'Geometric Frame'],
      bodyPlacements: ['Ense / Sırt Üst', 'Pazu Çevresi', 'Köprücük Kemiği', 'Göğüs Üstü'],
      compositionRole: 'Merkezi motifi çevreleyen dairesel veya hilal zafer tacı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Açık yarım çember kılavuzuna dizilmiş ritmik sivri yaprak dizisi'
    },
    visualDescription: 'Keskin uçlu defne yapraklarının oluşturduğu dairesel zafer tacı, ince hatlar.',
    numerologyConnection: 'Yaşam Yolu 1 (Liderlik) ve 8 (Zafer/Otorite)',
    astrologyConnection: 'Aslan (Solar Gurur) ve Koç',
    enneagramConnection: 'Tip 3 (Başarı) & Tip 8',
    visualKeywords: ['apollo laurel wreath', 'victory laurel leaves', 'roman laurel crown', 'fine line botanical wreath']
  },
  {
    id: 'sym-lavender',
    name: 'Lavanta (Lavender)',
    category: 'Bitki/Çiçek',
    subcategory: 'Zihinsel Sükunet & Şifa',
    meaning: 'Zihinsel dinginlik, sinir sistemini yatıştırma, üçüncü göz ferahlığı ve psişik arınma.',
    archetypes: ['Şifacı', 'Masum'],
    positiveThemes: ['derin sükunet', 'endişeden arınma', 'nazik zarafet', 'şifa'],
    shadowThemes: ['aşırı kırılganlık', 'pasiflik'],
    relatedChakras: [5, 6],
    relatedElements: ['Hava'],
    relatedNumerology: [7, 2],
    relatedAstrology: ['Başak', 'Kova'],
    relatedEnneagram: [5, 9],
    relatedTotemThemes: ['dingin koku', 'dik çiçek başakları', 'mor frekans'],
    suitableFor: ['Yoğun stres ve zihinsel aşırı yük yaşayan, dinginlik arayan kişiler'],
    avoidWhen: ['Yüksek ateşli, saldırgan veya ham fiziksel güç temaları'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Micro Realism', 'Minimalist', 'Botanical Ink'],
      bodyPlacements: ['Bilek İçi', 'Önkol Yanı', 'Köprücük Altı', 'Ayak Bileği'],
      compositionRole: 'Dikey zarif akış çizgisi veya minimal köşe detayı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dikey ince kılavuz eksen üzerinde damla şeklinde noktasal başaklar'
    },
    visualDescription: 'Dikey ince sap boyunca sıralanmış küçük çiçek tomurcukları ve mikro dotwork detaylar.',
    numerologyConnection: 'Yaşam Yolu 7 (Zihinsel İnziva) ve 2 (Şefkat)',
    astrologyConnection: 'Başak ve Kova (Zihin berraklığı)',
    enneagramConnection: 'Tip 5 & Tip 9',
    visualKeywords: ['lavender sprig fine line', 'botanical lavender stem', 'delicate healing lavender tattoo']
  },
  {
    id: 'sym-fern',
    name: 'Eğrelti Otu & Spiral Koru (Fern)',
    category: 'Bitki/Çiçek',
    subcategory: 'Fraktal Büyüme & Yeni Başlangıç',
    meaning: 'Gizli bilgelik, yeni başlangıçlar, spiral büyüme (Koru formu), adaptasyon ve orman koruması.',
    archetypes: ['Gezgin', 'Yaratıcı'],
    positiveThemes: ['sürekli yenilenme', 'fraktal düzen', 'doğal zarafet', 'esneklik'],
    shadowThemes: ['gölgelerde saklanma', 'açılmaktan çekinme'],
    relatedChakras: [4, 1],
    relatedElements: ['Toprak', 'Su'],
    relatedNumerology: [5, 3],
    relatedAstrology: ['Yay', 'Yengeç'],
    relatedEnneagram: [7, 4],
    relatedTotemThemes: ['açılan spiral sürgün', 'fraktal yaprak dizilimi', 'orman tabanı'],
    suitableFor: ['Hayatında yepyeni bir sayfa açan ve büyüme döngüsüne giren kişiler'],
    avoidWhen: ['Katı simetrik ve mekanik sert tasarımlarda uyum zorlaşabilir'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Dotwork', 'Botanical', 'Fibonacci Integrated'],
      bodyPlacements: ['Omurga Boyunca', 'Önkol Kavisli Akış', 'Baldır Yanı'],
      compositionRole: 'Akışkan dinamik S-eğrisi veya yan destekleyici bitkisel kanat',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Logaritmik spiral ucu ve fraktal kendi kendine benzeyen ikincil çizgiler'
    },
    visualDescription: 'Spiral şeklinde açılan taze sürgün ucu (koru) ve iki yana açılan ritmik mikro yapraklar.',
    numerologyConnection: 'Yaşam Yolu 5 (Özgür Büyüme) ve 3 (Yaratıcı İfade)',
    astrologyConnection: 'Yay ve Yengeç',
    enneagramConnection: 'Tip 7 & Tip 4',
    visualKeywords: ['unfurling fern koru', 'botanical fern frond linework', 'sacred geometry fern spiral']
  },
  {
    id: 'sym-ivy',
    name: 'Sarmaşık (Sacred Ivy)',
    category: 'Bitki/Çiçek',
    subcategory: 'Sadakat & Aşılmaz Azim',
    meaning: 'Sonsuz bağlılık, zorluklara sarılarak yükselme, azim, sadakat ve ölümden sonra yaşam.',
    archetypes: ['Aşık', 'Savaşçı'],
    positiveThemes: ['sadakat', 'tırmanma gücü', 'bırakmama iradesi', 'süreklilik'],
    shadowThemes: ['bağımlılık', 'boğucu sahiplenme', 'bırakamama'],
    relatedChakras: [4, 2],
    relatedElements: ['Toprak', 'Su'],
    relatedNumerology: [6, 4],
    relatedAstrology: ['Yengeç', 'Oğlak'],
    relatedEnneagram: [6, 2],
    relatedTotemThemes: ['duvara tırmanan kök', 'kalp yaprak', 'sonsuz bağ'],
    suitableFor: ['Karşılaştığı engelleri basamak yaparak zirveye tırmanan azimli ruhlar'],
    avoidWhen: ['Aşırı bağımsızlık ve hiçbir bağ istemeyen temalarda boğucu hissedilebilir'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Ornamental', 'Blackwork Sarmal'],
      bodyPlacements: ['Kol Sarmalı', 'Bilek Bilezik', 'Omurga Sarıcı'],
      compositionRole: 'Diğer geometrik sembolleri ve kılıç/hançeri birbirine bağlayan sarıcı ip',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Heliks / çift sarmal eğri ve ritmik üçgen yaprak düğümleri'
    },
    visualDescription: 'Taş veya hançer etrafına dolanan kıvrımlı sarmaşık gövdesi ve sivri damarlı yapraklar.',
    numerologyConnection: 'Yaşam Yolu 6 ve 4',
    astrologyConnection: 'Yengeç ve Oğlak (Duygusal ve Maddi Direnç)',
    enneagramConnection: 'Tip 6 (Sadık) & Tip 2',
    visualKeywords: ['ivy vine climbing', 'entwined ivy leaves', 'sacred botanical ivy linework']
  },
  {
    id: 'sym-willow',
    name: 'Salkım Söğüt (Weeping Willow)',
    category: 'Bitki/Çiçek',
    subcategory: 'Duygusal Esneklik & Hüzün Simyası',
    meaning: 'Fırtınada kırılmayan esneklik, hüzün ve kederin zarafete dönüşmesi, derin sezgi ve suyla bağ.',
    archetypes: ['Şifacı', 'Mistik'],
    positiveThemes: ['esneklik', 'duygusal simya', 'kabul', 'sezgisel akış'],
    shadowThemes: ['kurban psikolojisi', 'hüzne saplanma'],
    relatedChakras: [2, 4],
    relatedElements: ['Su'],
    relatedNumerology: [2, 9],
    relatedAstrology: ['Balık', 'Yengeç', 'Akrep'],
    relatedEnneagram: [4, 9],
    relatedTotemThemes: ['eğilen ama kırılmayan dal', 'suya değen yapraklar', 'duygu akışı'],
    suitableFor: ['Büyük bir yastan veya hüzünden geçip esneyerek hayatta kalanlar'],
    avoidWhen: ['Sert köşeli, askeri disiplinli veya katı mimari tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Micro Realism', 'Waterflow Stippling'],
      bodyPlacements: ['Kaburga', 'Sırt Kürek Kemiği Altı', 'Önkol'],
      compositionRole: 'Aşağı doğru süzülen organik perde veya su akışı köprüsü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Yerçekimine boyun eğen paralel dalgalı kavisler ve damla uçları'
    },
    visualDescription: 'Zarifçe aşağı sarkan ince söğüt dalları ve üzerindeki narin yaprak taneleri.',
    numerologyConnection: 'Yaşam Yolu 2 ve 9',
    astrologyConnection: 'Balık ve Yengeç (Su Simyası)',
    enneagramConnection: 'Tip 4 & Tip 9',
    visualKeywords: ['weeping willow branches', 'flowing willow leaves linework', 'melancholic graceful tree']
  },
  {
    id: 'sym-cypress',
    name: 'Selvi Ağacı (Cypress)',
    category: 'Bitki/Çiçek',
    subcategory: 'Sonsuzluk & Göğe Yükseliş',
    meaning: 'Sonsuzluğa uzanan dik duruş, ruhun göğe yükselişi, yasın vakur asaleti ve değişmez dürüstlük.',
    archetypes: ['Münzevi', 'Muhafız'],
    positiveThemes: ['vakur duruş', 'sonsuzluk bilinci', 'dürüstlük', 'dik omurga'],
    shadowThemes: ['aşırı ciddiyet', 'ölüm takıntısı'],
    relatedChakras: [1, 7],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [1, 7],
    relatedAstrology: ['Oğlak', 'Akrep'],
    relatedEnneagram: [1, 5],
    relatedTotemThemes: ['ok gibi göğe uzanma', 'yemyeşil kalma', 'kadim mezarlık muhafızı'],
    suitableFor: ['Kendi değerlerinden ödün vermeyen, dik ve onurlu bir duruş sergileyenler'],
    avoidWhen: ['Renkli, neşeli ve çocuksu hafif arayışlarda fazla vakur kalabilir'],
    designCompatibility: {
      recommendedStyles: ['Minimalist Silhouette', 'Fine Line', 'Geometric Accent'],
      bodyPlacements: ['Önkol Dış', 'Bacak Kaval Kemiği', 'Omurga'],
      compositionRole: 'Dikey hizalama oku veya arka plan göksel ekseni',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dar üçgen/mızrak silueti ve dikey merkez omurga'
    },
    visualDescription: 'Alev formunda yukarı doğru sivrilen dik ve yoğun selvi ağacı silueti.',
    numerologyConnection: 'Yaşam Yolu 1 ve 7',
    astrologyConnection: 'Oğlak ve Akrep',
    enneagramConnection: 'Tip 1 & Tip 5',
    visualKeywords: ['cypress tree silhouette', 'slender italian cypress fine line', 'vertical eternal tree']
  },
  {
    id: 'sym-pine-cedar',
    name: 'Sedir & Dağ Çamı (Cedar & Pine)',
    category: 'Bitki/Çiçek',
    subcategory: 'Ölümsüzlük & Arındırıcı Reçine',
    meaning: 'Ölümsüz ruh, kış fırtınalarına meydan okuma, arındırıcı reçine kokusu, üçüncü göz kozalağı (Epifiz).',
    archetypes: ['Şaman', 'Savaşçı'],
    positiveThemes: ['ölümsüzlük', 'aurayı temizleme', 'dağ dayanıklılığı', 'epifiz bezi uyanışı'],
    shadowThemes: ['yalnızlaşma', 'aşırı sert mizaç'],
    relatedChakras: [6, 1],
    relatedElements: ['Toprak', 'Hava'],
    relatedNumerology: [4, 11],
    relatedAstrology: ['Oğlak', 'Yay'],
    relatedEnneagram: [8, 5],
    relatedTotemThemes: ['yeşil iğneler', 'altın oran kozalak', 'dağ rüzgarı'],
    suitableFor: ['Zorlu koşullarda dik duran ve sezgisel epifiz uyanışı arayanlar'],
    avoidWhen: ['Yumuşak, narin ve su odaklı zayıf akışlar'],
    designCompatibility: {
      recommendedStyles: ['Etching', 'Fine Line', 'Fibonacci Dotwork'],
      bodyPlacements: ['Önkol', 'Omuz', 'Sırt'],
      compositionRole: 'Fibonacci kozalağı odak motifi veya dağ manzarası armatürü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Fibonacci spirali şeklinde dizilmiş çam kozalağı pulları'
    },
    visualDescription: 'İğne yapraklar ve merkezde Fibonacci altın spirali oluşturan çam kozalağı.',
    numerologyConnection: 'Yaşam Yolu 4 ve Üstat 11',
    astrologyConnection: 'Oğlak ve Yay',
    enneagramConnection: 'Tip 8 & Tip 5',
    visualKeywords: ['pine cone fibonacci', 'cedar needles botanical', 'sacred pineal gland pinecone']
  },
  {
    id: 'sym-pomegranate',
    name: 'Nar Çiçeği & Meyvesi (Pomegranate)',
    category: 'Bitki/Çiçek',
    subcategory: 'Yeraltı Sırları & Sonsuz Bolluk',
    meaning: 'Persephone’nin yeraltı sırları, tek kabukta toplanan binlerce tohum (birlik içinde çokluk), bereket ve yaratım.',
    archetypes: ['Büyücü', 'Yaratıcı', 'Aşık'],
    positiveThemes: ['yaratıcı bolluk', 'gölgeden doğan bereket', 'birlik bilinci', 'tutku'],
    shadowThemes: ['bağlayıcı sözleşmeler', 'karanlığa çekilme'],
    relatedChakras: [2, 1],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [3, 8],
    relatedAstrology: ['Akrep', 'Boğa'],
    relatedEnneagram: [4, 8],
    relatedTotemThemes: ['yakut tohumlar', 'kral tacı kabuk', 'yeraltı kraliçesi'],
    suitableFor: ['Yaratıcılığını ateşlemek ve gölgesindeki zenginliği açığa çıkarmak isteyenler'],
    avoidWhen: ['Minimalist renksiz ve tamamen kuru kavramsal tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Micro Realism', 'Classical Botanical'],
      bodyPlacements: ['Önkol İç', 'Kaburga Yanı', 'Uyluk Üstü'],
      compositionRole: 'Merkezi zenginlik odağı veya açık meyve kesiti motifi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dairesel küre içinde geometrik altıgen hücreler ve taç sivrisi'
    },
    visualDescription: 'Ortadan yarılmış, parlak yakut taneleri görünen taçlı nar meyvesi ve narin çiçekleri.',
    numerologyConnection: 'Yaşam Yolu 3 (Bolluk) ve 8 (Maddi/Manevi Güç)',
    astrologyConnection: 'Akrep ve Boğa',
    enneagramConnection: 'Tip 4 & Tip 8',
    visualKeywords: ['botanical split pomegranate', 'ruby seeds linework', 'persephone myth pomegranate']
  },
  {
    id: 'sym-sunflower',
    name: 'Ayçiçeği (Sunflower)',
    category: 'Bitki/Çiçek',
    subcategory: 'Güneşe Yöneliş & Sadakat',
    meaning: 'Işığa ve gerçeğe kesintisiz yöneliş (Helyotropizm), solar plexus canlılığı, neşe ve sarsılmaz sadakat.',
    archetypes: ['Güneş Kahramanı', 'Masum'],
    positiveThemes: ['iyimserlik', 'ışığa yönelme', 'canlılık', 'kararlılık'],
    shadowThemes: ['karanlığı inkâr etme', 'aşırı dışa bağımlılık'],
    relatedChakras: [3],
    relatedElements: ['Ateş', 'Toprak'],
    relatedNumerology: [1, 3],
    relatedAstrology: ['Aslan', 'Koç'],
    relatedEnneagram: [3, 7],
    relatedTotemThemes: ['güneş çarkı', 'altın oran tohum matrisi', 'yüksek gövde'],
    suitableFor: ['Hayatında pozitif ışığı, özgüveni ve canlılığı sabitlemek isteyenler'],
    avoidWhen: ['Karanlık, gotik, melankolik veya derin gölge temalarıyla tezat oluşturabilir'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Fibonacci Dotwork', 'Geometric Floral'],
      bodyPlacements: ['Omuz Başı', 'Önkol', 'Sırt Kürek Kemiği'],
      compositionRole: 'Solar odak noktası veya geometrik mandala tabanı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkezde Fermat spirali tohum dizilimi ve radyal üçgen yapraklar'
    },
    visualDescription: 'Merkezinde mükemmel altın oran tohum spirali ve etrafında neşeli açılan taç yapraklar.',
    numerologyConnection: 'Yaşam Yolu 1 ve 3 (Solar İfade)',
    astrologyConnection: 'Aslan (Güneş Rezonansı)',
    enneagramConnection: 'Tip 3 & Tip 7',
    visualKeywords: ['sunflower sacred geometry', 'fibonacci sunflower center', 'fine line solar flower']
  },
  {
    id: 'sym-iris-lily',
    name: 'İris & Kutsal Zambak (Iris & Sacred Lily)',
    category: 'Bitki/Çiçek',
    subcategory: 'Gökkuşağı Köprüsü & İlahi Mesaj',
    meaning: 'Boyutlar arası gökkuşağı köprüsü (İris tanrıçası), ilahi mesajlar, ruhsal saflık, asalet ve sezgi.',
    archetypes: ['Haberci', 'Mistik'],
    positiveThemes: ['ilahi rehberlik', 'yüksek vizyon', 'asalet', 'zarafet'],
    shadowThemes: ['ulaşılmazlık', 'aşırı idealleştirme'],
    relatedChakras: [5, 6, 7],
    relatedElements: ['Su', 'Hava'],
    relatedNumerology: [7, 11],
    relatedAstrology: ['Balık', 'Yay'],
    relatedEnneagram: [4, 5],
    relatedTotemThemes: ['üçlü yaprak açılımı', 'gökkuşağı tonları', 'kraliyet sembolü fleur-de-lis'],
    suitableFor: ['İçsel sezgilerine güvenmek ve ilahi ilham kapılarını açmak isteyenler'],
    avoidWhen: ['Topraksı kaba ve ağır endüstriyel kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Fleur-de-lis Stylized', 'Micro Realism'],
      bodyPlacements: ['Önkol', 'Omurga Üstü', 'Kaburga'],
      compositionRole: 'Tepe tacı veya dikey akışkan zarif merkez',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkezden üç yöne kıvrılan simetrik Fleur-de-lis hatları'
    },
    visualDescription: 'Üç yaprağı yukarı üç yaprağı aşağı kıvrılan zarif iris çiçeği ve ince botanik sap.',
    numerologyConnection: 'Yaşam Yolu 7 ve Üstat 11',
    astrologyConnection: 'Balık ve Yay',
    enneagramConnection: 'Tip 4 & Tip 5',
    visualKeywords: ['iris flower fine line', 'sacred lily linework', 'fleur de lis botanical iris']
  },
  {
    id: 'sym-chamomile-sage',
    name: 'Papatya & Adaçayı (Chamomile & White Sage)',
    category: 'Bitki/Çiçek',
    subcategory: 'Sadelik & Nazar Kalkanı',
    meaning: 'Gösterişsiz hakikat, ruhsal sadelik, nazar ve negatif enerjileri savuşturma, berrak zihin.',
    archetypes: ['Masum', 'Şifacı'],
    positiveThemes: ['arı bilinç', 'korunma', 'sadelik', 'dinginlik'],
    shadowThemes: ['kendi değerini küçümseme', 'aşırı naiflik'],
    relatedChakras: [3, 4],
    relatedElements: ['Hava', 'Ateş'],
    relatedNumerology: [2, 6],
    relatedAstrology: ['Yengeç', 'Başak'],
    relatedEnneagram: [9, 6],
    relatedTotemThemes: ['tütsü dumanı', 'beyaz taç yapraklar', 'güneş gözü'],
    suitableFor: ['Karmaşık dünyadan uzaklaşıp sadeleşmek ve negatif enerjilerden korunmak isteyenler'],
    avoidWhen: ['Görkemli, maksimalist ve agresif güç sembolü arayanlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Minimalist', 'Botanical Bouquet'],
      bodyPlacements: ['Bilek', 'Köprücük Altı', 'Ayak Bileği'],
      compositionRole: 'Zarif köşe tamamlayıcısı veya mikro tılsım',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dairesel sarı merkez ve çevresinde eşit aralıklı küçük yaylar'
    },
    visualDescription: 'Küçük beyaz papatyalar ve yanında adaçayı yapraklarının hafif kıvrımlı hatları.',
    numerologyConnection: 'Yaşam Yolu 2 ve 6',
    astrologyConnection: 'Yengeç ve Başak',
    enneagramConnection: 'Tip 9 & Tip 6',
    visualKeywords: ['chamomile flower linework', 'sage leaves botanical', 'simple delicate white flowers']
  },
  {
    id: 'sym-thistle-cactus',
    name: 'Devedikeni & Kaktüs (Thistle & Desert Cactus)',
    category: 'Bitki/Çiçek',
    subcategory: 'Dokunulmaz Kutsallık & Çöl Direnci',
    meaning: 'Sert koşullarda açan çiçek, dokunulmaz kutsal sınırlar, kırılmaz direnç ve içsel su hazinesi.',
    archetypes: ['Savaşçı', 'Koruyucu'],
    positiveThemes: ['çelik gibi irade', 'sınır koruma', 'kıtlıkta bile yaşama', 'özgün zarafet'],
    shadowThemes: ['kimseyi yaklaştırmama', 'sivrilik'],
    relatedChakras: [1, 3],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [1, 4],
    relatedAstrology: ['Koç', 'Oğlak', 'Akrep'],
    relatedEnneagram: [8, 6],
    relatedTotemThemes: ['keskin dikenler', 'mor tepe çiçeği', 'çöl direnci'],
    suitableFor: ['Kişisel sınırlarını net korumak ve en zorlu koşullarda bile dimdik kalmak isteyenler'],
    avoidWhen: ['Yumuşak teslimiyet ve tamamen gardını indirme odaklı süreçler'],
    designCompatibility: {
      recommendedStyles: ['Etching / Gravür', 'Blackwork', 'Fine Line Botanical'],
      bodyPlacements: ['Önkol Dış', 'Baldır', 'Omuz Yanı'],
      compositionRole: 'Koruyucu zırh motifi veya alt kaide savunma hattı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Çapraz kesişen geometrik diken kafesi ve radyal tepe patlaması'
    },
    visualDescription: 'Geometrik açılı dikenli gövde ve üzerinde asilce açan mor püsküllü devedikeni çiçeği.',
    numerologyConnection: 'Yaşam Yolu 1 ve 4',
    astrologyConnection: 'Koç ve Oğlak',
    enneagramConnection: 'Tip 8 & Tip 6',
    visualKeywords: ['scottish thistle linework', 'desert cactus flower', 'thorny botanical protective tattoo']
  },
  {
    id: 'sym-peony',
    name: 'Şakayık Çiçeği (Peony)',
    category: 'Bitki/Çiçek',
    subcategory: 'Görkemli Asalet & Ruhsal Çiçeklenme',
    meaning: 'Bolluk, ruhsal ihtişam, onur, yaraları şifalandıran kutsal çiçek ve cesurca tüm katmanlarını dünyaya açma.',
    archetypes: ['Hükümdar', 'Aşık'],
    positiveThemes: ['ruhsal zenginlik', 'ihtişamlı zarafet', 'şifa', 'onurlu duruş'],
    shadowThemes: ['kibir', 'gösteriş düşkünlüğü'],
    relatedChakras: [4, 2],
    relatedElements: ['Su', 'Ateş'],
    relatedNumerology: [3, 8],
    relatedAstrology: ['Aslan', 'Boğa', 'Terazi'],
    relatedEnneagram: [3, 4],
    relatedTotemThemes: ['kat kat açılan taç yapraklar', 'bahar asilliği', 'çiçeklerin kraliçesi'],
    suitableFor: ['Kendi değerini tam anlamıyla kabul edip kalbini cesurca genişletmek isteyenler'],
    avoidWhen: ['Aşırı sert veya agresif askeri kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Neo-Traditional', 'Fine Line Botanical', 'Japanese Irezumi Motif'],
      bodyPlacements: ['Omuz Başı', 'Uyluk', 'Önkol', 'Sırt'],
      compositionRole: 'Odak noktası ana çiçek motifi veya akıcı dolgu',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İç içe geçen spiral dalgalı taç yaprak katmanları'
    },
    visualDescription: 'Zengin katmanlı, hacimli açılmış taç yaprakları olan görkemli şakayık çiçeği.',
    numerologyConnection: 'Yaşam Yolu 3 ve 8',
    astrologyConnection: 'Aslan ve Terazi',
    enneagramConnection: 'Tip 3 & Tip 4',
    visualKeywords: ['botanical peony flower', 'layered peony linework', 'blooming peony tattoo design']
  },
  {
    id: 'sym-bodhi-tree',
    name: 'Bodhi Uyanış Ağacı (Sacred Bodhi Tree)',
    category: 'Bitki/Çiçek',
    subcategory: 'Aydınlanma & Zihinsel Dinginlik',
    meaning: 'Gautama Buda\'nın altında uyanışa ulaştığı kutsal incir ağacı; illüzyonların ötesini görme, derin köklenme ve mutlak zihinsel berraklık.',
    archetypes: ['Bilge', 'Münzevi'],
    positiveThemes: ['uyanış', 'dinginlik', 'köklenme', 'illüzyondan kurtuluş'],
    shadowThemes: ['dünyadan kopukluk', 'pasif bekleme'],
    relatedChakras: [6, 7],
    relatedElements: ['Toprak', 'Eter'],
    relatedNumerology: [7, 9],
    relatedAstrology: ['Yay', 'Kova', 'Balık'],
    relatedEnneagram: [5, 9],
    relatedTotemThemes: ['kalp formunda damarlı yapraklar', 'kadim gövde', 'sonsuz sükûnet'],
    suitableFor: ['İçsel fırtınaları dindirmek, meditasyon ve zihinsel uyanış arayanlar'],
    avoidWhen: ['Hızlı tempolu, agresif savaşçı arketip tasarımları'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Dotwork', 'Sacred Geometric Botanical', 'Minimalist'],
      bodyPlacements: ['Ense / Üst Sırt', 'Önkol İç', 'Göğüs Kafesi'],
      compositionRole: 'Merkezi uyanış ekseni veya kök-taç dengesi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Sivri damla/kalp formunda tek bir yaprak ve iç damar fraktalı'
    },
    visualDescription: 'Kalp formundaki karakteristik ince damarlı Bodhi yaprakları ve kutsal uyanış ağacı formu.',
    numerologyConnection: 'Yaşam Yolu 7 ve 9',
    astrologyConnection: 'Yay ve Balık',
    enneagramConnection: 'Tip 5 & Tip 9',
    visualKeywords: ['sacred bodhi leaf', 'ficus religiosa sacred tree', 'enlightenment bodhi tattoo linework']
  },
  {
    id: 'sym-poppy',
    name: 'Gelincik & Haşhaş (Poppy Flower)',
    category: 'Bitki/Çiçek',
    subcategory: 'Rüyalar & Derin Hafıza',
    meaning: 'Bilinçaltı rüyaları, derin uyku, ölümsüz hatıralar, narin görünen fakat kökünden dirilen kırılgan güç.',
    archetypes: ['Büyücü', 'Aşık'],
    positiveThemes: ['derin rüya vizyonu', 'huzurlu hafıza', 'duygusal derinlik'],
    shadowThemes: ['uyuşukluk', 'geçmişe saplanıp kalma'],
    relatedChakras: [6, 2],
    relatedElements: ['Su', 'Toprak'],
    relatedNumerology: [2, 7],
    relatedAstrology: ['Balık', 'Akrep'],
    relatedEnneagram: [4, 9],
    relatedTotemThemes: ['ipeksi narin taç yapraklar', 'kapsül tohum merkezi', 'kırmızı/siyah zıtlığı'],
    suitableFor: ['Kendi rüya alemine, geçmiş hatıralarına saygı duyan ve duygusal zenginliği kucaklayanlar'],
    avoidWhen: ['Sert ve duygusuz metalik tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line', 'Micro Realism', 'Single Needle Botanical'],
      bodyPlacements: ['Köprücük Kemiği', 'Bilek', 'Kaburga Yan'],
      compositionRole: 'İnce kavisli dal ve narin odak çiçeği',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Çember tohum kapsülü etrafında dalgalanan dairesel yaprak yayları'
    },
    visualDescription: 'İnce kıvrımlı zarif sap üzerinde narin yapraklı gelincik çiçeği ve tohum kozası.',
    numerologyConnection: 'Yaşam Yolu 2 ve 7',
    astrologyConnection: 'Balık ve Akrep',
    enneagramConnection: 'Tip 4 & Tip 9',
    visualKeywords: ['poppy flower fine line', 'botanical poppy single needle', 'delicate poppy tattoo']
  },
  {
    id: 'sym-iris',
    name: 'İris & Süsen Çiçeği (Iris)',
    category: 'Bitki/Çiçek',
    subcategory: 'Gökkuşağı Köprüsü & İlahi Haberci',
    meaning: 'Yeryüzü ile gökyüzü arasındaki gökkuşağı köprüsü; bilgelik, cesaret, inanç ve üçüncü göz sezgisi.',
    archetypes: ['Rehber', 'Elçi'],
    positiveThemes: ['sezgisel haberleşme', 'üçlü denge', 'asil inanç', 'umut'],
    shadowThemes: ['kendini fazla yüceltme'],
    relatedChakras: [5, 6],
    relatedElements: ['Hava', 'Su'],
    relatedNumerology: [3, 5],
    relatedAstrology: ['Yay', 'Kova', 'Terazi'],
    relatedEnneagram: [1, 7],
    relatedTotemThemes: ['üç yukarı üç aşağı taç yaprak', 'kraliyet moru ve altın', 'zarif kılıç formu yapraklar'],
    suitableFor: ['İç sesine güvenen, ruhsal rehberlik ve vizyon sahibi olanlar'],
    avoidWhen: ['Tamamen dünyevi ve kaba kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Botanical', 'Geometric Art Nouveau', 'Etching'],
      bodyPlacements: ['Önkol', 'Omurga Hattı', 'Baldır'],
      compositionRole: 'Dikey akış ve üçlü taç yaprak denge merkezi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Fleur-de-lis benzeri üç yapraklı simetrik eksen'
    },
    visualDescription: 'Yukarı ve aşağı zarifçe açılan üçer yapraklı asil süsen çiçeği ve kılıçsı ince yaprakları.',
    numerologyConnection: 'Yaşam Yolu 3 ve 5',
    astrologyConnection: 'Yay ve Kova',
    enneagramConnection: 'Tip 1 & Tip 7',
    visualKeywords: ['iris flower linework', 'botanical iris flower tattoo', 'art nouveau iris illustration']
  },
  {
    id: 'sym-orchid',
    name: 'Kutsal Orkide (Sacred Orchid)',
    category: 'Bitki/Çiçek',
    subcategory: 'Nadir Asalet & Egzotik Zarafet',
    meaning: 'Zor bulunan nadide içsel güzellik, yüksek zevkler, narin görünen fakat kökleriyle kayalara tutunan direnç.',
    archetypes: ['Aşık', 'Münzevi'],
    positiveThemes: ['nadir zarafet', 'özgün güzellik', 'dirençli kökler', 'derin çekicilik'],
    shadowThemes: ['kendini fazla ulaşılamaz kılma'],
    relatedChakras: [2, 4],
    relatedElements: ['Su', 'Hava'],
    relatedNumerology: [6, 9],
    relatedAstrology: ['Venüs', 'Terazi', 'Balık'],
    relatedEnneagram: [4],
    relatedTotemThemes: ['egzotik kavisli yapraklar', 'narin orta dudak', 'havada asılı kökler'],
    suitableFor: ['Kendi özgünlüğünü ve nadir rastlanan karakterini kutlamak isteyenler'],
    avoidWhen: ['Kaba, sert ve endüstriyel kompozisyonlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Botanical', 'Micro Realism', 'Single Needle'],
      bodyPlacements: ['Köprücük Kemiği', 'Bilek', 'Kaburga Yanı'],
      compositionRole: 'Zarif kavisli odak çiçeği veya asil vurgu',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Üç simetrik dış çanak yaprak ve merkezde kavisli iç damla formu'
    },
    visualDescription: 'İnce kavisli dal üzerinde açan, karakteristik egzotik taç yapraklarıyla tekil orkide çiçeği.',
    numerologyConnection: 'Yaşam Yolu 6 ve 9',
    astrologyConnection: 'Terazi ve Balık',
    enneagramConnection: 'Tip 4 (Özgün Bireyci)',
    visualKeywords: ['orchid flower tattoo linework', 'delicate botanical orchid fine line', 'exotic orchid single needle']
  },
  {
    id: 'sym-acanthus',
    name: 'Akantus Yaprağı (Acanthus Leaf)',
    category: 'Bitki/Çiçek',
    subcategory: 'Ölümsüz Mimari & Direnç',
    meaning: 'Zorlu engellerin içinden filizlenen ölümsüz güzellik, antik tapınak sütunlarının asil süsü ve zarafetle taşınan dayanıklılık.',
    archetypes: ['Mimar', 'Savaşçı'],
    positiveThemes: ['aşılmaz engelleri aşma', 'mimari estetik', 'ölümsüzlük', 'direnç'],
    shadowThemes: ['aşırı süslemecilik'],
    relatedChakras: [1, 4],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [4, 8],
    relatedAstrology: ['Oğlak', 'Boğa', 'Koç'],
    relatedEnneagram: [1, 8],
    relatedTotemThemes: ['korinto sütun başı', 'kavisli dişli yaprak', 'kayadan fışkıran bitki'],
    suitableFor: ['Hayatın zorlu taşlarını zarafetle aşıp kendi anıtını inşa edenler'],
    avoidWhen: ['Aşırı basit, ilkel veya karikatürize tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Ornate / Barok', 'Engraving / Gravür', 'Blackwork'],
      bodyPlacements: ['Pazu Çevresi', 'Kürek Kemiği', 'Göğüs Altı'],
      compositionRole: 'Kompozisyonu saran kıvrımlı bordür veya kaide çerçevesi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Sarmal logaritmik kavisler ve sivri dişli simetrik dilimler'
    },
    visualDescription: 'Antik Yunan Korinto sütun başlıklarını andıran zengin kıvrımlı ve dişli akantus yaprağı.',
    numerologyConnection: 'Yaşam Yolu 4 ve 8',
    astrologyConnection: 'Oğlak ve Boğa',
    enneagramConnection: 'Tip 1 & Tip 8',
    visualKeywords: ['acanthus leaf ornamental', 'corinthian capital acanthus linework', 'architectural botanical engraving']
  }
];
