import { SymbolLibraryItem } from '../../types';

export const SACRED_OBJECT_SYMBOLS: SymbolLibraryItem[] = [
  {
    id: 'sym-dagger',
    name: 'Ritüel Hançeri & Kılıç (Ritual Dagger / Athame / Sword)',
    category: 'Kutsal Obje',
    subcategory: 'Zihinsel Berraklık & Savunma',
    meaning: 'Zihinsel berraklık, zararlı bağları kesme, mutlak savunma, adalet ve illüzyonları yok etme iradesi.',
    archetypes: ['Savaşçı', 'Simyacı', 'Yargıç'],
    positiveThemes: ['bağları kesme', 'zihinsel netlik', 'sınırları koruma', 'cesaret'],
    shadowThemes: ['saldırganlık', 'kalpsiz acımasızlık'],
    relatedChakras: [1, 3, 5],
    relatedElements: ['Hava', 'Ateş'],
    relatedNumerology: [1, 8],
    relatedAstrology: ['Koç', 'İkizler', 'Akrep'],
    relatedEnneagram: [8, 1],
    relatedTotemThemes: ['çift ağızlı çelik', 'yılan sarılı kabza', 'ay delen bıçak'],
    suitableFor: ['Kişisel sınırlarını ihlal eden toksik bağları koparmak ve kararlılık kazanmak isteyenler'],
    avoidWhen: ['Yalnızca yumuşak teslimiyet ve şefkat odaklı pasif süreçler'],
    designCompatibility: {
      recommendedStyles: ['Gothic Fine Line', 'Neo-Traditional', 'Engraving / Gravür'],
      bodyPlacements: ['Önkol İç', 'Omurga', 'Baldır', 'Kaburga'],
      compositionRole: 'Dikey omurga taşıyıcısı veya merkezi odak silahı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dikey simetri ekseni, dar baklava formunda bıçak ve yatay balçak çizgisi'
    },
    visualDescription: 'Oyma süslemeli kabza, keskin çift ağızlı namlu, etrafına sarılan sarmaşık veya yılan motifi.',
    numerologyConnection: 'Yaşam Yolu 1 ve 8',
    astrologyConnection: 'Koç, İkizler ve Akrep',
    enneagramConnection: 'Tip 8 & Tip 1',
    visualKeywords: ['ornate gothic dagger', 'sword wrapped in snake', 'blade piercing moon', 'filigree hilt dagger']
  },
  {
    id: 'sym-hourglass',
    name: 'Zaman Kum Saati (Hourglass & Chronos)',
    category: 'Kutsal Obje',
    subcategory: 'Zamanın Değeri & Memento Mori',
    meaning: 'Zamanın kıymeti (Memento Mori), akışın döngüselliği, kum tanelerinin sabrı ve yaşamın kutsallığı.',
    archetypes: ['Bilge', 'Zaman Muhafızı'],
    positiveThemes: ['anın kıymetini bilme', 'sabır', 'döngüsel kabul', 'fani dünyanın bilgeliği'],
    shadowThemes: ['yaşlanma ve ölüm korkusu', 'zaman darlığı anksiyetesi'],
    relatedChakras: [1, 7],
    relatedElements: ['Toprak', 'Zaman / Eter'],
    relatedNumerology: [4, 9],
    relatedAstrology: ['Oğlak', 'Kova'],
    relatedEnneagram: [1, 5],
    relatedTotemThemes: ['ince boğaz', 'akan kum taneleri', 'kanatlı kum saati'],
    suitableFor: ['Hayatındaki zamanın değerini idrak eden ve hedeflerine sabırla odaklanmak isteyenler'],
    avoidWhen: ['Zaman baskısından aşırı tükenmiş ve anksiyete yaşayan kişilerde tetikleyici olabilir'],
    designCompatibility: {
      recommendedStyles: ['Classical Engraving', 'Fine Line Dotwork', 'Black & Grey'],
      bodyPlacements: ['Önkol Dış', 'Pazu', 'Baldır'],
      compositionRole: 'Merkezi felsefi odak veya alt dengeleyici armatür',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Tepeleri birleşen iki üçgen ve dikey kum akış çizgisi'
    },
    visualDescription: 'İnce cam hazneler, içinde süzülen mikro kum taneleri ve ahşap/bronz oymalı taşıyıcı sütunlar.',
    numerologyConnection: 'Yaşam Yolu 4 ve 9',
    astrologyConnection: 'Oğlak (Satürn zamanı)',
    enneagramConnection: 'Tip 1 & Tip 5',
    visualKeywords: ['vintage hourglass running sand', 'winged hourglass', 'celestial sands of time']
  },
  {
    id: 'sym-compass',
    name: 'Kozmik Pusula & Rüzgar Gülü (Cosmic Compass)',
    category: 'Kutsal Obje',
    subcategory: 'Hakiki Yön & Kozmik Rehberlik',
    meaning: 'İçsel yön bulma, hayat fırtınalarında kaybolmama, hakiki kuzeyi takip etme ve ruhsal pusula.',
    archetypes: ['Gezgin', 'Kâşif', 'Kılavuz'],
    positiveThemes: ['doğru rotada kalma', 'içsel pusula', 'keşif tutkusu', 'güven'],
    shadowThemes: ['yönünü kaybetme korkusu', 'kararsızlık'],
    relatedChakras: [3, 6],
    relatedElements: ['Hava', 'Su'],
    relatedNumerology: [5, 7],
    relatedAstrology: ['Yay', 'Balık'],
    relatedEnneagram: [7, 6],
    relatedTotemThemes: ['manyetik iğne', 'kuzey yıldızı', 'rüzgar gülü kadranı'],
    suitableFor: ['Hayatında yeni bir rota çizen, seyahat eden ve içsel pusulasına güvenmek isteyenler'],
    avoidWhen: ['Sabit, değişmez ve hareketsiz kalmayı seçen monolitik temalar'],
    designCompatibility: {
      recommendedStyles: ['Nautical Fine Line', 'Geometric Compass', 'Dotwork Map'],
      bodyPlacements: ['Önkol', 'Omuz Başı', 'Kürek Kemiği', 'Bilek'],
      compositionRole: 'Merkezi dairesel navigasyon kadranı veya arka plan kılavuzu',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dört ana yön oku, sekizgen rüzgar gülü ve dereceli eşmerkezli çemberler'
    },
    visualDescription: 'Antik bronz pusula kasası, ince kadran çizgileri, yön okları ve merkezinde parlayan kuzey yıldızı.',
    numerologyConnection: 'Yaşam Yolu 5 ve 7',
    astrologyConnection: 'Yay ve Balık',
    enneagramConnection: 'Tip 7 & Tip 6',
    visualKeywords: ['nautical antique compass', 'geometric compass rose', 'star compass with runes']
  },
  {
    id: 'sym-key',
    name: 'Kadim Anahtar (Skeleton Key of Mysteries)',
    category: 'Kutsal Obje',
    subcategory: 'Kilitli Kapılar & Bilinçaltı Yetkisi',
    meaning: 'Kilitli kapıları ve gizli potansiyelleri açma, bilinçaltı sırları, ruhsal yetki ve inisiyasyon.',
    archetypes: ['Muhafız', 'Büyücü', 'İnisiyatör'],
    positiveThemes: ['kapıları açma yetkisi', 'gizli potansiyel', 'özgürleşme', 'derin merak'],
    shadowThemes: ['sırların yükü', 'kendini kapalı tutma'],
    relatedChakras: [5, 6, 7],
    relatedElements: ['Toprak', 'Hava'],
    relatedNumerology: [7, 11],
    relatedAstrology: ['Akrep', 'Kova'],
    relatedEnneagram: [5, 4],
    relatedTotemThemes: ['oymalı tepe halkası', 'dişli uç', 'kanatlı anahtar'],
    suitableFor: ['Kendi içsel kapılarını açmak ve hayatında yeni fırsatların kilidini çevirmek isteyenler'],
    avoidWhen: ['Yalnızca açık, duvarsız ve kapısız yalın doğa temaları'],
    designCompatibility: {
      recommendedStyles: ['Victorian Fine Line', 'Gothic Filigree', 'Micro Realism'],
      bodyPlacements: ['Köprücük Kemiği', 'Önkol İç', 'Bilek', 'Ense Altı'],
      compositionRole: 'Tamamlayıcı asil tılsım veya kolyemsi dikey odak',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Yonca/üçgen başlı halka, düz şaft ve labirent diş geometrisi'
    },
    visualDescription: 'Filigran işlemeli tepe rozeti, üzerinde küçük kuru kafa veya ay motifi ve antik kilit dişleri.',
    numerologyConnection: 'Yaşam Yolu 7 ve Üstat 11',
    astrologyConnection: 'Akrep ve Kova',
    enneagramConnection: 'Tip 5 & Tip 4',
    visualKeywords: ['ornate antique key', 'key with skull head', 'winged key of knowledge', 'fine line key']
  },
  {
    id: 'sym-holy-grail',
    name: 'Kutsal Kâse (Holy Grail)',
    category: 'Kutsal Obje',
    subcategory: 'Ruhani Doyum & Şefkat Kabı',
    meaning: 'Tükenmez ruhsal doyum, kalp çakrasının alıcı kabı, şefkat, arınma ve hakiki mutluluk arayışı.',
    archetypes: ['Arayışçı', 'Şifacı', 'Masum'],
    positiveThemes: ['kalp kabı', 'ruhani zenginlik', 'bereket akışı', 'sevgiye açılma'],
    shadowThemes: ['dipsiz boşluk hissi', 'doyumsuzluk'],
    relatedChakras: [4, 2],
    relatedElements: ['Su'],
    relatedNumerology: [2, 6, 9],
    relatedAstrology: ['Yengeç', 'Balık'],
    relatedEnneagram: [2, 4],
    relatedTotemThemes: ['altın kadeh', 'taşan su/ışık', 'akantus yapraklı ayak'],
    suitableFor: ['Duygusal ve ruhani doyum arayan, kalbini sevgiye bir kadeh gibi açmak isteyenler'],
    avoidWhen: ['Saldırgan, yıkıcı ve savaşçı militarist tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Medieval Engraving', 'Fine Line Classical', 'Dotwork Shading'],
      bodyPlacements: ['Göğüs Merkezi', 'Önkol İç', 'Kaburga'],
      compositionRole: 'Alt kaide kadehi veya merkez kutsal nesnesi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Yukarı bakan yarım daire kase, dikey ince sap ve taban elipsi'
    },
    visualDescription: 'İnce oymalı kadeh, içinden yukarı süzülen ışık ışınları ve tabanında lotus/akantus yaprakları.',
    numerologyConnection: 'Yaşam Yolu 2 ve 6',
    astrologyConnection: 'Yengeç ve Balık (Su Kasesi)',
    enneagramConnection: 'Tip 2 & Tip 4',
    visualKeywords: ['holy grail chalice linework', 'sacred cup of light', 'medieval communion grail tattoo']
  },
  {
    id: 'sym-square-compasses',
    name: 'Gönye ve Pergel (Square and Compasses)',
    category: 'Kutsal Obje',
    subcategory: 'Kozmik Mimari & Sınırların Dengesi',
    meaning: 'Gönye (madde, ahlaki doğruluk) ve Pergel (ruh, tutkuların sınırlandırılması); evrensel mimari ve denge.',
    archetypes: ['Mimar', 'Bilge'],
    positiveThemes: ['öz-disiplin', 'doğruluk', 'ölçülü yaşam', 'inşa etme gücü'],
    shadowThemes: ['katı kurallar', 'aşırı dogmatizm'],
    relatedChakras: [1, 4, 6],
    relatedElements: ['Toprak', 'Hava'],
    relatedNumerology: [4, 22],
    relatedAstrology: ['Oğlak', 'Başak'],
    relatedEnneagram: [1, 5],
    relatedTotemThemes: ['90 derece gönye', 'açılan pergel', 'merkez G harfi / göz'],
    suitableFor: ['Kendi hayatını mimari bir ustalıkla, disiplin ve doğrulukla inşa etmek isteyenler'],
    avoidWhen: ['Serseri, tamamen dağınık ve kuralsız bohem yaklaşımlar'],
    designCompatibility: {
      recommendedStyles: ['Architectural Linework', 'Fine Line Masonic', 'Geometric Vector'],
      bodyPlacements: ['Önkol', 'Kürek Kemiği', 'Baldır'],
      compositionRole: 'Merkezi geometrik mimari çerçeve veya armatür',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İki bacaklı açı pergeli ve altına geçen 90 derece dik açı cetveli'
    },
    visualDescription: 'Kesişen pergel bacakları ve dik açılı gönye, merkezinde altın oran kılavuz çizgileri.',
    numerologyConnection: 'Yaşam Yolu 4 ve Üstat 22',
    astrologyConnection: 'Oğlak ve Başak',
    enneagramConnection: 'Tip 1 & Tip 5',
    visualKeywords: ['square and compasses linework', 'architectural sacred geometry tools', 'freemason masonic emblem']
  },
  {
    id: 'sym-hermit-lantern',
    name: 'Mistik Fener & Hermit Lambası (The Hermit Lantern)',
    category: 'Kutsal Obje',
    subcategory: 'İçsel Işık & İnziva Bilgeliği',
    meaning: 'Karanlıkta başkalarının onayına ihtiyaç duymadan sadece kendi içsel ışığıyla yürümek; arayış ve olgunluk.',
    archetypes: ['Münzevi', 'Bilge', 'Kılavuz'],
    positiveThemes: ['içsel rehberlik', 'bağımsız ışık', 'yalnızlığın asaleti', 'hakikat arayışı'],
    shadowThemes: ['toplumdan aşırı soyutlanma', 'kibirli inziva'],
    relatedChakras: [3, 6],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [9, 7],
    relatedAstrology: ['Başak', 'Oğlak'],
    relatedEnneagram: [5, 4],
    relatedTotemThemes: ['altı köşeli yıldız ışığı', 'antik cam fener', 'gece yürüyüşü'],
    suitableFor: ['Kendi yolunu aydınlatmak ve içsel rehberine güvenerek tek başına yürümekten korkmayanlar'],
    avoidWhen: ['Yalnızca gürültülü eğlence ve dışa dönük şov temaları'],
    designCompatibility: {
      recommendedStyles: ['Tarot Card Engraving', 'Fine Line', 'Micro Realism'],
      bodyPlacements: ['Önkol İç', 'Kaburga', 'Pazu'],
      compositionRole: 'Merkezi dikey ışık kaynağı veya gece kompozisyonu kalbi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Altıgen fener kafesi, askı halkası ve merkezden çıkan radyal ışınlar'
    },
    visualDescription: 'Cam fener içinde parlayan 6 köşeli yıldız ışığı, antik metal kafes ve ince zincir askısı.',
    numerologyConnection: 'Yaşam Yolu 9 (Hermit / Münzevi) ve 7',
    astrologyConnection: 'Başak (Tarot IX The Hermit)',
    enneagramConnection: 'Tip 5 & Tip 4',
    visualKeywords: ['the hermit lantern tarot tattoo', 'antique brass lantern fine line', 'inner light lantern tattoo']
  },
  {
    id: 'sym-scales-of-justice',
    name: 'Adalet Terazisi (Scales of Justice / Maat)',
    category: 'Kutsal Obje',
    subcategory: 'Mutlak Eşitlik & Karma Dengesi',
    meaning: 'Eylemlerin ve niyetlerin eşit tartılması; karma, tarafsız dürüstlük, hakkaniyet ve vicdani huzur.',
    archetypes: ['Yargıç', 'Hakkaniyetli'],
    positiveThemes: ['mutlak adalet', 'vicdan berraklığı', 'denge', 'dürüstlük'],
    shadowThemes: ['sürekli hesap kitap yapma', 'bağışlayamama'],
    relatedChakras: [4, 5],
    relatedElements: ['Hava'],
    relatedNumerology: [8, 6],
    relatedAstrology: ['Terazi'],
    relatedEnneagram: [1],
    relatedTotemThemes: ['iki kefe', 'merkez terazi mili', 'yatay denge kirişi'],
    suitableFor: ['Hayatında adalet, dürüstlük ve karma dengesini en yüksek ilke edinenler'],
    avoidWhen: ['Kaotik, fevri ve tek taraflı tarafgir temalar'],
    designCompatibility: {
      recommendedStyles: ['Classical Fine Line', 'Geometric Balance', 'Dotwork Scales'],
      bodyPlacements: ['Sırt Tam Merkez', 'Önkol', 'Göğüs Kafesi Ortası'],
      compositionRole: 'Merkezi simetri ekseni ve yatay denge unsuru',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Yatay denge çizgisi, tepe asma halkası ve iki yanda asılı eşkenar üçgen kefeler'
    },
    visualDescription: 'Kusursuz dengede duran iki terazi kefesi, üzerinde ince zincirler ve merkez sütun.',
    numerologyConnection: 'Yaşam Yolu 8 (Adalet ve Karma) ve 6',
    astrologyConnection: 'Terazi (Zodyak Terazisi)',
    enneagramConnection: 'Tip 1 (Doğruluk)',
    visualKeywords: ['scales of justice linework', 'libra balance scales tattoo', 'maat scales of truth']
  },
  {
    id: 'sym-astrolabe',
    name: 'Usturlap & Göksel Zaman Ölçer (Ancient Astrolabe)',
    category: 'Kutsal Obje',
    subcategory: 'Yıldız Navigasyonu & Kozmik Koordinat',
    meaning: 'Yıldızların konumunu ve göksel zamanı hesaplayan kadim alet; evrenle uyumlu zamanlama ve yüksek akıl.',
    archetypes: ['Kozmik Kâşif', 'Bilim İnsanı', 'Simyacı'],
    positiveThemes: ['doğru zamanlama', 'yıldızlarla uyum', 'derin bilimsel zarafet', 'yön tayini'],
    shadowThemes: ['her şeyi hesaplamaya çalışırken anı kaçırma'],
    relatedChakras: [6, 7],
    relatedElements: ['Hava', 'Eter'],
    relatedNumerology: [7, 5],
    relatedAstrology: ['Kova', 'Yay'],
    relatedEnneagram: [5, 7],
    relatedTotemThemes: ['dönen rete halkası', 'zodyak göstergeleri', 'astronomik kadran'],
    suitableFor: ['Astroloji, astronomi, zamanlama ve göksel nizamla ilgilenen entelektüel ruhlar'],
    avoidWhen: ['Basit, kaba ve ilkel kaba çizgili tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Intricate Fine Line', 'Engraving / Gravür', 'Astronomical Vector'],
      bodyPlacements: ['Önkol İç', 'Sırt Kürek Kemiği', 'Pazu'],
      compositionRole: 'Merkezi zengin kadran veya gezegensel yörünge armatürü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'İç içe geçmiş göksel koordinat halkaları ve zodyak açılı rete iğneleri'
    },
    visualDescription: 'Pirinç astrolab diski, üzerinde dönen yıldız koordinat rete ağı ve narin arapça/latince takımyıldız işaretleri.',
    numerologyConnection: 'Yaşam Yolu 7 ve 5',
    astrologyConnection: 'Kova ve Yay',
    enneagramConnection: 'Tip 5 & Tip 7',
    visualKeywords: ['antique astrolabe linework', 'astronomical navigation device tattoo', 'celestial clock astrolabe']
  },
  {
    id: 'sym-sigil-ring',
    name: 'Mühür Yüzüğü & Kadim Mühür (Sigil Ring / Seal)',
    category: 'Kutsal Obje',
    subcategory: 'Bireysel Otorite & Yemin',
    meaning: 'Bireyin kendi sözünün arkasında durması, kişisel otorite, gizli yemin ve ruhani kimliğin tescili.',
    archetypes: ['Hükümdar', 'İnisiyatör'],
    positiveThemes: ['sözünün eri olma', 'kişisel egemenlik', 'sır tutma', 'onur'],
    shadowThemes: ['aşırı otoriterlik', 'esneyememe'],
    relatedChakras: [1, 5],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [1, 8],
    relatedAstrology: ['Aslan', 'Oğlak'],
    relatedEnneagram: [8, 1],
    relatedTotemThemes: ['balmumu mühür', 'kraliyet arması', 'kazağı yüzük'],
    suitableFor: ['Kendi hayatının tek hükümdarı olduğunu ilan eden ve sözüne sadık olanlar'],
    avoidWhen: ['Bağsız, sorumsuz ve uçucu temalar'],
    designCompatibility: {
      recommendedStyles: ['Classical Engraving', 'Fine Line Signet', 'Micro Detail'],
      bodyPlacements: ['Parmak', 'Bilek', 'Önkol Kaidesi'],
      compositionRole: 'Tasarımın alt imza mührü veya merkezi hanedan arması',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dairesel çerçeve içinde kişisel monogram veya geometrik sigil kodu'
    },
    visualDescription: 'Ağır antik mühür yüzüğü, tablasında kişisel geometrik sigil ve etrafında ince oyma desenler.',
    numerologyConnection: 'Yaşam Yolu 1 ve 8',
    astrologyConnection: 'Aslan ve Oğlak',
    enneagramConnection: 'Tip 8 & Tip 1',
    visualKeywords: ['signet ring sigil tattoo', 'royal seal ring linework', 'wax seal stamp antique']
  },
  {
    id: 'sym-obsidian-mirror',
    name: 'Kadim Obsidyen Aynası (Obsidian Scrying Mirror)',
    category: 'Kutsal Obje',
    subcategory: 'Öz-Yüzleşme & İllüzyon Kırıcı',
    meaning: 'Volkanik siyah cam ayna (Tezcatlipoca aynası); illüzyonları kırma, gölgeyle korkusuz yüzleşme ve kehanet.',
    archetypes: ['Simyacı', 'Büyücü', 'Gölge Rehberi'],
    positiveThemes: ['öz-yüzleşme', 'illüzyonları yok etme', 'gölge bilgeliği', 'hakikati görme'],
    shadowThemes: ['kendi kusurlarında boğulma', 'korku'],
    relatedChakras: [1, 6],
    relatedElements: ['Toprak', 'Ateş'],
    relatedNumerology: [7, 8],
    relatedAstrology: ['Akrep'],
    relatedEnneagram: [4, 8],
    relatedTotemThemes: ['siyah ayna', 'volkanik cam', 'dumanlı yansıma'],
    suitableFor: ['Kendi gölgesinden kaçmayıp onunla yüzleşerek gerçek aydınlanmaya ulaşanlar'],
    avoidWhen: ['Yalnızca yüzeysel neşe ve derinliksiz hafif işler'],
    designCompatibility: {
      recommendedStyles: ['Blackwork Contrast', 'Fine Line Frame', 'Dark Mystical'],
      bodyPlacements: ['Önkol', 'Göğüs', 'Sırt'],
      compositionRole: 'Merkezi derinlik kuyusu veya çerçeve portalı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Kusursuz siyah dairesel disk ve etrafında geometrik güneş/yılan çerçevesi'
    },
    visualDescription: 'Pürüzsüz parlak siyah ayna diski, etrafında aztek/antik yılan işlemeli taş çerçeve.',
    numerologyConnection: 'Yaşam Yolu 7 ve 8',
    astrologyConnection: 'Akrep (Plüton Derinliği)',
    enneagramConnection: 'Tip 4 & Tip 8',
    visualKeywords: ['obsidian scrying mirror', 'black mirror occult linework', 'tezcatlipoca smoking mirror']
  },
  {
    id: 'sym-thread-of-fate',
    name: 'Kader İpliği & İğne (Thread of Fate / Moirai)',
    category: 'Kutsal Obje',
    subcategory: 'Hayatın İlmekleri & Seçimlerin Dokusu',
    meaning: 'Kader tanrıçalarının (Moirai / Nornlar) eğirdiği altın iplik; hayatın ilmek ilmek dokunması, seçimler ve kader bağı.',
    archetypes: ['Dokumacı', 'Kader Ustası'],
    positiveThemes: ['kendi kaderini dokuma', 'seçimlerin gücü', 'bağlantılı evren', 'zarafet'],
    shadowThemes: ['kader kurbanı hissetme'],
    relatedChakras: [4, 7],
    relatedElements: ['Hava', 'Eter'],
    relatedNumerology: [3, 9],
    relatedAstrology: ['Kova', 'Başak'],
    relatedEnneagram: [1, 4],
    relatedTotemThemes: ['altın iplik', 'kemik iğne', 'kader çilesi'],
    suitableFor: ['Hayatını bilinçli seçimlerle bir sanat eseri gibi ilmek ilmek örenler'],
    avoidWhen: ['Kaba, sert ve çizgisel olmayan blok tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Continuous Single-Line', 'Fine Line', 'Micro Realism'],
      bodyPlacements: ['Önkol Boydan Boya', 'Köprücük Kemiği', 'Parmak Sarmalı'],
      compositionRole: 'Tüm diğer sembollerin arasından geçen kesintisiz bağlantı çizgisi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Akışkan tek çizgi (continuous line) ve aradaki düğüm noktaları'
    },
    visualDescription: 'İnce bir iğnenin gözünden geçen ve dövmenin diğer hatlarına dolanan kesintisiz zarif iplik hattı.',
    numerologyConnection: 'Yaşam Yolu 3 ve 9',
    astrologyConnection: 'Kova ve Başak',
    enneagramConnection: 'Tip 1 & Tip 4',
    visualKeywords: ['thread of fate tattoo', 'needle and thread linework', 'moirai destiny thread tattoo']
  },
  {
    id: 'sym-censer-incense',
    name: 'Kutsal Buhurdan & Duman (Sacred Censer)',
    category: 'Kutsal Obje',
    subcategory: 'Arınma Buhuru & Duaların Yükselişi',
    meaning: 'Maddi ağırlığı yakıp kokuya dönüştürerek göğe yükselme; alan temizliği, hafifleme ve manevi arınma.',
    archetypes: ['Şifacı', 'Mistik'],
    positiveThemes: ['ağırlıklardan arınma', 'yükselen dua', 'alan temizliği', 'hafiflik'],
    shadowThemes: ['uçup gitme', 'dünyadan kaçış'],
    relatedChakras: [4, 7],
    relatedElements: ['Hava', 'Ateş'],
    relatedNumerology: [2, 9],
    relatedAstrology: ['Balık', 'Yay'],
    relatedEnneagram: [9, 2],
    relatedTotemThemes: ['asılı buhurdan', 'spiral duman hatları', 'köz ateşi'],
    suitableFor: ['Eski yüklerini geride bırakıp hafiflemek ve enerjetik alanını arındırmak isteyenler'],
    avoidWhen: ['Ağır, koyu ve maddiyata saplanma odaklı temalar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Smoke', 'Etching Censer', 'Dotwork Flow'],
      bodyPlacements: ['Kaburga', 'Önkol İç', 'Sırt'],
      compositionRole: 'Alt kaideden yukarı doğru süzülen duman akış köprüsü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Zincirli asma geometrisi ve yukarı yükselen akışkan sinüs eğrileri'
    },
    visualDescription: 'Zincirle asılı gotik delikli buhurdan ve deliklerinden göğe kıvrılarak yükselen ince duman çizgileri.',
    numerologyConnection: 'Yaşam Yolu 2 ve 9',
    astrologyConnection: 'Balık ve Yay',
    enneagramConnection: 'Tip 9 & Tip 2',
    visualKeywords: ['hanging censer incense tattoo', 'sacred smoke linework', 'botanical incense purification']
  },
  {
    id: 'sym-vajra-dorje',
    name: 'Vajra & Yıldırım Asası (Vajra / Dorje)',
    category: 'Kutsal Obje',
    subcategory: 'Yok Edilemez Hakikat Elması',
    meaning: 'Elmas sertliğinde yok edilemez hakikat ve cehaleti kesen göksel yıldırım; sarsılmaz zihinsel berraklık.',
    archetypes: ['Savaşçı Ruh', 'Aydınlanmış Bilge'],
    positiveThemes: ['yok edilemez hakikat', 'elmas zihin', 'cehaleti delme', 'sarsılmaz güç'],
    shadowThemes: ['aşırı tavizsizlik'],
    relatedChakras: [6, 7],
    relatedElements: ['Ateş', 'Eter'],
    relatedNumerology: [1, 11],
    relatedAstrology: ['Koç', 'Kova'],
    relatedEnneagram: [8, 5],
    relatedTotemThemes: ['çift başlı pençe', 'merkez küre bindu', 'yıldırım kıvılcımı'],
    suitableFor: ['Zihninde ve ruhunda kırılmaz bir çelik/elmas netliği kurmak isteyenler'],
    avoidWhen: ['Yumuşak, kararsız ve esnek teslimiyet süreçleri'],
    designCompatibility: {
      recommendedStyles: ['Tibetan Fine Line', 'Sacred Geometry Fusion', 'Engraving'],
      bodyPlacements: ['Önkol', 'Omurga', 'Pazu'],
      compositionRole: 'Merkezi güç asası veya koruyucu çapraz mühür',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Merkez küre ve iki yana açılan simetrik 4 veya 8 pençeli lotus kıvrımları'
    },
    visualDescription: 'Geleneksel Tibet vajrası; merkezde küre, iki ucunda kapanan lotus pençeleri ve şimşek hatları.',
    numerologyConnection: 'Yaşam Yolu 1 ve Üstat 11',
    astrologyConnection: 'Koç ve Kova',
    enneagramConnection: 'Tip 8 & Tip 5',
    visualKeywords: ['tibetan vajra dorje tattoo', 'indestructible diamond scepter linework', 'buddhist sacred weapon']
  },
  {
    id: 'sym-seal-of-solomon',
    name: 'Süleyman\'ın Mührü & Tılsımlı Yüzük (Seal of Solomon)',
    category: 'Kutsal Obje',
    subcategory: 'Görünmez Varlıklar Üzerinde Hüküm & İlahi Koruma',
    meaning: 'Elementler ve görünmez alemler üzerinde sarsılmaz adalet ve ilahi otorite; iki zıt üçgenin mükemmel dengesi ve negatif güçleri mühürleme.',
    archetypes: ['Hükümdar', 'Muhafız', 'Büyücü'],
    positiveThemes: ['tüm negatifliği mühürleme', 'ilahi adalet', 'elementler üzerinde otorite', 'koruyucu zırh'],
    shadowThemes: ['güç zehirlenmesi'],
    relatedChakras: [3, 6],
    relatedElements: ['Ateş', 'Su', 'Hava', 'Toprak'],
    relatedNumerology: [6, 1],
    relatedAstrology: ['Güneş', 'Aslan', 'Kova'],
    relatedEnneagram: [8, 1],
    relatedTotemThemes: ['iç içe iki üçgen', 'yüzük kaşı', 'koruyucu mühür'],
    suitableFor: ['Kişisel aurasını her türlü negatif etkiye karşı mühürlemek ve kendi hayatında mutlak otorite kurmak isteyenler'],
    avoidWhen: ['Yalnızca batıl inanç korkusuyla hareket eden pasif zihinler'],
    designCompatibility: {
      recommendedStyles: ['Classic Engraving', 'Sacred Line Geometry', 'Signet Ring Detail'],
      bodyPlacements: ['Bilek', 'Ense Altı', 'Önkol İç', 'Sternum'],
      compositionRole: 'Merkezi koruma odağı veya kalkan mührü',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dış çember içine oturan iç içe iki üçgen ve merkez nokta bindu'
    },
    visualDescription: 'Dairesel bir çerçeve içinde iç içe geçmiş iki eşkenar üçgen ve antik İbrani/Arap mühür yazıları.',
    numerologyConnection: 'Yaşam Yolu 6 ve 1',
    astrologyConnection: 'Aslan ve Kova',
    enneagramConnection: 'Tip 8 & Tip 1',
    visualKeywords: ['seal of solomon ring tattoo', 'protective hexagram talisman linework', 'king solomon seal symbol']
  },
  {
    id: 'sym-athame',
    name: 'Ritüel Athamesi & Koruma Bıçağı (Ritual Athame)',
    category: 'Kutsal Obje',
    subcategory: 'İllüzyonları Kesen İrade & Enerji Sınırları',
    meaning: 'Zarar vermek için değil, illüzyon bağlarını kesmek, kutsal çemberi çizmek ve kişisel alanı korumak için kullanılan kutsal bıçak.',
    archetypes: ['Simyacı', 'Savaşçı'],
    positiveThemes: ['bağ kesme', 'net sınırlar', 'illüzyonları yok etme', 'odaklanmış irade'],
    shadowThemes: ['kendine aşırı acımasız olma'],
    relatedChakras: [1, 3],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [1, 8],
    relatedAstrology: ['Koç', 'Akrep'],
    relatedEnneagram: [8, 1],
    relatedTotemThemes: ['çift ağızlı çelik bıçak', 'kara kabza', 'hilal koruma demiri'],
    suitableFor: ['Kendi enerjisini tüketen geçmiş bağları kararlılıkla kesip net sınırlar çekmek isteyenler'],
    avoidWhen: ['Yalnızca teslimiyet ve pasif kabullenme arayanlar'],
    designCompatibility: {
      recommendedStyles: ['Dark Fine Line', 'Engraving', 'Neo-Traditional Blade'],
      bodyPlacements: ['Önkol', 'Uyluk', 'Omurga'],
      compositionRole: 'Dikey keskinlik ekseni veya odak bıçağı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Dikey çift simetrik hat, sivri uç ve hilal kabza siperi'
    },
    visualDescription: 'Çift tarafı keskin çelik namlu, üzerinde astrolojik semboller kazınmış zarif ritüel hançeri.',
    numerologyConnection: 'Yaşam Yolu 1 ve 8',
    astrologyConnection: 'Koç ve Akrep',
    enneagramConnection: 'Tip 8 & Tip 1',
    visualKeywords: ['ritual athame dagger tattoo', 'sacred blade fine line linework', 'cord cutting athame tattoo']
  },
  {
    id: 'sym-anchor-hope',
    name: 'Kadim Umut Çapası (Sacred Anchor of Hope)',
    category: 'Kutsal Obje',
    subcategory: 'Fırtınada Köklenme & Sarsılmaz Güven',
    meaning: 'En sert deniz fırtınalarında bile gemiyi kayalara çarpmaktan koruyan çapa; ruhsal sığınak, derin inanç, köklenme ve umut.',
    archetypes: ['Denizci', 'Muhafız'],
    positiveThemes: ['fırtınada savrulmama', 'sarsılmaz köklenme', 'umut', 'sadakat'],
    shadowThemes: ['yerinden kımıldayamama', 'esnek olamama'],
    relatedChakras: [1, 4],
    relatedElements: ['Su', 'Toprak'],
    relatedNumerology: [4, 6],
    relatedAstrology: ['Boğa', 'Yengeç', 'Balık'],
    relatedEnneagram: [6, 1],
    relatedTotemThemes: ['çift kanatlı kanca', 'bağlantı halkası', 'halat sarmalı'],
    suitableFor: ['Hayat fırtınalarında savrulmadan kendi değerlerine sımsıkı tutunup köklenmek isteyenler'],
    avoidWhen: ['Sürekli yer değiştiren, tamamen göçebe ve hafif rüzgar odaklı tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Etching / Gravür', 'Neo-Traditional', 'Fine Line Maritime'],
      bodyPlacements: ['Bilek', 'Baldır', 'Önkol'],
      compositionRole: 'Kompozisyonun alt kaide ağırlığı veya omurga kilidi',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Üst çember halka, dikey ana mil, yatay kiriş ve alttaki hilal kavis'
    },
    visualDescription: 'Zarif bir denizci halatının dolandığı, klasik kavisli kolları ve üst halkası olan çelik çapa.',
    numerologyConnection: 'Yaşam Yolu 4 ve 6',
    astrologyConnection: 'Boğa ve Yengeç',
    enneagramConnection: 'Tip 6 & Tip 1',
    visualKeywords: ['maritime anchor linework', 'anchor of hope tattoo design', 'nautical sacred anchor symbol']
  },
  {
    id: 'sym-destiny-loom',
    name: 'Kader İpliği & Mekiği (Loom & Spindle of Moira)',
    category: 'Kutsal Obje',
    subcategory: 'Kendi Kaderini Dokuma & Zamanın Deseni',
    meaning: 'Kader tanrıçalarının (Moira / Nornlar) dokuma mekiği; hayatın iplerini kendi eline alma, rastlantıları anlamlı bir desene dönüştürme ustalığı.',
    archetypes: ['Mimar', 'Dokumacı', 'Yaratıcı'],
    positiveThemes: ['kendi kaderini yaratma', 'örüntü kurma', 'zaman ustalığı', 'sabır'],
    shadowThemes: ['kader kurbanı hissetme'],
    relatedChakras: [2, 5, 6],
    relatedElements: ['Hava', 'Toprak'],
    relatedNumerology: [3, 9],
    relatedAstrology: ['Başak', 'Oğlak', 'Kova'],
    relatedEnneagram: [1, 3],
    relatedTotemThemes: ['ahşap dokuma mekiği', 'sonsuz iplik yumağı', 'kesilmeyen altın bağ'],
    suitableFor: ['Kaderin pasif bir izleyicisi değil, kendi hayat hikayesinin bizzat dokuyucusu olanlar'],
    avoidWhen: ['Tamamen anlık rastlantı ve kaos temalı tasarımlar'],
    designCompatibility: {
      recommendedStyles: ['Fine Line Threadwork', 'Geometric Minimalist', 'Engraving'],
      bodyPlacements: ['Önkol', 'Bilek Çevresi', 'Köprücük Kemiği'],
      compositionRole: 'Ögeleri birbirine bağlayan akıcı altın iplik ve merkez mekik',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Sonsuz bir kavis çizen tek bir sürekli iplik ve ortasında simetrik mekik iğnesi'
    },
    visualDescription: 'İçinden parlayan tek bir ince ipliğin aktığı antik ahşap dokuma mekiği ve dalgalanan kader bağı.',
    numerologyConnection: 'Yaşam Yolu 3 ve 9',
    astrologyConnection: 'Başak ve Kova',
    enneagramConnection: 'Tip 1 & Tip 3',
    visualKeywords: ['weaving loom spindle tattoo', 'threads of fate moira linework', 'destiny weaver needle symbol']
  },
  {
    id: 'sym-hermetic-lantern',
    name: 'Hermetik Fener & İçsel Işık (The Hermit\'s Lantern)',
    category: 'Kutsal Obje',
    subcategory: 'Karanlıkta Yol Gösteren Hakikat Işığı',
    meaning: 'Tarot Münzevi kartının elindeki fener; başkalarının onayına ihtiyaç duymadan kendi yolunu aydınlatan içsel bilgelik ve hakikat.',
    archetypes: ['Münzevi', 'Yol Gösterici', 'Işık Muhafızı'],
    positiveThemes: ['içsel rehberlik', 'bağımsız akıl', 'karanlığı aydınlatma', 'hakikat meşalesi'],
    shadowThemes: ['aşırı yalnızlık ve izolasyon'],
    relatedChakras: [3, 6, 7],
    relatedElements: ['Ateş', 'Hava'],
    relatedNumerology: [9, 7],
    relatedAstrology: ['Başak', 'Yay'],
    relatedEnneagram: [5, 4],
    relatedTotemThemes: ['altı köşeli yıldız ışığı', 'antik cam fener', 'gece yürüyüşü'],
    suitableFor: ['Toplumun kalabalıklarına kapılmadan kendi hakikat yolunda cesurca ve sessizce yürüyenler'],
    avoidWhen: ['Gürültülü, parti ve popüler eğlence temaları'],
    designCompatibility: {
      recommendedStyles: ['Etching / Gravür', 'Fine Line Dotwork Glow', 'Neo-Traditional Blackwork'],
      bodyPlacements: ['Önkol', 'Pazu', 'Baldır'],
      compositionRole: 'Kompozisyonu aydınlatan yukarı yönlü fener odağı',
      canBeAbstractedToLines: true,
      abstractGeometricEquivalent: 'Altıgen fener kafesi içinde parlayan tek nokta ve yayılan ışınlar'
    },
    visualDescription: 'Cam pencerelerinden altı köşeli bir yıldız formunda ışık saçan antik el feneri ve taşıma halkası.',
    numerologyConnection: 'Yaşam Yolu 9 ve 7',
    astrologyConnection: 'Başak ve Yay',
    enneagramConnection: 'Tip 5 & Tip 4',
    visualKeywords: ['hermits lantern tattoo', 'antique lantern linework', 'guiding light lantern engraving']
  }
];
