import { StyleLibraryItem } from '../types';

export const TATTOO_STYLES: StyleLibraryItem[] = [
  {
    id: 'fine-line',
    name: 'Fine Line',
    description: 'Son derece ince, zarif ve tek iğne hassasiyetinde işlenmiş çizgi sanatı. Minimalist ve estetik zarafet ön plandadır.',
    characteristics: ['Mikro detaylar', 'Hassas 1-3 RL iğne izleri', 'Hafif gölgelendirme', 'Yüksek zarafet'],
    recommendedNeedles: '01RL, 03RL Tek İğne (Single Needle)',
    bestBodyPlacements: ['Önkol İç', 'Bilek', 'Köprücük Kemiği', 'Kaburga', 'Boyun / Ense'],
    compatibleStyles: ['Micro Realism', 'Geometric', 'Dotwork', 'Ornamental', 'Minimalist'],
    promptKeywords: ['fine line tattoo', 'single needle intricate lines', 'delicate linework', 'clean black ink on skin', 'minimalist precision'],
    complexityRating: 3,
    visualTag: 'Zarif & İnce'
  },
  {
    id: 'linework',
    name: 'Linework',
    description: 'Sadece kontur çizgileri, çizgi kalınlık varyasyonları ve net konturlarla kompozisyon kuran temel ve güçlü dövme dili.',
    characteristics: ['Net hatlar', 'Ağırlık farkı olan çizgiler', 'Gölgelendirmesiz veya minimal doku'],
    recommendedNeedles: '03RL, 07RL, 09RL',
    bestBodyPlacements: ['Önkol', 'Pazu', 'Baldır', 'Sırt Omurga'],
    compatibleStyles: ['Geometric', 'Illustrative', 'Ornamental', 'Blackwork'],
    promptKeywords: ['linework tattoo', 'bold and thin line contrast', 'clean contour lines', 'graphic line art style'],
    complexityRating: 2,
    visualTag: 'Çizgisel & Net'
  },
  {
    id: 'blackwork',
    name: 'Blackwork',
    description: 'Yoğun, derin saf siyah mürekkep blokları, yüksek kontrastlı silüetler ve dramatik görsel etki.',
    characteristics: ['Saf siyah dolgular', 'Sıfır renk', 'Yüksek negatif alan kontrastı', 'Grafik güç'],
    recommendedNeedles: '09RS, 15M1, 23M1 Magnum dolgu',
    bestBodyPlacements: ['Kol Kaplama (Sleeve)', 'Bacak', 'Sırt', 'Omuz'],
    compatibleStyles: ['Geometric', 'Ornamental', 'Dotwork', 'Dark Surrealism', 'Tribal'],
    promptKeywords: ['blackwork tattoo', 'solid heavy black ink', 'high contrast negative space', 'bold black fills', 'dramatic darkness'],
    complexityRating: 4,
    visualTag: 'Yoğun Saf Siyah'
  },
  {
    id: 'black-and-grey',
    name: 'Black & Grey',
    description: 'Siyah mürekkebin sulandırılmasıyla elde edilen ton geçişleri (wash shades), pürüzsüz gölgeler ve klasik derinlik.',
    characteristics: ['Pürüzsüz ton geçişleri (whip shading)', 'Gri yıkama (gray wash)', 'Işık-gölge hacmi'],
    recommendedNeedles: '03RL kontur, 07M1 / 09M1 curved magnum gölge',
    bestBodyPlacements: ['Pazu', 'Göğüs', 'Sırt', 'Uyluk', 'Önkol'],
    compatibleStyles: ['Realism', 'Chicano', 'Neo Traditional', 'Surrealism', 'Dark Surrealism'],
    promptKeywords: ['black and grey tattoo', 'smooth gray wash shading', 'dramatic lighting', 'chasing shadows', 'hyper-detailed shading'],
    complexityRating: 4,
    visualTag: 'Klasik Gölgeli'
  },
  {
    id: 'realism',
    name: 'Realism',
    description: 'Fotoğraf kalitesinde derinlik, anatomik doğruluk, dokusal detaylar ve 3 boyutlu illüzyon.',
    characteristics: ['Foto-gerçekçi dokular', 'Kontursuz ton geçişleri', 'Doğal ışık yansımaları'],
    recommendedNeedles: '03RL detay, 07M1, 09M1, 13M1 soft shading',
    bestBodyPlacements: ['Pazu', 'Sırt', 'Uyluk', 'Önkol'],
    compatibleStyles: ['Black & Grey', 'Surrealism', 'Micro Realism', 'Dark Surrealism'],
    promptKeywords: ['photorealistic tattoo', 'hyperrealism skin art', 'photographic lighting', 'depth of field', 'anatomical accuracy'],
    complexityRating: 5,
    visualTag: 'Foto-Gerçekçi'
  },
  {
    id: 'micro-realism',
    name: 'Micro Realism',
    description: 'Bozuk para veya avuç içi boyutlarında minyatür foto-gerçekçi sanat. İnanılmaz mikro detaylar barındırır.',
    characteristics: ['Minyatür ölçek', 'Ultra ince iğneyle fotogerçekçilik', 'Hassas kontrast'],
    recommendedNeedles: '01RL, 03RL Single Needle & Micro Magnum',
    bestBodyPlacements: ['Önkol', 'Bilek Üstü', 'Pazu İçi', 'Ayak Bileği'],
    compatibleStyles: ['Fine Line', 'Realism', 'Illustrative'],
    promptKeywords: ['micro realism tattoo', 'miniature photorealistic tattoo', 'single needle micro details', 'hyper detailed small tattoo'],
    complexityRating: 5,
    visualTag: 'Minyatür Gerçekçilik'
  },
  {
    id: 'neo-traditional',
    name: 'Neo Traditional',
    description: 'Geleneksel motiflerin zenginleştirilmiş renk paleti, değişken çizgi kalınlıkları ve Art Nouveau zarafetiyle harmanlanması.',
    characteristics: ['Kalın dış konturlar', 'İnce iç detaylar', 'Zengin kadife tonlar', 'Organik süslemeler'],
    recommendedNeedles: '07RL, 09RL dış kontur, 07M1 renk dolgusu',
    bestBodyPlacements: ['Uyluk', 'Pazu', 'Göğüs', 'Baldır'],
    compatibleStyles: ['Traditional/Old School', 'Illustrative', 'Japanese/Irezumi'],
    promptKeywords: ['neo traditional tattoo', 'art nouveau aesthetics', 'lush color palette', 'bold dynamic outline', 'ornate floral framing'],
    complexityRating: 4,
    visualTag: 'Modern Geleneksel'
  },
  {
    id: 'traditional-old-school',
    name: 'Traditional / Old School',
    description: 'Kalın simsiyah konturlar, ikonik semboller ve sınırlı ana renk paletiyle (kırmızı, sarı, yeşil, siyah) zamansız klasik.',
    characteristics: ['Kalın 11-14 RL hatlar', 'Katı renk blokları', 'Denizci ve klasik mitik motifler'],
    recommendedNeedles: '09RL, 11RL, 14RL, 09RS',
    bestBodyPlacements: ['Pazu', 'Önkol', 'Bacak', 'Göğüs'],
    compatibleStyles: ['Neo Traditional', 'Chicano', 'Blackwork'],
    promptKeywords: ['american traditional tattoo', 'old school tattoo flash', 'bold outlines', 'solid primary colors', 'classic flash art'],
    complexityRating: 3,
    visualTag: 'Old School Klasik'
  },
  {
    id: 'new-school',
    name: 'New School',
    description: 'Abartılı oranlar, karikatürize dinamikler, parlak neon renkler ve 90’lar sokak sanatı enerjisi.',
    characteristics: ['Graffiti dinamizmi', 'Perspektif bükülmeleri', 'Çok canlı renk patlamaları'],
    recommendedNeedles: '09RL, 11RL, 15M1',
    bestBodyPlacements: ['Baldır', 'Pazu', 'Sırt'],
    compatibleStyles: ['Neo Traditional', 'Illustrative', 'Watercolor'],
    promptKeywords: ['new school tattoo', 'graffiti style illustration', 'exaggerated perspective', 'vibrant neon colors', 'whimsical cartoon energy'],
    complexityRating: 4,
    visualTag: 'Canlı & Karikatürize'
  },
  {
    id: 'japanese-irezumi',
    name: 'Japanese / Irezumi',
    description: 'Ejderhalar, koi balıkları, dalgalar, rüzgar şeritleri ve kiraz çiçekleriyle kadim Japon dövme geleneği.',
    characteristics: ['Arka plan rüzgar/su barları (mikiri)', 'Mitolojik canavarlar', 'Anatomik akışa tam uyum'],
    recommendedNeedles: '09RL - 14RL çizgi, büyük magnumlar ve tebori esintisi',
    bestBodyPlacements: ['Tam Kol Kaplama', 'Tam Sırt (Backpiece)', 'Göğüs-Pazu Paneli'],
    compatibleStyles: ['Neo Traditional', 'Illustrative', 'Black & Grey'],
    promptKeywords: ['japanese irezumi tattoo', 'wabori masterwork', 'waves and wind bars background', 'traditional oriental tattoo', 'floating world ukiyo-e'],
    complexityRating: 5,
    visualTag: 'Kadim Japon'
  },
  {
    id: 'ornamental',
    name: 'Ornamental',
    description: 'Dantel, mandalalar, kutsal süslemeler ve vücudun kıvrımlarını bir mücevher gibi saran dekoratif kalıplar.',
    characteristics: ['Mücevheratsı süslemeler', 'Kusursuz simetri', 'Vücut anatomisini vurgulama'],
    recommendedNeedles: '03RL, 05RL, 05RS',
    bestBodyPlacements: ['Göğüs Altı (Sternum)', 'Omuz-Köprücük', 'Boyun', 'Uyluk', 'El'],
    compatibleStyles: ['Geometric', 'Dotwork', 'Fine Line', 'Blackwork'],
    promptKeywords: ['ornamental tattoo', 'intricate mandala lace', 'sacred symmetry jewelry tattoo', 'body contour ornamental art'],
    complexityRating: 4,
    visualTag: 'Dekoratif & Süsleme'
  },
  {
    id: 'geometric',
    name: 'Geometric',
    description: 'Kutsal geometri, platonic katılar, fraktallar, çokgenler ve matematiksel kusursuzluk.',
    characteristics: ['Kusursuz açılar', 'Kutsal geometrik desenler', 'Optik illüzyonlar'],
    recommendedNeedles: '03RL, 05RL, 07RL hassas cetvel hassasiyeti',
    bestBodyPlacements: ['Önkol', 'Sırt Ortası', 'Göğüs', 'Baldır'],
    compatibleStyles: ['Dotwork', 'Blackwork', 'Fine Line', 'Ornamental'],
    promptKeywords: ['sacred geometry tattoo', 'metatron cube fractals', 'mathematical precision linework', 'tesseract polygons tattoo'],
    complexityRating: 4,
    visualTag: 'Kutsal Geometri'
  },
  {
    id: 'dotwork',
    name: 'Dotwork',
    description: 'Milyonlarca tekil noktanın (stippling) yoğunluk farkıyla ton, derinlik ve form oluşturduğu sabır sanatı.',
    characteristics: ['Noktasal gölgelendirme (stippling)', 'Doku zenginliği', 'Yumuşak geçişler'],
    recommendedNeedles: '03RL, 05RL düşük voltaj / tek tek nokta vuruşları',
    bestBodyPlacements: ['Omuz', 'Önkol', 'Sırt', 'Bilek'],
    compatibleStyles: ['Geometric', 'Ornamental', 'Blackwork', 'Illustrative'],
    promptKeywords: ['dotwork tattoo', 'stippling pointillism tattoo', 'intricate dot shading', 'sacred stipple art'],
    complexityRating: 4,
    visualTag: 'Noktalama / Stippling'
  },
  {
    id: 'chicano',
    name: 'Chicano',
    description: 'Pürüzsüz siyah-gri gölgeler, dini ikonografi (Meryem Ana, tespihler), maskeler ve kaligrafi yazılar.',
    characteristics: ['Kadife gibi yumuşak gri yıkamalar', 'Klasik LA sokak kültürü', 'Dramatik portreler'],
    recommendedNeedles: '03RL ince hat, 09M1 yumuşak gölgelendirme',
    bestBodyPlacements: ['Sırt', 'Göğüs', 'Önkol', 'Boyun'],
    compatibleStyles: ['Black & Grey', 'Realism', 'Illustrative'],
    promptKeywords: ['chicano style tattoo', 'smooth black and grey portraits', 'dramatic chicano shading', 'street art iconography'],
    complexityRating: 4,
    visualTag: 'Chicano Black & Grey'
  },
  {
    id: 'trash-polka',
    name: 'Trash Polka',
    description: 'Fotogerçekçilik, tipografi, soyut lekeler ve kırmızı-siyah zıtlığının agresif, avangart kolajı.',
    characteristics: ['Sadece siyah ve kırmızı', 'Boya fırçası lekeleri', 'Tipografik metinler', 'Kaotik kolaj'],
    recommendedNeedles: '03RL detay, 15M1 sert fırça efektleri, kırmızı dolgular',
    bestBodyPlacements: ['Tam Kol Kaplama', 'Sırt', 'Kaburga', 'Uyluk'],
    compatibleStyles: ['Realism', 'Abstract', 'Blackwork'],
    promptKeywords: ['trash polka tattoo', 'red and black high contrast collage', 'paint splatters and typography', 'grungy realistic abstract tattoo'],
    complexityRating: 5,
    visualTag: 'Trash Polka Avangart'
  },
  {
    id: 'surrealism',
    name: 'Surrealism',
    description: 'Bilinçaltının rüyaları, eriyen formlar, mantık dışı görsel metaforlar ve psişik sembolizm.',
    characteristics: ['Rüya mantığı', 'Dali ve Magritte esintileri', 'İmkansız perspektifler'],
    recommendedNeedles: '03RL, 07M1, 09M1',
    bestBodyPlacements: ['Önkol', 'Sırt', 'Pazu', 'Uyluk'],
    compatibleStyles: ['Realism', 'Dark Surrealism', 'Illustrative', 'Abstract'],
    promptKeywords: ['surrealism tattoo', 'dreamlike metaphysical art', 'dali inspired surrealistic elements', 'mystical symbolic illusions'],
    complexityRating: 5,
    visualTag: 'Gerçeküstü & Rüya'
  },
  {
    id: 'dark-surrealism',
    name: 'Dark Surrealism',
    description: 'Karanlık ezoterik vizyonlar, gölge arketipleri, biomekanik karanlık ve Beksinski/Giger esintisi.',
    characteristics: ['Gölge psikolojisi', 'Melankolik ve uhrevi karanlık', 'Organik-karanlık dokular'],
    recommendedNeedles: '03RL, 09M1, 15M1',
    bestBodyPlacements: ['Sırt', 'Tam Kol', 'Göğüs'],
    compatibleStyles: ['Blackwork', 'Black & Grey', 'Biomechanical', 'Etching/Engraving'],
    promptKeywords: ['dark surrealism tattoo', 'beksinski atmosphere', 'lovecraftian and esoteric dark art', 'somber macabre elegance', 'deep shadows'],
    complexityRating: 5,
    visualTag: 'Karanlık Sürrealizm'
  },
  {
    id: 'illustrative',
    name: 'Illustrative',
    description: 'Kitap illüstrasyonları, çizgi roman estetiği ve sanatsal serbest çizim tekniklerinin dövmeye uyarlanması.',
    characteristics: ['Hikaye anlatıcı kompozisyon', 'Ekspresif çizgiler', 'Tarama gölgeler (cross-hatching)'],
    recommendedNeedles: '05RL, 07RL, 07M1',
    bestBodyPlacements: ['Önkol', 'Uyluk', 'Pazu', 'Kaburga'],
    compatibleStyles: ['Etching/Engraving', 'Neo Traditional', 'Watercolor'],
    promptKeywords: ['illustrative tattoo', 'storybook engraving illustration', 'cross-hatch drawing tattoo', 'artistic ink sketch'],
    complexityRating: 4,
    visualTag: 'İllüstratif Sanat'
  },
  {
    id: 'etching-engraving',
    name: 'Etching / Engraving',
    description: 'Ortaçağ gravürleri, ahşap baskı (woodcut) ve Dürer tarzı yoğun tarama (hatching) çizgileri.',
    characteristics: ['Yoğun paralel ve çapraz taramalar', 'Antik kitap gravürü hissi', 'Arkaik mistisizm'],
    recommendedNeedles: '03RL, 05RL sıkı çizgiler',
    bestBodyPlacements: ['Önkol', 'Göğüs', 'Baldır', 'Sırt'],
    compatibleStyles: ['Illustrative', 'Blackwork', 'Dark Surrealism'],
    promptKeywords: ['woodcut etching tattoo', 'albrecht durer engraving style', 'vintage medieval book illustration', 'crosshatch ink art'],
    complexityRating: 4,
    visualTag: 'Antik Gravür'
  },
  {
    id: 'biomechanical',
    name: 'Biomechanical',
    description: 'İnsan anatomisiyle iç içe geçmiş hidrolik pistonlar, kablolar, sibernetik omurlar ve uzaylı dokuları.',
    characteristics: ['H.R. Giger biyomekanik estetiği', 'Deri altından fışkıran metal parçalar', '3D derinlik'],
    recommendedNeedles: '03RL kontur, 11M1, 15M1 derin gölge ve metalik parlamalar',
    bestBodyPlacements: ['Omuz-Kol (Sleeve)', 'Omurga Sırt', 'Bacak Baldır'],
    compatibleStyles: ['Dark Surrealism', 'Futuristic/Cyber', 'Realism'],
    promptKeywords: ['biomechanical tattoo', 'giger alien cybernetic bio-fusion', 'hydraulic pistons under skin', 'organic machine fusion'],
    complexityRating: 5,
    visualTag: 'Biyomekanik'
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    description: 'Sulu boya fırça darbeleri, renk akmaları, sıçramalar ve serbest akışkan renk geçişleri.',
    characteristics: ['Sert kontursuz renk lekeleri', 'Boya damlamaları', 'Pastel ve canlı spektrum'],
    recommendedNeedles: '07M1, 09M1, 13M1 fırça süpürme tekniği',
    bestBodyPlacements: ['Kürek Kemiği', 'Önkol', 'Kaburga', 'Uyluk'],
    compatibleStyles: ['Illustrative', 'Fine Line', 'Abstract'],
    promptKeywords: ['watercolor tattoo', 'fluid paint splatter', 'vibrant aquarelle blending', 'expressive color washes'],
    complexityRating: 4,
    visualTag: 'Sulu Boya Aquarel'
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'En az çizgiyle en derin anlamı veren, saf negatif alan ve sadelik odaklı tasarım.',
    characteristics: ['Mikro formlar', 'Tek çizgi (continuous line)', 'Maksimum sadelik'],
    recommendedNeedles: '01RL, 03RL',
    bestBodyPlacements: ['Bilek', 'Parmak', 'Kulak Arkası', 'Köprücük', 'Ayak Bileği'],
    compatibleStyles: ['Fine Line', 'Linework', 'Geometric'],
    promptKeywords: ['minimalist tattoo', 'clean micro symbol', 'simple continuous single line', 'understated minimalist tattoo'],
    complexityRating: 2,
    visualTag: 'Minimalist & Saf'
  },
  {
    id: 'abstract',
    name: 'Abstract',
    description: 'Geleneksel nesne formlarını reddeden, duygu, ritim ve saf enerji akışını anlatan soyut kompozisyonlar.',
    characteristics: ['Serbest formlar', 'Dinamik fırça izleri', 'Kişisel anlam yüklü metaforlar'],
    recommendedNeedles: '05RL, 09RS, 15M1',
    bestBodyPlacements: ['Sırt', 'Tüm Kol', 'Kaburga'],
    compatibleStyles: ['Watercolor', 'Blackwork', 'Surrealism'],
    promptKeywords: ['abstract expressionist tattoo', 'dynamic motion lines', 'avant-garde abstract composition', 'fluid conceptual ink'],
    complexityRating: 4,
    visualTag: 'Soyut / Abstrakt'
  },
  {
    id: 'tribal',
    name: 'Tribal / Kabile',
    description: 'Polinezya, Maori, Samoa ve antik kabilelerin koruma, statü ve ruhani güç taşıyan geometrik desenleri.',
    characteristics: ['Simetrik kabile kalıpları', 'Kas hatlarını vurgulayan eğriler', 'Ritüelistik anlamlar'],
    recommendedNeedles: '07RL, 09RS, 15M1 katı siyah dolgu',
    bestBodyPlacements: ['Omuz-Göğüs Paneli', 'Kol', 'Bacak Baldır'],
    compatibleStyles: ['Blackwork', 'Geometric', 'Ornamental'],
    promptKeywords: ['tribal tattoo', 'polynesian maori sacred patterns', 'black heavy tribal contours', 'warrior ritual tattoo markings'],
    complexityRating: 4,
    visualTag: 'Kabile & Tribal'
  },
  {
    id: 'futuristic-cyber',
    name: 'Futuristic / Cyber & Cyber-Sigilism',
    description: 'Siber-sigilist çizgiler, devre kartları, neon sibernetik mühürler ve dijital çağın ezoterik glifleri.',
    characteristics: ['Siber-sigilizm akışları', 'Keskin krom ve sivri uzantılar', 'Teknolojik mistisizm'],
    recommendedNeedles: '03RL, 05RL keskin hız vuruşları',
    bestBodyPlacements: ['Omurga', 'Boyun / Çene Altı', 'Önkol', 'El Üstü', 'Göğüs'],
    compatibleStyles: ['Fine Line', 'Geometric', 'Biomechanical', 'Abstract'],
    promptKeywords: ['cyber sigilism tattoo', 'futuristic neo-tribal cyber tattoo', 'chrome cybernetic sigils', 'sharp organic tech linework'],
    complexityRating: 4,
    visualTag: 'Siber & Cyber-Sigilism'
  }
];

export function getStyleById(id: string): StyleLibraryItem | undefined {
  return TATTOO_STYLES.find(s => s.id === id || s.name.toLowerCase() === id.toLowerCase());
}
